package fr.dila.solonepg.ui.enums.mgpp;

import fr.dila.st.ui.enums.ActionCategory;

public enum MgppActionCategory implements ActionCategory {
    ADMIN_VIEW_COURRIER,
    BASE_COMMUNICATION_ADD,
    BASE_COMMUNICATION_DISPLAY,
    BASE_COMMUNICATION_EDIT,
    BASE_CREATE_DOSSIER_MGPP,
    COMMUNICATION_FICHE_ACTION,
    COMMUNICATION_FICHE_EDIT_ACTION,
    COMMUNICATION_FICHE_PRINT_ACTION,
    CREATE_DOSSIER_MGPP,
    DOSSIER_PARLEMENTAIRE_ACTIONS,
    FICHE_TOPBAR_ACTIONS_LOCKS,
    MAIN_COMMUNICATION_CREER,
    MAIN_COMMUNICATION_CREER_ALERTE,
    MAIN_COMMUNICATION_DISPLAY,
    MAIN_COMMUNICATION_EDIT,
    MAIN_CREATE_DOSSIER_MGPP,
    MAIN_TRANSMETTRE_PAR_MEL,
    MGPP_CALENDRIER_MENU,
    MGPP_DECLARATION_CATEGORY,
    MGPP_DOCUMENTS_LIST_ADD,
    MGPP_DYNAMIC_LIST_PRINT_ACTION,
    MGPP_ECH_PROMULGATION_ACTIONS,
    MGPP_FDD_DOCUMENT_ACTIONS,
    MGPP_FDD_FICHE_ACTIONS,
    MGPP_NOMINATION_CATEGORY,
    MGPP_NON_DYNAMIC_LIST_PRINT_ACTION,
    MGPP_ORGANISATION_CATEGORY,
    MGPP_RAPORT_CATEGORY,
    MGPP_RECHERCHE_EXPERTE_ACTIONS,
    MGPP_SUIVI_ECHEANCES_ACTIONS,
    ONGLET_DOSSIER_MGPP,
    ONGLET_DOSSIER_SIMPLE_MGPP,
    REPRESENTANTS_TABLE_ACTIONS,
    REPRESENTANTS_TABLE_LINE_ACTIONS,
    TABLE_REFERENCE_EPP_ACTIONS,
    TABLE_REFERENCE_MINSELECTEUR_ACTIONS;

    @Override
    public String getName() {
        return name();
    }
}
