package fr.dila.solonepg.api.activitenormative;

import fr.dila.solonepg.api.constant.ActiviteNormativeStatsConstants;

/**
 * classe enum qui represente tous les raports des stats pour l'activite normatives
 * 
 * 
 */
public enum ANReportEnum {

	/*##################################################################################################################
	 * 											APPLICATION DES LOIS
	 ###################################################################################################################*/
	
	TAB_AN_TABLEAU_BORD_ACTIVE("TAB_AN_TABLEAU_BORD_ACTIVE",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_ACTIVES_NON_PUBLIEES_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_ACTIVES_NON_PUBLIEES_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_ACTIVES_NON_PUBLIEES_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_ACTIVE_ALL(
			"TAB_AN_TABLEAU_BORD_ACTIVE_ALL",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_ACTIVES_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_ACTIVES_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_ACTIVES_ALL_REPORT_LIBELLE),

	TAB_AN_MESURES_APPLICATION_LOI(
			"TAB_AN_MESURES_APPLICATION_LOI",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_LOI_NON_PUBLIEES_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_LOI_NON_PUBLIEES_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_LOI_NON_PUBLIEES_REPORT_LIBELLE),
	
	TAB_AN_TABLEAU_BORD_DIFFEREE(
			"TAB_AN_TABLEAU_BORD_DIFFEREE",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DIFFEREE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DIFFEREE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DIFFEREE_REPORT_LIBELLE),

	TAB_AN_MESURES_APPLICATION_LOI_ALL(
			"TAB_AN_MESURES_APPLICATION_LOI_ALL",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_LOI_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_LOI_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_LOI_ALL_REPORT_LIBELLE),
	
	TAB_AN_BILAN_SEMESTRIEL_LOI(
			"TAB_AN_BILAN_SEMESTRIEL_LOI",
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_LOI_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_LOI_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_LOI_REPORT_LIBELLE),

	TAB_AN_TAUX_APPLICATION_LOI(
			"TAB_AN_TAUX_APPLICATION_LOI",
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_LOI_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_LOI_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_LOI_REPORT_LIBELLE),
	
	TAB_AN_TAUX_APPLICATION_LOI_ALL(
			"TAB_AN_TAUX_APPLICATION_LOI_ALL",
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_LOI_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_LOI_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_LOI_ALL_REPORT_LIBELLE),

	TAB_AN_MESURE_APPLICATION_MIN(
			"TAB_AN_MESURE_APPLICATION_MIN",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_NON_PUBLIEES_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_NON_PUBLIEES_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_NON_PUBLIEES_REPORT_LIBELLE),

	TAB_AN_MESURE_APPLICATION_MIN_ALL(
			"TAB_AN_MESURE_APPLICATION_MIN_ALL",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_ALL_REPORT_LIBELLE),

	TAB_AN_DEBUT_LEGISLATURE_MIN(
			"TAB_AN_DEBUT_LEGISLATURE_MIN",
			ActiviteNormativeStatsConstants.AN_TAUX_DEBUT_LEGISLATURE_PAR_MIN_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DEBUT_LEGISLATURE_PAR_MIN_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DEBUT_LEGISLATURE_PAR_MIN_REPORT_LIBELLE),

	TAB_AN_BILAN_SEMESTRIEL_MIN(
			"TAB_AN_BILAN_SEMESTRIEL_MIN",
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_MIN_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_MIN_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_MIN_REPORT_LIBELLE),

	TAB_AN_TAUX_APPLICATION_MIN(
			"TAB_AN_TAUX_APPLICATION_MIN",
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_MIN_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_MIN_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_MIN_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_DEPASSE(
			"TAB_AN_TABLEAU_BORD_DEPASSE",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DEPASSES_NON_PUBLIEES_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DEPASSES_NON_PUBLIEES_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DEPASSES_NON_PUBLIEES_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_DEPASSE_ALL(
			"TAB_AN_TABLEAU_BORD_DEPASSE_ALL",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DEPASSES_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DEPASSES_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DEPASSES_ALL_REPORT_LIBELLE),

	TAB_AN_STAT_DEBUT_LEGISLATURE(
			"TAB_AN_STAT_DEBUT_LEGISLATURE",
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_LOIS_PROMULGUEES_DEBUT_LEGISTRATURE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_LOIS_PROMULGUEES_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_LOIS_PROMULGUEES_DEBUT_LEGISLATURE_REPORT_LIBELLE),

	TAB_AN_STAT_MISE_APPLICATION(
			"TAB_AN_STAT_MISE_APPLICATION",
			ActiviteNormativeStatsConstants.AN_DELAIS_MISE_APPLICATION_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_DELAIS_MISE_APPLICATION_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_DELAIS_MISE_APPLICATION_REPORT_LIBELLE),

	TAB_AN_STAT_DERNIERE_SESSION(
			"TAB_AN_STAT_DERNIERE_SESSION",
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_LOIS_PROMULGUEES_DERNIERE_SESSION_PARLEMENTAIRE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_LOIS_PROMULGUEES_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_LOIS_PROMULGUEES_DERNIERE_SESSION_PARLEMENTAIRE_REPORT_LIBELLE),

	TAB_AN_BILAN_SEM_LOI_TOUS(
			"TAB_AN_BILAN_SEM_LOI_TOUS",
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_LOI_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_LOI_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_LOI_REPORT_LIBELLE),

	TAB_AN_BILAN_SEM_MIN_TOUS(
			"TAB_AN_BILAN_SEM_MIN_TOUS",
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_MINISTERE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_MINISTERE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_MINISTERE_REPORT_LIBELLE),

	TAB_AN_BILAN_SEM_NATURE(
			"TAB_AN_BILAN_SEM_NATURE",
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_NATURE_TEXTE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_NATURE_TEXTE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_NATURE_TEXTE_REPORT_LIBELLE),

	TAB_AN_BILAN_SEM_VOTE(
			"TAB_AN_BILAN_SEM_VOTE",
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_PROCEDURE_VOTE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_PROCEDURE_VOTE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_PROCEDURE_VOTE_REPORT_LIBELLE),

	TAB_AN_FIL_EAU_GLOBAL(
			"TAB_AN_FIL_EAU_GLOBAL",
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_GLOBAL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_GLOBAL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_GLOBAL_REPORT_LIBELLE),

	TAB_AN_FIL_EAU_LOI_TOUS(
			"TAB_AN_FIL_EAU_LOI_TOUS",
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_LOI_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_LOI_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_LOI_REPORT_LIBELLE),

	TAB_AN_FIL_EAU_LOI_TOUS_ALL(
			"TAB_AN_FIL_EAU_LOI_TOUS_ALL",
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_LOI_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_LOI_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_LOI_ALL_REPORT_LIBELLE),

	TAB_AN_FIL_EAU_MIN_TOUS(
			"TAB_AN_FIL_EAU_MIN_TOUS",
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_MINISTERE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_MINISTERE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_MINISTERE_REPORT_LIBELLE),

	TAB_AN_FIL_EAU_NATURE(
			"TAB_AN_FIL_EAU_NATURE",
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_NATURE_TEXTE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_NATURE_TEXTE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_NATURE_TEXTE_REPORT_LIBELLE),

	TAB_AN_FIL_EAU_VOTE(
			"TAB_AN_FIL_EAU_VOTE",
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_PROCEDURE_VOTE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_PROCEDURE_VOTE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_PROCEDURE_VOTE_REPORT_LIBELLE),

	TAB_AN_DELAI_LOI_TOUS(
			"TAB_AN_DELAI_LOI_TOUS",
			ActiviteNormativeStatsConstants.AN_DELAI_LOI_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_DELAI_LOI_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_DELAI_LOI_REPORT_LIBELLE),

	TAB_AN_DELAI_MIN_TOUS(
			"TAB_AN_DELAI_MIN_TOUS",
			ActiviteNormativeStatsConstants.AN_DELAI_MINISTERE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_DELAI_MINISTERE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_DELAI_MINISTERE_REPORT_LIBELLE),

	TAB_AN_DELAI_NATURE_TOUS(
			"TAB_AN_DELAI_NATURE_TOUS",
			ActiviteNormativeStatsConstants.AN_DELAI_NATURE_TEXTE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_DELAI_NATURE_TEXTE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_DELAI_NATURE_TEXTE_REPORT_LIBELLE),

	TAB_AN_COURBE_TOUS(
			"TAB_AN_COURBE_TOUS",
			ActiviteNormativeStatsConstants.AN_COURBE_PUBLICATION_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_COURBE_PUBLICATION_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_COURBE_PUBLICATION_REPORT_LIBELLE),
	
	/*##################################################################################################################
	 * 											APPLICATION DES ORDONNANCES
	 ###################################################################################################################*/
	
	TAB_AN_MESURES_APP_ORDONNANCES(
			"TAB_AN_MESURES_APP_ORDONNANCES",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_ORDO_APP_ORDO_NON_PUBLIEES_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_ORDO_APP_ORDO_NON_PUBLIEES_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_ORDO_APP_ORDO_NON_PUBLIEES_REPORT_LIBELLE),

	TAB_AN_MESURES_APP_ORDONNANCES_ALL(
			"TAB_AN_MESURES_APP_ORDONNANCES_ALL",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_ORDO_APP_ORDO_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_ORDO_APP_ORDO_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_ORDO_APP_ORDO_ALL_REPORT_LIBELLE),

	TAB_AN_BILAN_SEMESTRIEL_SUB_APP_ORDONNANCES(
			"TAB_AN_BILAN_SEMESTRIEL_SUB_APP_ORDONNANCES",
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_ORDO_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_ORDO_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_ORDO_APP_ORDO_REPORT_LIBELLE),

	TAB_AN_TAUX_APPLICATION_ORDO(
			"TAB_AN_TAUX_APPLICATION_SUB_APP_ORDONNANCES",
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_ORDO_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_ORDO_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_ORDO_REPORT_LIBELLE),

	TAB_AN_TAUX_APPLICATION_SUB_APP_ORDONNANCES_ALL(
			"TAB_AN_TAUX_APPLICATION_SUB_APP_ORDONNANCES_ALL",
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_ORDO_ALL_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_ORDO_ALL_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_ORDO_ALL_REPORT_LIBELLE),

	TAB_AN_MESURE_APPLICATION_MIN_APP_ORDO(
			"TAB_AN_MESURE_APPLICATION_MIN_APP_ORDO",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_NON_PUBLIEES_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_NON_PUBLIEES_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_NON_PUBLIEES_REPORT_LIBELLE),

	TAB_AN_MESURE_APPLICATION_MIN_APP_ORDO_ALL(
			"TAB_AN_MESURE_APPLICATION_MIN_APP_ORDO_ALL",
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_APP_ORDO_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_APP_ORDO_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_PAR_MIN_ALL_REPORT_LIBELLE),

	TAB_AN_DEBUT_LEGISLATURE_MIN_APP_ORDO(
			"TAB_AN_DEBUT_LEGISLATURE_MIN_APP_ORDO",
			ActiviteNormativeStatsConstants.AN_TAUX_DEBUT_LEGISLATURE_PAR_MIN_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DEBUT_LEGISLATURE_PAR_MIN_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DEBUT_LEGISLATURE_PAR_MIN_APP_ORDO_REPORT_LIBELLE),

	TAB_AN_BILAN_SEMESTRIEL_MIN_APP_ORDO(
			"TAB_AN_BILAN_SEMESTRIEL_MIN_APP_ORDO",
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_MIN_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_MIN_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_PAR_MIN_REPORT_LIBELLE),

	TAB_AN_TAUX_APPLICATION_MIN_APP_ORDO(
			"TAB_AN_TAUX_APPLICATION_MIN_APP_ORDO",
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_MIN_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_MIN_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_APPLICATION_PAR_MIN_REPORT_LIBELLE),

	TAB_AN_FIL_EAU_GLOBAL_APP_ORDONNANCE(
			"TAB_AN_FIL_EAU_GLOBAL_APP_ORDONNANCE",
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_GLOBAL_APP_ORDONNANCE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_GLOBAL_APP_ORDONNANCE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_GLOBAL_REPORT_LIBELLE),

	TAB_AN_FIL_EAU_ORDO_TOUS_APP_ORDONNANCE(
			"TAB_AN_FIL_EAU_ORDO_TOUS_APP_ORDONNANCE",
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_APP_ORDONNANCE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_APP_ORDONNANCE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_LOI_ORDO_APP_ORDO_REPORT_LIBELLE),

	TAB_AN_FIL_EAU_ORDO_TOUS_APP_ORDONNANCE_ALL(
			"TAB_AN_FIL_EAU_ORDO_TOUS_APP_ORDONNANCE_ALL",
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_ORDO_APP_ORDO_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_ORDO_APP_ORDO_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_LOI_ORDO_APP_ORDO_REPORT_LIBELLE),

	TAB_AN_FIL_EAU_MIN_TOUS_APP_ORDONNANCE(
			"TAB_AN_FIL_EAU_MIN_TOUS_APP_ORDONNANCE",
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_MINISTERE_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_MINISTERE_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_DAPPLICATION_FIL_EAU_TAUX_TOUS_MINISTERE_REPORT_LIBELLE),

	TAB_AN_DELAI_ORDO_TOUS_APP_ORDO(
			"TAB_AN_DELAI_ORDO_TOUS_APP_ORDO",
			ActiviteNormativeStatsConstants.AN_DELAI_ORDO_REPORT_NAME_APP_ORDO,
			ActiviteNormativeStatsConstants.AN_DELAI_ORDO_REPORT_FILE_APP_ORDO,
			ActiviteNormativeStatsConstants.AN_DELAI_ORDO_APP_ORDO_REPORT_LIBELLE),

	TAB_AN_DELAI_MIN_TOUS_APP_ORDO(
			"TAB_AN_DELAI_MIN_TOUS_APP_ORDO",
			ActiviteNormativeStatsConstants.AN_DELAI_MINISTERE_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_DELAI_MINISTERE_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_DELAI_MINISTERE_REPORT_LIBELLE),

	TAB_AN_COURBE_TOUS_APP_ORDO(
			"TAB_AN_COURBE_TOUS_APP_ORDO",
			ActiviteNormativeStatsConstants.AN_COURBE_PUBLICATION_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_COURBE_PUBLICATION_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_COURBE_PUBLICATION_REPORT_LIBELLE),

	TAB_AN_TB_APP_ORDO_DEPASSE(
			"TAB_AN_TB_APP_ORDO_DEPASSE",
			ActiviteNormativeStatsConstants.AN_MES_APP_DEP_NON_PUB_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MES_APP_DEP_NON_PUB_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DEPASSES_NON_PUBLIEES_REPORT_LIBELLE),

	TAB_AN_TB_APP_ORDO_DEPASSE_ALL(
			"TAB_AN_TB_APP_ORDO_DEPASSE_ALL",
			ActiviteNormativeStatsConstants.AN_MES_APP_DEP_ALL_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MES_APP_DEP_ALL_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DEPASSES_ALL_REPORT_LIBELLE),

	TAB_AN_TB_APP_ORDO_ACTIVE(
			"TAB_AN_TB_APP_ORDO_ACTIVE",
			ActiviteNormativeStatsConstants.AN_MES_APP_ACTIVES_NON_PUB_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MES_APP_ACTIVES_NON_PUB_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_ACTIVES_NON_PUBLIEES_REPORT_LIBELLE),

	TAB_AN_TB_APP_ORDO_ACTIVE_ALL(
			"TAB_AN_TB_APP_ORDO_ACTIVE_ALL",
			ActiviteNormativeStatsConstants.AN_MES_APP_ACTIVES_ALL_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MES_APP_ACTIVES_ALL_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_ACTIVES_ALL_REPORT_LIBELLE),

	TAB_AN_TB_APP_ORDO_DIFFEREE(
			"TAB_AN_TB_APP_ORDO_DIFFEREE",
			ActiviteNormativeStatsConstants.AN_MES_APP_DIFFEREE_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_MES_APP_DIFFEREE_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_MESURES_APPLICATION_DIFFEREE_REPORT_LIBELLE),

	TAB_AN_BILAN_SEM_ORDONNANCE_TOUS(
			"TAB_AN_BILAN_SEM_ORDONNANCE_TOUS",
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_ORDONNANCE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_ORDONNANCE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_ORDONNANCE_REPORT_LIBELLE),

	TAB_AN_BILAN_SEM_MIN_TOUS_ORDONNANCE(
			"TAB_AN_BILAN_SEM_MIN_TOUS_ORDONNANCE",
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_MINISTERE_ORDONNANCE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_MINISTERE_ORDONNANCE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_BILAN_SEMESTRIELS_TOUS_MINISTERE_REPORT_LIBELLE),

	TAB_AN_INDIC_APP_ORDO_DEBUT_LEGISLATURE(
			"TAB_AN_INDIC_APP_ORDO_DEBUT_LEGISLATURE",
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_ORDOS_PROMULGUEES_DEBUT_LEGISLATURE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_ORDOS_PROMULGUEES_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_ORDOS_PROMULGUEES_DEBUT_LEGISLATURE_REPORT_LIBELLE),

	TAB_AN_INDIC_APP_ORDO_MISE_APPLI(
			"TAB_AN_INDIC_APP_ORDO_MISE_APPLI",
			ActiviteNormativeStatsConstants.AN_DELAIS_MISE_APPLI_APP_ORDO_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_DELAIS_MISE_APPLI_APP_ORDO_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_DELAIS_MISE_APPLICATION_REPORT_LIBELLE),

	TAB_AN_INDIC_APP_ORDO_DERNIERE_SESSION(
			"TAB_AN_INDIC_APP_ORDO_DERNIERE_SESSION",
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_ORDOS_PROMULGUEES_DERNIERE_SESSION_PARLEMENTAIRE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_ORDOS_PROMULGUEES_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TAUX_EXECUTION_ORDOS_PROMULGUEES_DERNIERE_SESSION_PARLEMENTAIRE_REPORT_LIBELLE),
	
	/*##################################################################################################################
	 * 											TRANSPOSITION DES DIRECTIVES
	 ###################################################################################################################*/
	
	TAB_AN_TABLEAU_BORD_TRANSPOSITION_ACHEVEE(
			"TAB_AN_TABLEAU_BORD_TRANSPOSITION_ACHEVEE",
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ACHEVEE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ACHEVEE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ACHEVEE_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_TRANSPOSITION_MIN_ACHEVEE(
			"TAB_AN_TABLEAU_BORD_TRANSPOSITION_MIN_ACHEVEE",
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_MIN_ACHEVEE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_MIN_ACHEVEE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_MIN_ACHEVEE_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_TRANSPOSITION_ENCOURS(
			"TAB_AN_TABLEAU_BORD_TRANSPOSITION_ENCOURS",
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ENCOURS_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ENCOURS_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ENCOURS_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_TRANSPOSITION_MIN_ENCOURS(
			"TAB_AN_TABLEAU_BORD_TRANSPOSITION_MIN_ENCOURS",
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_MIN_ENCOURS_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_MIN_ENCOURS_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_MIN_ENCOURS_REPORT_LIBELLE),

	TAB_AN_STAT_INDICATEUR_MIN_TRANS(
			"TAB_AN_STAT_INDICATEUR_MIN_TRANS",
			ActiviteNormativeStatsConstants.AN_STAT_INDICATEUR_MIN_TRANS_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_STAT_INDICATEUR_MIN_TRANS_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_STAT_INDICATEUR_MIN_TRANS_REPORT_LIBELLE),

	TAB_AN_STAT_RETARD_MOY_TRANS(
			"TAB_AN_STAT_RETARD_MOY_TRANS",
			ActiviteNormativeStatsConstants.AN_STAT_RETARD_MOY_TRANS_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_STAT_RETARD_MOY_TRANS_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_STAT_RETARD_MOY_TRANS_REPORT_LIBELLE),

	TAB_AN_STAT_REPARTITION_DIR_APRENDRE(
			"TAB_AN_STAT_REPARTITION_DIR_APRENDRE",
			ActiviteNormativeStatsConstants.AN_STAT_REPARTITION_DIR_APRENDRE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_STAT_REPARTITION_DIR_APRENDRE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_STAT_REPARTITION_DIR_APRENDRE_REPORT_LIBELLE),

	TAB_AN_TRANSPOSITION_ACHEVEE_MIN(
			"TAB_AN_TRANSPOSITION_ACHEVEE_MIN",
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ACHEVEE_MIN_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ACHEVEE_MIN_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ACHEVEE_MIN_REPORT_LIBELLE),

	TAB_AN_TRANSPOSITION_ENCOURS_MIN(
			"TAB_AN_TRANSPOSITION_ENCOURS_MIN",
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ENCOURS_MIN_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ENCOURS_MIN_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TRANSPOSITION_ENCOURS_MIN_REPORT_LIBELLE),
	
	/*##################################################################################################################
	 * 											SUIVI DES HABILITATIONS
	 ###################################################################################################################*/
	
	TAB_AN_HABILITATION_FLTR_MIN(
			"TAB_AN_HABILITATION_FLTR_MIN",
			ActiviteNormativeStatsConstants.AN_HABILITATION_FLTR_MIN_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_HABILITATION_FLTR_MIN_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_HABILITATION_FLTR_MIN_REPORT_LIBELLE),

	TAB_AN_HABILITATION_FLTR_MIN_ALL(
			"TAB_AN_HABILITATION_FLTR_MIN_ALL",
			ActiviteNormativeStatsConstants.AN_HABILITATION_FLTR_MIN_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_HABILITATION_FLTR_MIN_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_HABILITATION_FLTR_MIN_ALL_REPORT_LIBELLE),

	TAB_AN_HABILITATION_SS_FLTR_MIN(
			"TAB_AN_HABILITATION_SS_FLTR_MIN",
			ActiviteNormativeStatsConstants.AN_HABILITATION_SS_FLTR_MIN_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_HABILITATION_SS_FLTR_MIN_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_HABILITATION_SS_FLTR_MIN_REPORT_LIBELLE),

	TAB_AN_HABILITATION_SS_FLTR_MIN_ALL(
			"TAB_AN_HABILITATION_SS_FLTR_MIN_ALL",
			ActiviteNormativeStatsConstants.AN_HABILITATION_SS_FLTR_MIN_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_HABILITATION_SS_FLTR_MIN_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_HABILITATION_SS_FLTR_MIN_ALL_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_HABILITATION_FILTRE(
			"TAB_AN_TABLEAU_BORD_HABILITATION_FILTRE",
			ActiviteNormativeStatsConstants.AN_AN_TABLEAU_BORD_HABILITATION_FILTRE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_AN_TABLEAU_BORD_HABILITATION_FILTRE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_AN_TABLEAU_BORD_HABILITATION_FILTRE_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_HABILITATION_FILTRE_ALL(
			"TAB_AN_TABLEAU_BORD_HABILITATION_FILTRE_ALL",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_HABILITATION_FILTRE_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_HABILITATION_FILTRE_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_HABILITATION_FILTRE_ALL_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_HABILITATION_SS_FILTRE(
			"TAB_AN_TABLEAU_BORD_HABILITATION_SS_FILTRE",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_HABILITATION_SS_FILTRE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_HABILITATION_SS_FILTRE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_HABILITATION_SS_FILTRE_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_HABILITATION_SS_FILTRE_ALL(
			"TAB_AN_TABLEAU_BORD_HABILITATION_SS_FILTRE_ALL",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_HABILITATION_SS_FILTRE_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_HABILITATION_SS_FILTRE_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_HABILITATION_SS_FILTRE_ALL_REPORT_LIBELLE),
	
	/*##################################################################################################################
	 * 											RATIFICATION DES ORDONNANCES
	 ###################################################################################################################*/
	
	TAB_AN_RATIFICATION_741_MIN(
			"TAB_AN_RATIFICATION_741_MIN",
			ActiviteNormativeStatsConstants.AN_RATIFICATION_741_MIN_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_RATIFICATION_741_MIN_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_RATIFICATION_741_MIN_REPORT_LIBELLE),

	TAB_AN_RATIFICATION_741_MIN_ALL(
			"TAB_AN_RATIFICATION_741_MIN_ALL",
			ActiviteNormativeStatsConstants.AN_RATIFICATION_741_MIN_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_RATIFICATION_741_MIN_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_RATIFICATION_741_MIN_ALL_REPORT_LIBELLE),

	TAB_AN_RATIFICATION_38C_MIN(
			"TAB_AN_RATIFICATION_38C_MIN",
			ActiviteNormativeStatsConstants.AN_RATIFICATION_38C_MIN_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_RATIFICATION_38C_MIN_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_RATIFICATION_38C_MIN_REPORT_LIBELLE),

	TAB_AN_RATIFICATION_38C_MIN_ALL(
			"TAB_AN_RATIFICATION_38C_MIN_ALL",
			ActiviteNormativeStatsConstants.AN_RATIFICATION_38C_MIN_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_RATIFICATION_38C_MIN_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_RATIFICATION_38C_MIN_ALL_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_RATIFICATION_PAS_DEPOSE(
			"TAB_AN_TABLEAU_BORD_RATIFICATION_PAS_DEPOSE",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_PAS_DEPOSE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_PAS_DEPOSE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_PAS_DEPOSE_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_RATIFICATION_38C(
			"TAB_AN_TABLEAU_BORD_RATIFICATION_38C",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_38C_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_38C_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_38C_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_RATIFICATION_38C_ALL(
			"TAB_AN_TABLEAU_BORD_RATIFICATION_38C_ALL",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_38C_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_38C_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_38C_ALL_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_RATIFICATION_741(
			"TAB_AN_TABLEAU_BORD_RATIFICATION_741",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_741_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_741_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_741_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_RATIFICATION_741_ALL(
			"TAB_AN_TABLEAU_BORD_RATIFICATION_741_ALL",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_741_ALL_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_741_ALL_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_741_ALL_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_RATIFICATION_DECRET(
			"TAB_AN_TABLEAU_BORD_RATIFICATION_DECRET",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_DECRET_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_DECRET_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_RATIFICATION_DECRET_REPORT_LIBELLE),
	
	/*##################################################################################################################
	 * 											TRAITES ET ACCORDS
	 ###################################################################################################################*/

	TAB_AN_TRAITE_PUB_AVENIR_MIN(
			"TAB_AN_TRAITE_PUB_AVENIR_MIN",
			ActiviteNormativeStatsConstants.AN_TRAITE_PUB_AVENIR_MIN_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TRAITE_PUB_AVENIR_MIN_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TRAITE_PUB_AVENIR_MIN_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_TRAITE_PUB_INTERVENUE(
			"TAB_AN_TABLEAU_BORD_TRAITE_PUB_INTERVENUE",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_TRAITE_PUB_INTERVENUE_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_TRAITE_PUB_INTERVENUE_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_TRAITE_PUB_INTERVENUE_REPORT_LIBELLE),

	TAB_AN_TABLEAU_BORD_TRAITE_PUB_INTERVENIR(
			"TAB_AN_TABLEAU_BORD_TRAITE_PUB_INTERVENIR",
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_TRAITE_PUB_INTERVENIR_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_TRAITE_PUB_INTERVENIR_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_TABLEAU_BORD_TRAITE_PUB_INTERVENIR_REPORT_LIBELLE),

	TAB_AN_STAT_TRAITE_ETUDES_IMPACT(
			"TAB_AN_STAT_TRAITE_ETUDES_IMPACT",
			ActiviteNormativeStatsConstants.AN_STAT_TRAITE_ETUDES_IMPACT_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_STAT_TRAITE_ETUDES_IMPACT_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_STAT_TRAITE_ETUDES_IMPACT_REPORT_LIBELLE),

	TAB_AN_STAT_TRAITE_PUBLIER(
			"TAB_AN_STAT_TRAITE_PUBLIER",
			ActiviteNormativeStatsConstants.AN_STAT_TRAITE_PUBLIER_REPORT_NAME,
			ActiviteNormativeStatsConstants.AN_STAT_TRAITE_PUBLIER_REPORT_FILE,
			ActiviteNormativeStatsConstants.AN_STAT_TRAITE_PUBLIER_REPORT_LIBELLE);

	private String	id;
	private String	name;
	private String	file;
	private String	libelle;

	ANReportEnum(String id, String name, String file, String libelle) {
		this.id = id;
		this.setName(name);
		this.setFile(file);
		this.setLibelle(libelle);

	}

	public static ANReportEnum getById(String id) {
		for (ANReportEnum elem : ANReportEnum.values()) {
			if (elem.getId().equals(id)) {
				return elem;
			}
		}
		return null;
	}

	protected void setId(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	private void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	private void setFile(String file) {
		this.file = file;
	}

	public String getFile() {
		return file;
	}

	private void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getLibelle() {
		return libelle;
	}

	public static ANReportEnum getReportByFileName(String birtReportFileName) {
		ANReportEnum report = null;
		for (ANReportEnum value : ANReportEnum.values()) {
			if (value.getFile().equals(birtReportFileName)) {
				report = value;
			}
		}

		return report;
	}

}
