ALTER TABLE "TABLE_REFERENCE"
add
   (
   "POSTEPUBLICATIONID" NVARCHAR2(2000),  
   "POSTEDANID" NVARCHAR2(2000)
   );
   
ALTER TABLE "TABLE_REFERENCE" ADD CONSTRAINT "POSTEPUBLI_FK" FOREIGN KEY ("POSTEPUBLICATIONID")
	  REFERENCES "POSTE" ("ID_ORGANIGRAMME") ON DELETE CASCADE ENABLE;
ALTER TABLE "TABLE_REFERENCE" ADD CONSTRAINT "POSTEDAN_FK" FOREIGN KEY ("POSTEDANID")
	  REFERENCES "POSTE" ("ID_ORGANIGRAMME") ON DELETE CASCADE ENABLE;
commit;

