CREATE OR REPLACE PROCEDURE CREATE_NEW_SEQUENCE(seqName VARCHAR2)
IS
  request VARCHAR2(2000);
BEGIN
    request := 'CREATE SEQUENCE '||seqName||' START WITH 0 MINVALUE 0 MAXVALUE 99999 NOCACHE NOORDER NOCYCLE';
    EXECUTE IMMEDIATE request;
END;
/
