UPDATE VOC_PERIODICITE_RAPPORT SET "label"='Rapport unique' WHERE "id"='RAPPORT_UNIQUE';
UPDATE VOC_PERIODICITE_RAPPORT SET "label"='Rapport d’application de la loi' WHERE "id"='RAPPORT_RELATIF_ARTICLE_67_LOI_N_2004-1343';
UPDATE VOC_PERIODICITE_RAPPORT SET "label"='Rapport périodique' WHERE "id"='RAPPORT_PERIODIQUE';
commit;
