DELETE FROM BIRT_REFRESH_FICHIER WHERE ID NOT IN (select ID from hierarchy);
commit;
ALTER TABLE "BIRT_REFRESH_FICHIER" ADD CONSTRAINT "BIRT_REFRESH_FICHIER_PK" PRIMARY KEY ("ID") ENABLE; 
ALTER TABLE "BIRT_REFRESH_FICHIER" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "BIRT_REFRESH_FICHIER" ADD CONSTRAINT "BIRT_REF_HIER_FK" FOREIGN KEY ("ID")
  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE;
  
DELETE FROM EXPORT_PAN_STAT WHERE ID NOT IN (select ID from hierarchy);
commit;
ALTER TABLE "EXPORT_PAN_STAT" ADD CONSTRAINT "EXPORT_PAN_STAT_PK" PRIMARY KEY ("ID") ENABLE; 
ALTER TABLE "EXPORT_PAN_STAT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "EXPORT_PAN_STAT" ADD CONSTRAINT "EXP_PAN_REF_HIER_FK" FOREIGN KEY ("ID")
  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE;
  
  
DELETE FROM FICHE_PRESENTATION_DECRET WHERE ID NOT IN (select ID from hierarchy);
commit;
ALTER TABLE "FICHE_PRESENTATION_DECRET" ADD CONSTRAINT "FP_DECRET_REF_HIER_FK" FOREIGN KEY ("ID")
  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE;
  
DELETE FROM NOTIFICATION_DOC WHERE ID NOT IN (select ID from hierarchy);
commit;
ALTER TABLE "NOTIFICATION_DOC" ADD CONSTRAINT "NOTIFDOC_PK" PRIMARY KEY ("ID") ENABLE; 
ALTER TABLE "NOTIFICATION_DOC" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "NOTIFICATION_DOC" ADD CONSTRAINT "NOTIFDOC_REF_HIER_FK" FOREIGN KEY ("ID")
  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE;
  

  