-- dans cette vue ont été modifiés les liens avec VOC_MODE_PARUTION et VOC_VECTEUR_PUBLICATION qui ont été supprimées
CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_PUB  AS
SELECT '0' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION, 
  DOS.MINISTERERESP, TO_CHAR (DOS.DATEPRECISEEPUBLICATION, 'DD/MM/YYYY') AS DATEPRECISEPUB,
  NVL(MP."MODE",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, RETOUR_DILA RD, VOC_PUBLICATION_DELAI VPD, MODE_PARUTION MP
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND RD.MODEPARUTION =  MP.id(+)
AND DOS.DELAIPUBLICATION = VPD."id" (+)
AND RD.ID = DOS.ID
AND EXISTS ( 	SELECT 1 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
        		AND   ROU.DATEFINETAPE IS NULL
				AND   ROU.TYPE IN (13) )
AND (SELECT vp.vppos
        FROM DOS_VECTEURPUBLICATION VEC, vecteur_publication vp
        WHERE VEC.ID = DOS.ID
        AND VEC.ITEM = vp.id) = 1 -- 1 = Journal officiel
UNION
SELECT '1' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, TP.PUBLICATIONDELAI DELAIPUBLICATION, DOS.MINISTERERESP,
  TP.PUBLICATIONMODEPUBLICATION MODEPARUTION, TO_CHAR (TP.PUBLICATIONDATEDEMANDE, 'DD/MM/YYYY')  AS DATEPRECISEPUB,
  NVL(MP."MODE",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, RETOUR_DILA RD, MODE_PARUTION MP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
AND TP.PUBLICATIONMODEPUBLICATION = MP."ID" (+)
AND TP.PUBLICATIONDELAI = VPD."id" (+)
AND TP.PUBLICATIONNOMPUBLICATION = '1'
AND DOS.ID = TP.ID;

-- Cette vue est recréée uniquement pour une optimisation sur la colonne VOC_VECTEUR_PUBLICATION_TP.id
CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_RIG  AS
SELECT DISTINCT DOS.*
FROM DOSSIER_SOLON_EPG DOS,
     TRAITEMENT_PAPIER TP
WHERE DOS.ID = TP.ID
AND   DOS.STATUTARCHIVAGE IN ('1', '2')
AND(
( 
	EXISTS
	(
		SELECT 1
		FROM ACTIONNABLE_CASE_LINK ACT, CASE_LINK CAS, ROUTING_TASK ROU
		WHERE DOS.ID = CAS.CASEDOCUMENTID
		AND   CAS.ID = ACT.ID
		AND   ACT.ROUTINGTASKID = ROU.ID
		AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
    AND   ROU.DATEFINETAPE IS NULL
		AND   ROU.TYPE = 13
		AND   DOS.DELAIPUBLICATION = 3
	)
  AND ( 
    SELECT vP.id 
    FROM DOS_VECTEURPUBLICATION VEC, VECTEUR_PUBLICATION VP
    WHERE VEC.ID = DOS.ID
    AND VEC.ITEM = VP.id
  ) = 1
)
OR (
  TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY') 
  AND   TP.PUBLICATIONDELAI = 3
  AND TP.PUBLICATIONNOMPUBLICATION = '1'
));

-- Cette vue a été modifiée pour les modes de parution
CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_JO_BO  AS
SELECT DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION, 
  TO_CHAR (DOS.POURFOURNITUREEPREUVE, 'DD/MM/YYYY') AS POURFOURNITUREEPREUVE,
  DOS.MINISTERERESP, TO_CHAR (DOS.DATEPRECISEEPUBLICATION, 'DD/MM/YYYY') AS DATEPRECISEPUB,
  NVL(MP."MODE",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL,
  (case when vp.vpintitule is not null then vp.vpintitule else VEC.ITEM end) AS VECTEURPUBLICATION
FROM DOSSIER_SOLON_EPG DOS, DOS_VECTEURPUBLICATION VEC, 
  RETOUR_DILA RD, MODE_PARUTION MP, VOC_PUBLICATION_DELAI VPD, VECTEUR_PUBLICATION vp
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND RD.MODEPARUTION =  MP."ID"(+)
AND DOS.DELAIPUBLICATION = VPD."id" (+)
AND DOS.ID = VEC.ID(+)
AND RD.ID = DOS.ID
and VEC.ITEM = VP.ID (+)
AND EXISTS ( 	SELECT 1 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
        		AND   ROU.DATEFINETAPE IS NULL
				AND   ROU.TYPE IN (13, 14) );
				
-- Cette vue a été modifiée pour les modes de parution
CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_EPR  AS
SELECT DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION, 
  TO_CHAR (DOS.POURFOURNITUREEPREUVE, 'DD/MM/YYYY') AS POURFOURNITUREEPREUVE,
  DOS.MINISTERERESP, TO_CHAR (DOS.DATEPRECISEEPUBLICATION, 'DD/MM/YYYY') AS DATEPRECISEPUB,
  NVL(MP."MODE",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL,
  (case when vp.vpintitule is not null then vp.vpintitule else VEC.ITEM end) AS VECTEURPUBLICATION
FROM DOSSIER_SOLON_EPG DOS, DOS_VECTEURPUBLICATION VEC, 
  RETOUR_DILA RD, MODE_PARUTION MP, VOC_PUBLICATION_DELAI VPD, VECTEUR_PUBLICATION vp
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND RD.MODEPARUTION =  MP."ID"(+)
AND DOS.DELAIPUBLICATION = VPD."id" (+)
AND DOS.ID = VEC.ID(+)
AND RD.ID = DOS.ID
and VEC.ITEM = VP.ID (+)
AND EXISTS ( 	SELECT 1
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
        AND   ROU.DATEFINETAPE IS NULL
				AND   ROU.TYPE IN (12) );

