package fr.dila.solonmgpp.api.enumeration;

import java.util.stream.Stream;
import org.apache.commons.lang3.StringUtils;

/**
 * Enum du type de corbeille MGPP et si elle est dynamique
 */
public enum MgppCorbeilleName {
    CORBEILLE_GOUVERNEMET_PROC_LEG_RECEPTION(false),
    CORBEILLE_GOUVERNEMET_PROC_LEG_EMIS(false),
    CORBEILLE_GOUVERNEMET_PROC_LEG_ATTENTE(false),
    CORBEILLE_GOUVERNEMENT_CENSURE(false),
    CORBEILLE_GOUVERNEMET_PROC_LEG_HISTORIQUE(false),
    CONSULTATION_FICHE_LOIS_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_PUBLICATION_ATTRIB_PARLEMENTAIRE(true),
    CORBEILLE_GOUVERNEMENT_PUBLICATION_ATTRIB(true),
    CORBEILLE_GOUVERNEMENT_PUBLICATION_FOURN_EPRV(true),
    CORBEILLE_GOUVERNEMENT_PUBLICATION_BON_TIRER(true),
    CORBEILLE_GOUVERNEMENT_PUBLICATION_PUBLI_JO(true),
    CORBEILLE_GOUVERNEMENT_RAPPORT_HISTORIQUE(false),
    CONSULTATION_FICHE_DR_EXISTANT(true),
    CONSULTATION_FICHE_DR_67_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_AUTRES_DOCUMENTS_TRANSMIS_AUX_ASSEMBLEES(false),
    CORBEILLE_GOUVERNEMENT_AUTRES_DOCUMENTS_TRANSMIS_AUX_ASSEMBLEES_HISTORIQUE(false),
    CONSULTATION_FICHE_DOC_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_NOMINATION(false),
    CORBEILLE_GOUVERNEMENT_NOMINATION_HISTORIQUE(false),
    CONSULTATION_AVI_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_OEP(false),
    CORBEILLE_GOUVERNEMENT_OEP_HISTORIQUE(false),
    CONSULTATION_OEP_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_DEMANDE_AUDITION(false),
    CORBEILLE_GOUVERNEMENT_DEMANDE_AUDITION_HISTORIQUE(false),
    CONSULTATION_FICHE_AUD_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_DECRET_HISTORIQUE(false),
    CONSULTATION_FICHE_DECRET_EXISTANT(true),
    CONSULTATION_FICHE_JSS_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_INTERVENTION_EXTERIEURE_HISTORIQUE(false),
    CONSULTATION_FICHE_IE_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_DECLARATION_DE_POLITIQUE_GENERALE_HISTORIQUE(false),
    CONSULTATION_FICHE_DPG_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_DECLARATION_SUR_UN_SUJET_DETERMINE_HISTORIQUE(false),
    CONSULTATION_FICHE_SD_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_RESOLUTION_341(false, "CORBEILLE_GOUVERNEMENT_RESOLUTION_34-1"),
    CORBEILLE_GOUVERNEMENT_INTERVENTION_EXTERIEURE(false),
    CORBEILLE_GOUVERNEMENT_RAPPORT(false),
    CORBEILLE_GOUVERNEMENT_DEMANDE_DE_MISE_EN_OEUVRE_ARTICLE_283C(
        false,
        "CORBEILLE_GOUVERNEMENT_DEMANDE_DE_MISE_EN_OEUVRE_ARTICLE_28-3C"
    ),
    CORBEILLE_GOUVERNEMENT_DEMANDE_DE_MISE_EN_OEUVRE_ARTICLE_283C_HISTORIQUE(
        false,
        "CORBEILLE_GOUVERNEMENT_DEMANDE_DE_MISE_EN_OEUVRE_ARTICLE_28-3C_HISTORIQUE"
    ),
    CORBEILLE_GOUVERNEMENT_DECLARATION_DE_POLITIQUE_GENERALE(false),
    CORBEILLE_GOUVERNEMENT_DECLARATION_SUR_UN_SUJET_DETERMINE_50_1C(false),
    CORBEILLE_GOUVERNEMENT_RESOLUTION_341_HISTORIQUE(false, "CORBEILLE_GOUVERNEMENT_RESOLUTION_34-1_HISTORIQUE"),
    CONSULTATION_FICHE_341_EXISTANT(true),
    CORBEILLE_GOUVERNEMENT_DECRET(false);

    private final boolean dynamic;
    private final String name;

    MgppCorbeilleName(boolean dynamic) {
        this(dynamic, "");
    }

    MgppCorbeilleName(boolean dynamic, String name) {
        this.dynamic = dynamic;
        this.name = name;
    }

    public String getIdCorbeille() {
        return StringUtils.isBlank(this.name) ? name() : this.name;
    }

    public static MgppCorbeilleName fromValue(String idCorbeille) {
        return Stream
            .of(values())
            .filter(corbeille -> corbeille.getIdCorbeille().equals(idCorbeille))
            .findFirst()
            .orElse(null);
    }

    public boolean isDynamic() {
        return dynamic;
    }
}
