ALTER TABLE "FICHE_PRESENTATION_OEP" DROP COLUMN "BASELEGALE";
ALTER TABLE "FICHE_PRESENTATION_DR" DROP COLUMN "DESTINATAIRE1RAPPORT";
ALTER TABLE "FULLTEXT" DROP
	(
		"FULLTEXT_NOR",
        "SIMPLETEXT_NOR",
        "BINARYTEXT_NOR"
	);
commit;
