-- Ajour d'index sur la table Feuille de route --

CREATE INDEX "IDX_FEUILLE_ROUTE_DIR" ON "FEUILLE_ROUTE" ("DIRECTION");
CREATE INDEX "IDX_FEUILLE_ROUTE_DEFAULT" ON "FEUILLE_ROUTE" ("FEUILLEROUTEDEFAUT");

-- Ajour d'index sur la table de l'activite normative --

CREATE INDEX "IDX_TEXM_NUMERO" ON "TEXTE_MAITRE" ("NUMERO");
CREATE INDEX "IDX_TEXM_NOR" ON "TEXTE_MAITRE" ("NUMERONOR");
CREATE INDEX "IDX_TEXM_NUMORDRE" ON "TEXTE_MAITRE" ("NUMEROORDRE");
CREATE INDEX "IDX_TEXM_IDDOS" ON "TEXTE_MAITRE" ("IDDOSSIER");
CREATE INDEX "IDX_TEXM_ARTICLE" ON "TEXTE_MAITRE" ("ARTICLE");


 
