CREATE OR REPLACE VIEW V_BORDEREAU_AUTRE_LISTE  AS
SELECT DOS.MINISTERERESP, DOS.NUMERONOR, 
       DOS.TITREACTE, 
       TP.PUBLICATIONEPREUVEENRETOUR,
       TP.PUBLICATIONDELAI,
       TP.PUBLICATIONDATEDEMANDE,
       LISTE.TYPELISTE, LISTE.NUMEROLISTE, 
       LISTE.ID,
       TP.ID as DOCID,
       LISTE.DATEGENERATIONLISTE, 
       LISTE.TYPESIGNATURE,
       NVL(VOCPUBTP."label",' ') AS PUBTPLABEL, 
       NVL(VOCMODEPARU."label",'') AS MODPARULABEL,
       NVL(VOCPUBDEL."label",' ') AS PUBDELAILABEL,
       NVL(VOCVEC."label",'') AS VECTEURPUBLICATION
  FROM DOSSIER_SOLON_EPG DOS,
       TRAITEMENT_PAPIER TP,
       LIS_IDSDOSSIER LISDOS,
       LISTE_TRAITEMENT_PAPI_144E75F6 LISTE,
       VOC_VECTEUR_PUBLICATION_TP VOCPUBTP,
       VOC_MODE_PARUTION VOCMODEPARU,
       VOC_PUBLICATION_DELAI VOCPUBDEL,
       VOC_VECTEUR_PUBLICATION_TP VOCVEC
 WHERE DOS.ID = TP.ID
   AND DOS.ID = LISDOS.ITEM
   AND LISDOS.ID = LISTE.ID
   AND (LISTE.TYPELISTE = '2' OR LISTE.TYPELISTE = '3')
   AND TP.PUBLICATIONNOMPUBLICATION = VOCPUBTP."id"(+)
   AND TP.PUBLICATIONMODEPUBLICATION = VOCMODEPARU."id"(+)
   AND TP.PUBLICATIONDELAI = VOCPUBDEL."id"(+)
   AND TP.PUBLICATIONNOMPUBLICATION = VOCVEC."id"(+);

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_SIG_PM_PR  AS
SELECT DISTINCT DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, 
  NVL(V."label", '') TYPEACTELABEL, MAX(SIG.DATEENVOISIGNATURE)AS DATESIGNATURE
FROM DOSSIER_SOLON_EPG DOS, HIERARCHY H, DONNEESSIGNATAIRE SIG, VOC_ACTE_TYPE V
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND DOS.TYPEACTE = V."id" (+)
AND H.NAME IN ('tp:signaturePm', 'tp:signaturePr')
AND H.PARENTID = DOS.ID
AND H.ID = SIG.ID
AND SIG.DATEENVOISIGNATURE IS NOT NULL
AND SIG.DATERETOURSIGNATURE IS NULL 
GROUP BY DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, NVL(V."label", '');

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_AMPLIATION  AS
SELECT  DOS.ID, 
		DOS.NUMERONOR, 
		DOS.TITREACTE, 
		LISTAGG (AMP.ITEM, ', ') WITHIN GROUP (ORDER BY AMP.ITEM) ITEM,
    (
      SELECT MAX(I.DATEENVOIAMPLIATION) AS DATEENVOIE FROM INFOHISTORIQUEAMPLIATION I, HIERARCHY H 
      WHERE H.PARENTID = DOS.ID AND H.NAME = 'tp:ampliationHistorique'
      AND I.ID = H.ID GROUP BY H.PARENTID
    )AS DATEENVOIE
FROM (DOSSIER_SOLON_EPG DOS INNER JOIN TP_AMPLIATIONDESTINATAIREMAILS AMP ON DOS.ID = AMP.ID AND   DOS.STATUTARCHIVAGE IN ('1', '2'))
GROUP BY DOS.ID, DOS.NUMERONOR, DOS.TITREACTE
order by DATEENVOIE desc;

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_PUB  AS
SELECT '0' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION, DOS.MINISTERERESP,
  NVL(VMP."label",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, RETOUR_DILA RD, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND RD.MODEPARUTION =  VMP."id"(+)
AND DOS.DELAIPUBLICATION = VPD."id" (+)
AND RD.ID = DOS.ID
AND EXISTS ( 	SELECT * 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
				AND   ROU.TYPE IN (13, 14) )
UNION
SELECT '1' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, TP.PUBLICATIONDELAI DELAIPUBLICATION, 
  TP.PUBLICATIONMODEPUBLICATION MODEPARUTION, DOS.MINISTERERESP,
  NVL(VMP."label",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
AND TP.PUBLICATIONMODEPUBLICATION = VMP."id" (+)
AND TP.PUBLICATIONDELAI = VPD."id" (+)
AND DOS.ID = TP.ID;