CREATE OR REPLACE VIEW V_AN_MESURES_LEGISLATIVE  AS
SELECT
TM_LOI.MOTCLE,
TM_LOI.NUMERO AS NUMEROLOI,
TM_LOI.TITREOFFICIEL,
TM_LOI.NATURETEXTE AS NATURETEXTE, 
TM_LOI.PROCEDUREVOTE AS PROCEDUREVOTE, 
TO_CHAR(TM_LOI.DATEPUBLICATION , 'DD/MM/YYYY') DATEPUBLICATION,
TM_LOI.LEGISLATUREPUBLICATION,
TM_MES.NUMEROORDRE,
TM_MES.ARTICLE,
TM_MES.CODEMODIFIE,
TM_MES.BASELEGALE,
TM_MES.OBJETRIM,
TM_MES.MINISTEREPILOTE,
TM_MES.DIRECTIONRESPONSABLE,
TM_MES.CONSULTATIONSHCE,
TM_MES.CALENDRIERCONSULTATIONSHCE,
TM_MES.DATEPREVISIONNELLESAISINECE,
TM_MES.DATEENTREEENVIGUEUR,
TM_MES.DATEOBJECTIFPUBLICATION DATEOBJECTIFPUBLICATION,
TM_MES.TYPEMESURE           AS TYPEMESUREID,
NVL(VOC_TM_MES."label", '') AS TYPEMESURE,
TM_MES.OBSERVATION,
TM_DEC.NUMERONOR,
TM_DEC.TITREOFFICIEL DECRET_TITREOFFICIEL,
NVL(VOC_TM_DEC."label",' ') AS TYPACTE,
TO_CHAR(TM_DEC.DATESAISINECE, 'DD/MM/YYYY') DATESAISINECE,
TO_CHAR(TM_DEC.DATESORTIECE, 'DD/MM/YYYY') DATESORTIECE,
TO_CHAR(TM_DEC.DATEPUBLICATION, 'DD/MM/YYYY') DECRET_DATEPUBLICATION,
TO_CHAR(TM_MES.DATEMISEAPPLICATION, 'DD/MM/YYYY') DATEMISEAPPLICATION,
TM_MES.DATEENTREEENVIGUEUR as MES_DATEENTREEENVIGUEUR,
TM_MES.APPLICATIONRECU,
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION,
TM_MES.DIFFERE as MES_DIFFERE
FROM TEXTE_MAITRE TM_LOI, TEXM_MESUREIDS TME, ACTIVITE_NORMATIVE AN, TEXTE_MAITRE TM_MES 
LEFT JOIN VOC_TYPE_MESURE VOC_TM_MES ON TM_MES.TYPEMESURE = VOC_TM_MES."id"
LEFT JOIN TEXM_DECRETIDS TD ON TD.ID = TM_MES.ID
LEFT JOIN TEXTE_MAITRE TM_DEC ON TM_DEC.ID = TD.ITEM
LEFT JOIN VOC_ACTE_TYPE VOC_TM_DEC ON TM_DEC.TYPEACTE = VOC_TM_DEC."id"
WHERE TM_LOI.ID = AN.ID
AND AN.APPLICATIONLOI = '1'
AND TM_MES.TYPEMESURE IN ('1','4' ,'6')
AND TME.ID = AN.ID
AND TM_MES.ID = TME.ITEM
ORDER BY NUMEROLOI, TO_NUMBER(TM_MES.NUMEROORDRE);
commit;
