ALTER TABLE navette
ADD(  
  "DATENAVETTE" TIMESTAMP(6)
  );

UPDATE navette set "DATENAVETTE" = "DATETRANSMISSION", "DATETRANSMISSION"=null;

ALTER TABLE FICHE_LOI
ADD(  
  "DATEPROCEDUREACCELEREE" TIMESTAMP(6)
  );
ALTER TABLE FICHE_LOI
DROP COLUMN "PROCEDUREACCELEREE";
  
commit;

