CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_PUB  AS
SELECT '0' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION,
  NVL(VMP."label",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, RETOUR_DILA RD, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND RD.MODEPARUTION =  VMP."id"(+)
AND DOS.DELAIPUBLICATION = VPD."id" (+)
AND RD.ID = DOS.ID
AND EXISTS ( 	SELECT * 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
				AND   ROU.TYPE IN (13, 14) )
UNION
SELECT '1' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, TP.PUBLICATIONDELAI DELAIPUBLICATION, TP.PUBLICATIONMODEPUBLICATION MODEPARUTION,
  NVL(VMP."label",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
AND TP.PUBLICATIONMODEPUBLICATION = VMP."id" (+)
AND TP.PUBLICATIONDELAI = VPD."id" (+)
AND DOS.ID = TP.ID;

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_RIG  AS
SELECT DISTINCT DOS.*
FROM DOSSIER_SOLON_EPG DOS,
     TRAITEMENT_PAPIER TP
WHERE DOS.ID = TP.ID
AND   DOS.STATUTARCHIVAGE IN ('1', '2')
AND( 
	EXISTS
	(
		SELECT *
		FROM ACTIONNABLE_CASE_LINK ACT, CASE_LINK CAS, ROUTING_TASK ROU
		WHERE DOS.ID = CAS.CASEDOCUMENTID
		AND   CAS.ID = ACT.ID
		AND   ACT.ROUTINGTASKID = ROU.ID
		AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
		AND   ROU.TYPE = 13
		AND   DOS.DELAIPUBLICATION = 3
	)
	 OR
	(
		TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY') 
		AND   TP.PUBLICATIONDELAI = 3
	)
);