delete from VOC_ACTE_TYPE;
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('1','0',0,'0','0',10000000,'Amnistie');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('2','0',0,'0','0',10000000,'Arrêté ministériel');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('36','0',0,'0','0',10000000,'Arrêté ministériel (individuel)');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('3','0',0,'0','0',10000000,'Arrêté interministériel');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('37','0',0,'0','0',10000000,'Arrêté interministériel (individuel)');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('4','0',0,'1','0',10000000,'Arrêté du Premier ministre');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('38','0',0,'1','0',10000000,'Arrêté du Premier ministre (individuel)');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('5','0',0,'0','0',10000000,'Arrêté du Président de la République');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('39','0',0,'0','0',10000000,'Arrêté du Président de la République (individuel)');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('46','0',0,'0','0',10000000,'Arrêté en Conseil d''Etat');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('6','0',0,'0','0',10000000,'Avenant');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('7','0',0,'0','0',10000000,'Avis');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('8','0',0,'0','0',10000000,'Circulaire');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('9','0',0,'0','0',10000000,'Citation');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('10','0',0,'0','0',10000000,'Communiqué');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('11','0',0,'0','0',10000000,'Convention');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('12','0',0,'0','0',10000000,'Décision');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('13','0',0,'1','1',10000000,'Décret en Conseil d''Etat de l''article 37 second alinéa de la Constitution');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('14','0',0,'1','1',10000000,'Décret en Conseil d''Etat');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('40','0',0,'1','1',10000000,'Décret en Conseil d''Etat (individuel)');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('15','0',0,'1','1',10000000,'Décret en Conseil d''Etat et conseil des ministres');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('41','0',0,'1','1',10000000,'Décret en Conseil d''Etat et conseil des ministres (individuel)');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('16','0',0,'1','1',10000000,'Décret en conseil des ministres');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('42','0',0,'1','1',10000000,'Décret en conseil des ministres (individuel)');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('17','0',0,'1','1',10000000,'Décret du Président de la République');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('43','0',0,'1','1',10000000,'Décret du Président de la République (individuel)');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('18','0',0,'1','1',10000000,'Décret simple');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('44','0',0,'1','1',10000000,'Décret simple (individuel)');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('19','0',0,'1','1',10000000,'Décret de publication de traité ou accord');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('47','0',0,'1','1',10000000,'Décret du Président de la République en Conseil d''Etat');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('20','0',0,'0','0',10000000,'Délibération');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('21','0',0,'0','0',10000000,'Demande d''avis au Conseil d''Etat');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('22','0',0,'0','0',10000000,'Divers');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('23','0',0,'0','0',10000000,'Exequatur');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('24','0',0,'0','0',10000000,'Instruction');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('25','0',0,'0','0',10000000,'Liste');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('26','1',0,'1','0',10000000,'Loi');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('27','1',0,'1','0',10000000,'Loi de l''article 53 de la Constitution');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('28','1',0,'1','0',10000000,'Loi constitutionnelle');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('29','1',0,'1','0',10000000,'Loi organique');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('30','0',0,'0','0',10000000,'Note');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('31','2',0,'1','0',10000000,'Ordonnance');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('32','0',0,'0','0',10000000,'Rapport');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('33','0',0,'0','0',10000000,'Rectificatif');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('34','0',0,'0','0',10000000,'Tableau');
insert into VOC_ACTE_TYPE ("id","activiteNormative","obsolete","classification","isDecret","ordering","label") values ('45','0',0,'0','0',10000000,'Rapport au parlement');
commit;