-- Ajout de la liste des detinataire 1 d'une fiche depot de rapport
  
CREATE TABLE "FPDR_DESTINATAIRE1RAPPORT" 
(	
	"ID" VARCHAR2(36 BYTE), 
	"POS" NUMBER(10,0), 
	"ITEM" NVARCHAR2(2000),
	CONSTRAINT "FPDR_750A2700_FK" FOREIGN KEY ("ID") REFERENCES "HIERARCHY" ("ID") ON
	DELETE CASCADE ENABLE
) ;