--== HIERARCHY ==--

spool complement.log

create unique index IDX_HIER_1 ON HIERARCHY(PRIMARYTYPE, ID);
create index IDX_HIER_2 ON HIERARCHY(PARENTID, ISPROPERTY);
create unique index IDX_HIER_3 ON HIERARCHY(PARENTID, PRIMARYTYPE, ID);
create unique index IDX_HIER_4 ON HIERARCHY(ID, PRIMARYTYPE);
create unique index IDX_HIER_5 ON HIERARCHY(ID, MIXINTYPES);
create unique index IDX_HIER_6 ON HIERARCHY(ID, ISVERSION);

create index DOSSIER_ARCHIVAGE ON DOSSIER_SOLON_EPG(STATUTARCHIVAGE);


--== MISC ==--
create unique index IDX_MISC_1 ON MISC(ID, LIFECYCLESTATE);
create unique index IDX_MISC_2 ON MISC(LIFECYCLESTATE, ID);

--== ACLS ==--
create unique index IDX_ACLS_1 ON ACLS ("ID","POS","PERMISSION","USER","GRANT","NAME","GROUP");

--== FULLTEXT ==--
create unique index IDX_FULLTEXT_1 on FULLTEXT(jobid, id);


--== INDEXATION_MOT_CLE_SOLON_EPG ==--
CREATE INDEX IDX_INDEX_MOT_CLE_1 ON INDEXATION_MOT_CLE_SOLON_EPG(ID, INTITULE);

--== MOTS_CLES ==--
CREATE INDEX IDX_MOT_CLE_1 ON MOTS_CLES(ID, ITEM);

--== DOSSIER_SOLON_EPG ==--
CREATE UNIQUE INDEX IDX_DOSSIER_SOLON_EPG_1 ON DOSSIER_SOLON_EPG(NUMERONOR);

--== Début DUBLINCORE ==--
ALTER TABLE DUBLINCORE RENAME COLUMN CREATOR TO CREATOR_OLD;
ALTER TABLE DUBLINCORE RENAME COLUMN LASTCONTRIBUTOR TO LASTCONTRIBUTOR_OLD;
ALTER TABLE DUBLINCORE RENAME COLUMN DESCRIPTION TO DESCRIPTION_OLD;
ALTER TABLE DUBLINCORE RENAME COLUMN TITLE TO TITLE_OLD;

ALTER TABLE DUBLINCORE
ADD
   (
   CREATOR NVARCHAR2(50),
   LASTCONTRIBUTOR NVARCHAR2(50),
   DESCRIPTION NVARCHAR2(500),
   TITLE NVARCHAR2(500)
   );

UPDATE DUBLINCORE
SET CREATOR = CREATOR_OLD,
    LASTCONTRIBUTOR = LASTCONTRIBUTOR_OLD,
	DESCRIPTION = DESCRIPTION_OLD,
	TITLE = TITLE_OLD;
COMMIT;

ALTER TABLE DUBLINCORE DROP (CREATOR_OLD, LASTCONTRIBUTOR_OLD, TITLE_OLD, DESCRIPTION_OLD);

CREATE INDEX IDX_DUBLINCORE_1 ON DUBLINCORE(ID, TITLE);
CREATE INDEX IDX_DUBLINCORE_2 ON DUBLINCORE(ID, CREATOR);
--== Fin DUBLINCORE ==--


--== Début BULLETIN_OFFICIEL ==--
ALTER TABLE BULLETIN_OFFICIEL RENAME COLUMN BONOR TO BONOR_OLD;
ALTER TABLE BULLETIN_OFFICIEL RENAME COLUMN BOETAT TO BOETAT_OLD;

ALTER TABLE BULLETIN_OFFICIEL
ADD
   (
   BONOR NVARCHAR2(5),
   BOETAT NVARCHAR2(15)
   );

UPDATE BULLETIN_OFFICIEL
SET BONOR = BONOR_OLD,
    BOETAT = BOETAT_OLD;
COMMIT;

ALTER TABLE BULLETIN_OFFICIEL DROP (BONOR_OLD, BOETAT_OLD);

CREATE UNIQUE INDEX IDX_BO_1 on BULLETIN_OFFICIEL(ID, BONOR);
CREATE UNIQUE INDEX IDX_BO_2 on BULLETIN_OFFICIEL(ID, BOETAT);
--== Fin BULLETIN_OFFICIEL ==--


--== Début CMDIST_INITIAL_ACTION_4CD43708 ==--
ALTER TABLE CMDIST_INITIAL_ACTION_4CD43708 RENAME COLUMN ITEM TO ITEM_OLD;

ALTER TABLE CMDIST_INITIAL_ACTION_4CD43708
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE CMDIST_INITIAL_ACTION_4CD43708
SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE CMDIST_INITIAL_ACTION_4CD43708 DROP (ITEM_OLD);

CREATE UNIQUE INDEX IDX_CMDISTINITACTION_1 on CMDIST_INITIAL_ACTION_4CD43708(ID, ITEM);
--== Fin CMDIST_INITIAL_ACTION_4CD43708 ==--


--== Début CMDIST_ALL_ACTION_PAR_6B4BBED8 ==--
ALTER TABLE CMDIST_ALL_ACTION_PAR_6B4BBED8 RENAME COLUMN ITEM TO ITEM_OLD;

ALTER TABLE CMDIST_ALL_ACTION_PAR_6B4BBED8
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE CMDIST_ALL_ACTION_PAR_6B4BBED8
SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE CMDIST_ALL_ACTION_PAR_6B4BBED8 DROP (ITEM_OLD);

CREATE UNIQUE INDEX IDX_CMDISTALLACTION_1 on CMDIST_ALL_ACTION_PAR_6B4BBED8(ID, ITEM);
--== Fin CMDIST_ALL_ACTION_PAR_6B4BBED8 ==--


/* Ces deux tables vont être remplacées par des tables de type "DOS_NOMCOMPLETCHARGESMISSIONS"
--== Début DOS_CHARGEMISSIONIDS ==--
ALTER TABLE DOS_CHARGEMISSIONIDS RENAME COLUMN ITEM TO ITEM_OLD;

ALTER TABLE DOS_CHARGEMISSIONIDS
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE DOS_CHARGEMISSIONIDS
SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE DOS_CHARGEMISSIONIDS DROP (ITEM_OLD);

CREATE UNIQUE INDEX IDX_CHARGEMISSION_1 on DOS_CHARGEMISSIONIDS(ID, ITEM);
--== Fin DOS_CHARGEMISSIONIDS ==--


--== Début DOS_CONSEILLERPMIDS ==--
ALTER TABLE DOS_CONSEILLERPMIDS RENAME COLUMN ITEM TO ITEM_OLD;

ALTER TABLE DOS_CONSEILLERPMIDS
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE DOS_CONSEILLERPMIDS
SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE DOS_CONSEILLERPMIDS DROP (ITEM_OLD);

CREATE UNIQUE INDEX IDX_CONSEILLERPM_1 on DOS_CONSEILLERPMIDS(ID, ITEM);
--== Fin DOS_CONSEILLERPMIDS ==--
*/

--== Début DOS_PUBLICATIONSCONJOINTES ==--
ALTER TABLE DOS_PUBLICATIONSCONJOINTES RENAME COLUMN ITEM TO ITEM_OLD;

ALTER TABLE DOS_PUBLICATIONSCONJOINTES
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE DOS_PUBLICATIONSCONJOINTES
SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE DOS_PUBLICATIONSCONJOINTES DROP (ITEM_OLD);

CREATE UNIQUE INDEX IDX_PUBLICCONJ_1 on DOS_PUBLICATIONSCONJOINTES(ID, ITEM);
--== Fin DOS_PUBLICATIONSCONJOINTES ==--


--== Début DOS_VECTEURPUBLICATION ==--
ALTER TABLE DOS_VECTEURPUBLICATION RENAME COLUMN ITEM TO ITEM_OLD;

ALTER TABLE DOS_VECTEURPUBLICATION
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE DOS_VECTEURPUBLICATION
SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE DOS_VECTEURPUBLICATION DROP (ITEM_OLD);

CREATE UNIQUE INDEX IDX_VECTEURPUBLIC_1 on DOS_VECTEURPUBLICATION(ID, ITEM);
--== Fin DOS_VECTEURPUBLICATION ==--


--== Début FDD_FORMATAUTORISE ==--
ALTER TABLE FDD_FORMATAUTORISE RENAME COLUMN ITEM TO ITEM_OLD;

ALTER TABLE FDD_FORMATAUTORISE
ADD
   (
   ITEM NVARCHAR2(10)
   );

UPDATE FDD_FORMATAUTORISE
SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE FDD_FORMATAUTORISE DROP (ITEM_OLD);

CREATE UNIQUE INDEX IDX_FDD_FORMAT_1 on FDD_FORMATAUTORISE(ID, POS, ITEM);
--== Fin FDD_FORMATAUTORISE ==--


--== Début PF_FORMATAUTORISE ==--
ALTER TABLE PF_FORMATAUTORISE RENAME COLUMN ITEM TO ITEM_OLD;

ALTER TABLE PF_FORMATAUTORISE
ADD
   (
   ITEM NVARCHAR2(10)
   );

UPDATE PF_FORMATAUTORISE
SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE PF_FORMATAUTORISE DROP (ITEM_OLD);

CREATE UNIQUE INDEX IDX_PF_FORMAT_1 on PF_FORMATAUTORISE(ID, POS, ITEM);
--== Fin PF_FORMATAUTORISE ==--


--== Début MAILBOX ==--
ALTER TABLE MAILBOX RENAME COLUMN MAILBOX_ID TO MAILBOX_ID_OLD;

ALTER TABLE MAILBOX
ADD
   (
   MAILBOX_ID NVARCHAR2(100)
   );

UPDATE MAILBOX
SET MAILBOX_ID = MAILBOX_ID_OLD;
COMMIT;

ALTER TABLE MAILBOX DROP (MAILBOX_ID_OLD);
CREATE UNIQUE INDEX IDX_MAILBOX_1 on MAILBOX(MAILBOX_ID, ID);
--== Fin MAILBOX ==--


--== Début MLBX_GROUPS ==--
ALTER TABLE MLBX_GROUPS RENAME COLUMN ITEM TO ITEM_OLD;

ALTER TABLE MLBX_GROUPS
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE MLBX_GROUPS
SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE MLBX_GROUPS DROP (ITEM_OLD);
CREATE UNIQUE INDEX IDX_MLBX_GROUPS_1 on MLBX_GROUPS(ID, ITEM);
--== Fin MLBX_GROUPS ==--


--== Début DOCRI_PARTICIPATINGDOCUMENTS ==--
ALTER TABLE DOCRI_PARTICIPATINGDOCUMENTS RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE DOCRI_PARTICIPATINGDOCUMENTS
ADD
   (
   ITEM VARCHAR2(50)
   );

UPDATE DOCRI_PARTICIPATINGDOCUMENTS SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE DOCRI_PARTICIPATINGDOCUMENTS DROP (ITEM_OLD);

create unique index IDX_DOCRIPARTDOC_1 ON DOCRI_PARTICIPATINGDOCUMENTS(ID, ITEM);
--== Fin DOCRI_PARTICIPATINGDOCUMENTS ==--


--== Début DC_CONTRIBUTORS ==--
ALTER TABLE DC_CONTRIBUTORS RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE DC_CONTRIBUTORS
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE DC_CONTRIBUTORS SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE DC_CONTRIBUTORS DROP (ITEM_OLD);

create unique index IDX_DCCONTRIB_1 on DC_CONTRIBUTORS(ID, POS, ITEM);
--== Fin DC_CONTRIBUTORS ==--

--== DC_SUBJECTS ==--
create unique index IDX_DCSUBJECT_1 on DC_SUBJECTS(ID, POS, ITEM);


--== Début CASE_LINK ==--
ALTER TABLE CASE_LINK RENAME COLUMN CASEDOCUMENTID TO CASEDOCUMENTID_OLD;

ALTER TABLE CASE_LINK
ADD
   (
   CASEDOCUMENTID VARCHAR2(50)
   );

UPDATE CASE_LINK
SET CASEDOCUMENTID = CASEDOCUMENTID_OLD;
COMMIT;

ALTER TABLE CASE_LINK DROP (CASEDOCUMENTID_OLD);

create unique index IDX_CASE_LINK_1 ON CASE_LINK(ID, "DATE");
CREATE unique INDEX IDX_CASE_LINK_2 on CASE_LINK(CASEDOCUMENTID, ID);

--== Début MODELE_FOND_DOSSIER_SOLON_EPG ==--
ALTER TABLE MODELE_FOND_DOSSIER_SOLON_EPG RENAME COLUMN TYPEACTE TO TYPEACTE_OLD;

ALTER TABLE MODELE_FOND_DOSSIER_SOLON_EPG
ADD
   (
   TYPEACTE NVARCHAR2(10)
   );

UPDATE MODELE_FOND_DOSSIER_SOLON_EPG
SET TYPEACTE = TYPEACTE_OLD;
COMMIT;

ALTER TABLE MODELE_FOND_DOSSIER_SOLON_EPG DROP (TYPEACTE_OLD);

CREATE unique INDEX IDX_MODEL_FDD_1 ON MODELE_FOND_DOSSIER_SOLON_EPG(TYPEACTE, ID);
--== Fin MODELE_FOND_DOSSIER_SOLON_EPG ==--


--== Début MODELE_PARAPHEUR_SOLON_EPG ==--
ALTER TABLE MODELE_PARAPHEUR_SOLON_EPG RENAME COLUMN TYPEACTE TO TYPEACTE_OLD;

ALTER TABLE MODELE_PARAPHEUR_SOLON_EPG
ADD
   (
   TYPEACTE NVARCHAR2(10)
   );

UPDATE MODELE_PARAPHEUR_SOLON_EPG
SET TYPEACTE = TYPEACTE_OLD;
COMMIT;

ALTER TABLE MODELE_PARAPHEUR_SOLON_EPG DROP (TYPEACTE_OLD);

CREATE unique INDEX IDX_MODEL_PARAPH_1 ON MODELE_PARAPHEUR_SOLON_EPG(TYPEACTE, ID);
--== Fin MODELE_PARAPHEUR_SOLON_EPG ==--


--== Début TABLE COMMENT ==--
ALTER TABLE "COMMENT" RENAME COLUMN COMMENTEDDOCID TO COMMENTEDDOCID_OLD;

ALTER TABLE "COMMENT"
ADD
   (
   COMMENTEDDOCID VARCHAR2(50)
   );

UPDATE "COMMENT"
SET COMMENTEDDOCID = COMMENTEDDOCID_OLD;
COMMIT;

ALTER TABLE "COMMENT" DROP (COMMENTEDDOCID_OLD);

CREATE unique INDEX IDX_COMMENT_1 ON "COMMENT"(COMMENTEDDOCID, ID);
-- Peut etre rajouter des index pour VISIBLETOMINISTEREID, VISIBLETOPOSTEID et VISIBLETOUNITESTRUCTURELLEID
--== Fin TABLE COMMENT ==--


--== Début LISTE_TRAITEMENT_PAPI_144E75F6 ==--
ALTER TABLE LISTE_TRAITEMENT_PAPI_144E75F6 RENAME COLUMN TYPELISTE TO TYPELISTE_OLD;
ALTER TABLE LISTE_TRAITEMENT_PAPI_144E75F6 RENAME COLUMN TYPESIGNATURE TO TYPESIGNATURE_OLD;

ALTER TABLE LISTE_TRAITEMENT_PAPI_144E75F6
ADD
   (
   TYPELISTE NVARCHAR2(2),
   TYPESIGNATURE NVARCHAR2(5)
   );

UPDATE LISTE_TRAITEMENT_PAPI_144E75F6
SET TYPELISTE = TYPELISTE_OLD,
    TYPESIGNATURE = TYPESIGNATURE_OLD;
COMMIT;

ALTER TABLE LISTE_TRAITEMENT_PAPI_144E75F6 DROP (TYPELISTE_OLD, TYPESIGNATURE_OLD);

CREATE unique INDEX IDX_LIST_TRAIT_PAP_1 ON LISTE_TRAITEMENT_PAPI_144E75F6(DATEGENERATIONLISTE, ID);
CREATE unique INDEX IDX_LIST_TRAIT_PAP_2 ON LISTE_TRAITEMENT_PAPI_144E75F6(TYPELISTE, ID);
--== Fin LISTE_TRAITEMENT_PAPI_144E75F6 ==--


--== Début TABLE ROUTING_TASK ==--
ALTER TABLE "ROUTING_TASK" RENAME COLUMN DOCUMENTROUTEID TO DOCUMENTROUTEID_OLD;

ALTER TABLE "ROUTING_TASK"
ADD
   (
   DOCUMENTROUTEID VARCHAR2(50)
   );

UPDATE "ROUTING_TASK"
SET DOCUMENTROUTEID = DOCUMENTROUTEID_OLD;
COMMIT;

ALTER TABLE "ROUTING_TASK" DROP (DOCUMENTROUTEID_OLD);

create unique index IDX_RTASK_1 ON "ROUTING_TASK"(ID, DATEFINETAPE);
create unique index IDX_RTASK_2 ON "ROUTING_TASK"(ID, DISTRIBUTIONMAILBOXID);
create index IDX_RTASK_3 ON "ROUTING_TASK"(DATEFINETAPE);
create index IDX_RTASK_4 ON "ROUTING_TASK"(DISTRIBUTIONMAILBOXID);
create index IDX_RTASK_5 ON "ROUTING_TASK"(DOCUMENTROUTEID);
create index IDX_RTASK_6 ON "ROUTING_TASK"(TYPE);
--== Fin TABLE ROUTING_TASK ==--


--== Début TABLE FEUILLE_ROUTE ==--
ALTER TABLE FEUILLE_ROUTE RENAME COLUMN MINISTERE TO MINISTERE_OLD;
ALTER TABLE FEUILLE_ROUTE RENAME COLUMN TYPECREATION TO TYPECREATION_OLD;
ALTER TABLE FEUILLE_ROUTE RENAME COLUMN TYPEACTE TO TYPEACTE_OLD;
ALTER TABLE FEUILLE_ROUTE RENAME COLUMN DIRECTION TO DIRECTION_OLD;
ALTER TABLE FEUILLE_ROUTE RENAME COLUMN NUMERO TO NUMERO_OLD;

ALTER TABLE FEUILLE_ROUTE
ADD
   (
   MINISTERE NVARCHAR2(50),
   TYPECREATION NVARCHAR2(50),
   TYPEACTE NVARCHAR2(50),
   DIRECTION NVARCHAR2(50),
   NUMERO NVARCHAR2(10)
   );

UPDATE FEUILLE_ROUTE
SET MINISTERE = MINISTERE_OLD,
    TYPECREATION = TYPECREATION_OLD,
	TYPEACTE = TYPEACTE_OLD,
	DIRECTION = DIRECTION_OLD,
	NUMERO = NUMERO_OLD;
COMMIT;

ALTER TABLE FEUILLE_ROUTE DROP (MINISTERE_OLD, TYPECREATION_OLD, TYPEACTE_OLD, DIRECTION_OLD, NUMERO_OLD);

create index IDX_FEUILLE_ROUTE_1 on FEUILLE_ROUTE(MINISTERE);
create index IDX_FEUILLE_ROUTE_2 on FEUILLE_ROUTE(TYPEACTE);
--== Fin TABLE FEUILLE_ROUTE ==--

------====== Début GESTION DES DERNIERS RESULTATS CONSULTES ======------
--== Début RESCON_DOSSIERSIDS ==--
ALTER TABLE RESCON_DOSSIERSIDS RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE RESCON_DOSSIERSIDS
ADD
   (
   ITEM VARCHAR2(50)
   );

UPDATE RESCON_DOSSIERSIDS SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE RESCON_DOSSIERSIDS DROP (ITEM_OLD);

create unique index IDX_RESCON_DOS_1 on RESCON_DOSSIERSIDS(ID, ITEM);
--== Fin RESCON_DOSSIERSIDS ==--

--== Début RESCON_FDRSIDS ==--
ALTER TABLE RESCON_FDRSIDS RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE RESCON_FDRSIDS
ADD
   (
   ITEM VARCHAR2(50)
   );

UPDATE RESCON_FDRSIDS SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE RESCON_FDRSIDS DROP (ITEM_OLD);

create unique index IDX_RESCON_MFDR_1 on RESCON_FDRSIDS(ID, ITEM);
--== Fin RESCON_FDRSIDS ==--

--== Début RESCON_USERSNAMES ==--
ALTER TABLE RESCON_USERSNAMES RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE RESCON_USERSNAMES
ADD
   (
   ITEM VARCHAR2(100)
   );

UPDATE RESCON_USERSNAMES SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE RESCON_USERSNAMES DROP (ITEM_OLD);

create unique index IDX_RESCON_USER_1 on RESCON_USERSNAMES(ID, ITEM);
--== Fin RESCON_USERSNAMES ==--
------====== Fin GESTION DES DERNIERS RESULTATS CONSULTES ======------


------====== Début GESTION DES FAVORIS ======------
--== Début FAVCON_DOSSIERSIDS ==--
ALTER TABLE FAVCON_DOSSIERSIDS RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE FAVCON_DOSSIERSIDS
ADD
   (
   ITEM VARCHAR2(50)
   );

UPDATE FAVCON_DOSSIERSIDS SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE FAVCON_DOSSIERSIDS DROP (ITEM_OLD);

create unique index IDX_FAVCON_DOS_1 on FAVCON_DOSSIERSIDS(ID, ITEM);
--== Fin FAVCON_DOSSIERSIDS ==--

--== Début FAVCON_FDRSIDS ==--
ALTER TABLE FAVCON_FDRSIDS RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE FAVCON_FDRSIDS
ADD
   (
   ITEM VARCHAR2(50)
   );

UPDATE FAVCON_FDRSIDS SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE FAVCON_FDRSIDS DROP (ITEM_OLD);

create unique index IDX_FAVCON_MFDR_1 on FAVCON_FDRSIDS(ID, ITEM);
--== Fin FAVCON_FDRSIDS ==--

--== Début FAVCON_USERSNAMES ==--
ALTER TABLE FAVCON_USERSNAMES RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE FAVCON_USERSNAMES
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE FAVCON_USERSNAMES SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE FAVCON_USERSNAMES DROP (ITEM_OLD);

create unique index IDX_FAVCON_USER_1 on FAVCON_USERSNAMES(ID, ITEM);
--== Fin FAVCON_USERSNAMES ==--
------====== Fin GESTION DES FAVORIS ======------

------====== Début GESTION DES PREFERENCES UTILISATEUR ======------
--== Début PUSR_IDCOLONNEESPACET_934A8665 ==--
ALTER TABLE PUSR_IDCOLONNEESPACET_934A8665 RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE PUSR_IDCOLONNEESPACET_934A8665
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE PUSR_IDCOLONNEESPACET_934A8665 SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE PUSR_IDCOLONNEESPACET_934A8665 DROP (ITEM_OLD);

create unique index IDX_PUSR_COL_ESP_1 on PUSR_IDCOLONNEESPACET_934A8665(ID, POS, ITEM);
--== Fin PUSR_IDCOLONNEESPACET_934A8665 ==--


--== Début PUSR_IDCOLONNEINSTANC_3FED9D1F ==--
ALTER TABLE PUSR_IDCOLONNEINSTANC_3FED9D1F RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE PUSR_IDCOLONNEINSTANC_3FED9D1F
ADD
   (
   ITEM NVARCHAR2(100)
   );

UPDATE PUSR_IDCOLONNEINSTANC_3FED9D1F SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE PUSR_IDCOLONNEINSTANC_3FED9D1F DROP (ITEM_OLD);

create unique index IDX_PUSR_COL_INST_1 on PUSR_IDCOLONNEINSTANC_3FED9D1F(ID, POS, ITEM);
--== Fin PUSR_IDCOLONNEINSTANC_3FED9D1F ==--


--== Début PUSR_NOTIFICATIONTYPEACTES ==--
ALTER TABLE PUSR_NOTIFICATIONTYPEACTES RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE PUSR_NOTIFICATIONTYPEACTES
ADD
   (
   ITEM NVARCHAR2(10)
   );

UPDATE PUSR_NOTIFICATIONTYPEACTES SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE PUSR_NOTIFICATIONTYPEACTES DROP (ITEM_OLD);

create unique index IDX_PUSR_NOTIF_ACTE_1 on PUSR_NOTIFICATIONTYPEACTES(ID, POS, ITEM);
--== Fin PUSR_NOTIFICATIONTYPEACTES ==--
------====== Fin GESTION DES PREFERENCES UTILISATEUR ======------


--== Début LIS_IDSDOSSIER ==--
ALTER TABLE LIS_IDSDOSSIER RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE LIS_IDSDOSSIER
ADD
   (
   ITEM VARCHAR2(50)
   );

UPDATE LIS_IDSDOSSIER SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE LIS_IDSDOSSIER DROP (ITEM_OLD);

create unique index IDX_LIS_IDDOS_1 on LIS_IDSDOSSIER(ID, ITEM);
--== Fin LIS_IDSDOSSIER ==--


--== TABLE PROXIES ==--
create unique index IDX_PROXIES_1 ON PROXIES(ID, TARGETID);

--== LOCALTHEMECONFIG ==--
CREATE INDEX IDX_THEME_1 ON LOCALTHEMECONFIG(DOCID);

--== NXP_LOGS ==--
CREATE INDEX IDX_NXP_LOGS_1 ON NXP_LOGS(LOG_DOC_UUID);
CREATE INDEX IDX_NXP_LOGS_2 ON NXP_LOGS(LOG_EVENT_DATE);
CREATE INDEX IDX_NXP_LOGS_3 ON NXP_LOGS(LOG_EVENT_CATEGORY);

--== Début MFDDR_FORMATAUTORISE ==--
ALTER TABLE MFDDR_FORMATAUTORISE RENAME COLUMN ITEM TO ITEM_OLD;
ALTER TABLE MFDDR_FORMATAUTORISE
ADD
   (
   ITEM NVARCHAR2(50)
   );

UPDATE MFDDR_FORMATAUTORISE SET ITEM = ITEM_OLD;
COMMIT;

ALTER TABLE MFDDR_FORMATAUTORISE DROP (ITEM_OLD);

create unique index IDX_MFDDR_FORMAT_1 on MFDDR_FORMATAUTORISE(ID, POS, ITEM);
--== Fin MFDDR_FORMATAUTORISE ==--


--== Début TABLES VOCABULAIRES ==--
create index IDX_VOC_ACTE_CATEGORY_1 on VOC_ACTE_CATEGORY("obsolete");
create unique index IDX_VOC_ACTE_CATEGORY_2 on VOC_ACTE_CATEGORY("id");
create index IDX_VOC_ACTE_TYPE_1 on VOC_ACTE_TYPE("obsolete");
create unique index IDX_VOC_ACTE_TYPE_2 on VOC_ACTE_TYPE("id");
create index IDX_VOC_ACTE_TYPE_3 on VOC_ACTE_TYPE(lower("label"));
create index IDX_VOC_BOOL_1 on VOC_BOOLEAN("obsolete");
create index IDX_VOC_BORDEREAU_1 on VOC_BORDEREAU_LABEL("id");
create index IDX_VOC_BORDEREAU_2 on VOC_BORDEREAU_LABEL("obsolete");
create index IDX_VOC_CM_ROUT_TASK_TYPE_1 on VOC_CM_ROUTING_TASK_TYPE("obsolete");
create index IDX_VOC_DOS_STATUS_1 on VOC_DOS_STATUS("obsolete");
create index IDX_VOC_ETAPE_STATUT_RECH_1 on VOC_ETAPE_STATUT_RECHERCHE("obsolete");
create index IDX_VOC_FDR_COLUMN_1 on VOC_FDR_COLUMN("id");
create index IDX_VOC_FDR_COLUMN_2 on VOC_FDR_COLUMN("obsolete");
create unique index IDX_VOC_FILE_FORMAT_1 on VOC_FILE_FORMAT("id");
create unique index IDX_VOC_MODE_PARU_1 on VOC_MODE_PARUTION("id");
create index IDX_VOC_MODE_PARU_2 on VOC_MODE_PARUTION("obsolete");
create unique index IDX_VOC_PAPIER_AVIS_TP_1 on VOC_PAPIER_AVIS_TP("id");
create index IDX_VOC_PAPIER_AVIS_TP_2 on VOC_PAPIER_AVIS_TP("obsolete");
create unique index IDX_VOC_PAPIER_PRIO_1 on VOC_PAPIER_PRIORITE("id");
create index IDX_VOC_PAPIER_PRIO_2 on VOC_PAPIER_PRIORITE("obsolete");
create unique index IDX_VOC_PAPIER_TYPE_1 on VOC_PAPIER_TYPE_SIGN("id");
create index IDX_VOC_PAPIER_TYPE_2 on VOC_PAPIER_TYPE_SIGN("obsolete");
create unique index IDX_VOC_PUBL_DELAI_1 on VOC_PUBLICATION_DELAI("id");
create index IDX_VOC_PUBL_DELAI_2 on VOC_PUBLICATION_DELAI("obsolete");
create unique index IDX_VOC_PUBL_TYPE_1 on VOC_PUBLICATION_TYPE("id");
create unique index IDX_VOC_VECT_PUBL_TP_1 on VOC_VECTEUR_PUBLICATION_TP("id");
create index IDX_VOC_VECT_PUBL_TP_2 on VOC_VECTEUR_PUBLICATION_TP("obsolete");

--== Fin TABLES VOCABULAIRES ==--

--================================================================== Creation des vues ==========================================================================--

CREATE OR REPLACE VIEW V_BORDEREAU_SIGNATURE_LISTE  AS
SELECT DOS.MINISTERERESP, 
        DOS.NUMERONOR,
        LISTE.TYPELISTE,
        LISTE.NUMEROLISTE,
        LISTE.DATEGENERATIONLISTE,
        LISTE.TYPESIGNATURE,
        DOS.TITREACTE,
        LISTE.ID
  FROM DOSSIER_SOLON_EPG DOS,LIS_IDSDOSSIER LISDOS,LISTE_TRAITEMENT_PAPI_144E75F6 LISTE
  WHERE DOS.ID=LISDOS.ITEM 
	AND LISDOS.ID=LISTE.ID 
	AND LISTE.TYPELISTE = '1' ;


CREATE OR REPLACE VIEW V_BORDEREAU_AUTRE_LISTE  AS
SELECT DOS.MINISTERERESP, DOS.NUMERONOR, 
       DOS.TITREACTE, 
       TP.PUBLICATIONEPREUVEENRETOUR,
       TP.PUBLICATIONDELAI,
       TP.PUBLICATIONDATEDEMANDE,
       LISTE.TYPELISTE, LISTE.NUMEROLISTE, 
       LISTE.ID,
       TP.ID as DOCID,
       LISTE.DATEGENERATIONLISTE, 
       LISTE.TYPESIGNATURE,
       NVL(VOCPUBTP."label",' ') AS PUBTPLABEL, 
       NVL(VOCMODEPARU."label",'') AS MODPARULABEL,
       NVL(VOCPUBDEL."label",' ') AS PUBDELAILABEL,
       NVL(VOCVEC."label",'') AS VECTEURPUBLICATION
  FROM DOSSIER_SOLON_EPG DOS,
       TRAITEMENT_PAPIER TP,
       LIS_IDSDOSSIER LISDOS,
       LISTE_TRAITEMENT_PAPI_144E75F6 LISTE,
       VOC_VECTEUR_PUBLICATION_TP VOCPUBTP,
       VOC_MODE_PARUTION VOCMODEPARU,
       VOC_PUBLICATION_DELAI VOCPUBDEL,
       VOC_VECTEUR_PUBLICATION_TP VOCVEC
 WHERE DOS.ID = TP.ID
   AND DOS.ID = LISDOS.ITEM
   AND LISDOS.ID = LISTE.ID
   AND (LISTE.TYPELISTE = '2' OR LISTE.TYPELISTE = '3')
   AND TP.PUBLICATIONNOMPUBLICATION = VOCPUBTP."id"(+)
   AND TP.PUBLICATIONMODEPUBLICATION = VOCMODEPARU."id"(+)
   AND TP.PUBLICATIONDELAI = VOCPUBDEL."id"(+)
   AND TP.PUBLICATIONNOMPUBLICATION = VOCVEC."id"(+);

CREATE OR REPLACE VIEW  V_BORDEREAU_COMMUNICATION AS 
SELECT
    1 AS JOIN_ID,
    DOS.ID,
    TP.SIGNATAIRE,    
    DOS.NUMERONOR,
    DOS.TITREACTE,
    TP.PRIORITE,
    NVL(VOCPRIORITE."label",' ') AS PRIORITELABEL,
    NVL(DOS.PRENOMRESPDOSSIER,' ') || ' ' || NVL(DOS.NOMRESPDOSSIER,' ') AS RESPDOSSIER,
    NVL(DOS.TELRESPDOSSIER,' ') AS TELRESPDOSSIER,
    TP.PERSONNESNOMMEES,
	  DOS.TYPEACTE,
	  TP.TEXTESOUMISAVALIDATION,
	  TP.TEXTEAPUBLIER
FROM
    DOSSIER_SOLON_EPG DOS,
    TRAITEMENT_PAPIER TP,
    VOC_PAPIER_PRIORITE  VOCPRIORITE
WHERE DOS.ID = TP.ID
AND	  TP.PRIORITE=VOCPRIORITE."id"(+);

CREATE OR REPLACE VIEW V_BORDEREAU_ENVOI_EPR_RELC AS 
SELECT
	DOS.ID,
	TP.SIGNATAIRE,
	DOS.NUMERONOR,
	DOS.TITREACTE,
	TP.PRIORITE,
	NVL(VOCPRIORITE."label",' ') AS PRIORITELABEL,
	NVL(DOS.PRENOMRESPDOSSIER,' ') || ' ' || NVL(DOS.NOMRESPDOSSIER,' ') AS RESPDOSSIER,
	NVL(DOS.TELRESPDOSSIER,' ') AS TELRESPDOSSIER
FROM 
	DOSSIER_SOLON_EPG DOS,
	TRAITEMENT_PAPIER TP,
	VOC_PAPIER_PRIORITE VOCPRIORITE
WHERE DOS.ID   = TP.ID
AND   TP.PRIORITE=VOCPRIORITE."id"(+);

CREATE OR REPLACE VIEW V_BORDEREU_RETOUR AS 
SELECT  DOS.ID,
        DOS.NUMERONOR, 
        NVL(DOS.TITREACTE,' ') AS TITREACTE, 
        NVL(TP.MOTIFRETOUR,' ') AS MOTIFRETOUR, 
        NVL(TP.RETOURA,' ') AS RETOURA,
        NVL(DOS.PRENOMRESPDOSSIER,' ') || ' ' || NVL(DOS.NOMRESPDOSSIER,' ') AS RESPDOSSIER,
        NVL(DOS.TELRESPDOSSIER,' ') AS TELRESPDOSSIER
FROM DOSSIER_SOLON_EPG DOS,
     TRAITEMENT_PAPIER TP
WHERE DOS.ID = TP.ID;

--********
--V_STATS
--********

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_COM  AS
SELECT DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.MINISTEREATTACHE, DOS.MINISTERERESP, 
      DES.NOMDESTINATAIRECOMMUNICATION, TO_CHAR(DES.DATEENVOICOMMUNICATION, 'DD/MM/YYYY')DATEENVOICOMMUNICATION
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, HIERARCHY H, DESTINATAIRECOMMUNICATION DES
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND TP.TEXTESOUMISAVALIDATION = 1
AND DOS.ID = TP.ID
AND DOS.ID = H.PARENTID
AND   H.ID = DES.ID 
AND   DES.DATERETOURCOMMUNICATION IS NULL 
AND   DES.DATEENVOICOMMUNICATION IS NOT NULL
ORDER BY DES.DATEENVOICOMMUNICATION ASC;

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_SIG_PM_PR  AS
SELECT DISTINCT DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, 
  NVL(V."label", '') TYPEACTELABEL, MAX(SIG.DATEENVOISIGNATURE)AS DATESIGNATURE,
  LISTE.DATEGENERATIONLISTE
FROM DOSSIER_SOLON_EPG DOS, HIERARCHY H, DONNEESSIGNATAIRE SIG, VOC_ACTE_TYPE V, LIS_IDSDOSSIER LISDOS, LISTE_TRAITEMENT_PAPI_144E75F6 LISTE
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND DOS.TYPEACTE = V."id" (+)
AND H.NAME IN ('tp:signaturePm', 'tp:signaturePr')
AND H.PARENTID = DOS.ID
AND H.ID = SIG.ID
AND SIG.DATEENVOISIGNATURE IS NOT NULL
AND SIG.DATERETOURSIGNATURE IS NULL 
AND DOS.ID=LISDOS.ITEM (+)
AND LISDOS.ID=LISTE.ID (+)
AND (LISTE.TYPELISTE = '1' OR LISTE.TYPELISTE IS NULL)
GROUP BY DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, NVL(V."label", ''), LISTE.DATEGENERATIONLISTE, LISTE.TYPELISTE
ORDER BY LISTE.DATEGENERATIONLISTE;

CREATE OR REPLACE VIEW V_STATS_LISTE_EPREUVE_RELEC  AS
SELECT DISTINCT DOS.*
FROM DOSSIER_SOLON_EPG DOS, 
     TRAITEMENT_PAPIER TP
WHERE DOS.ID = TP.ID
AND   DOS.STATUTARCHIVAGE IN ('1', '2')
AND EXISTS (
				SELECT * 
				FROM INFOEPREUVE EPR, HIERARCHY H
				WHERE DOS.ID = H.PARENTID
				AND   H.ID = EPR.ID
				AND   EPR.EPREUVEENVOIRELECTURELE IS NOT NULL
				AND   TP.RETOURDUBONATITRERLE IS NULL );

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_AMPLIATION  AS
SELECT  DOS.ID, 
		DOS.NUMERONOR, 
		DOS.TITREACTE, 
		LISTAGG (AMP.ITEM, ', ') WITHIN GROUP (ORDER BY AMP.ITEM) ITEM,
    (
      SELECT MAX(I.DATEENVOIAMPLIATION) AS DATEENVOIE FROM INFOHISTORIQUEAMPLIATION I, HIERARCHY H 
      WHERE H.PARENTID = DOS.ID AND H.NAME = 'tp:ampliationHistorique'
      AND I.ID = H.ID GROUP BY H.PARENTID
    )AS DATEENVOIE
FROM (DOSSIER_SOLON_EPG DOS INNER JOIN TP_AMPLIATIONDESTINATAIREMAILS AMP ON DOS.ID = AMP.ID AND   DOS.STATUTARCHIVAGE IN ('1', '2'))
GROUP BY DOS.ID, DOS.NUMERONOR, DOS.TITREACTE
order by DATEENVOIE desc;

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_RIG  AS
SELECT DISTINCT DOS.*
FROM DOSSIER_SOLON_EPG DOS,
     TRAITEMENT_PAPIER TP
WHERE DOS.ID = TP.ID
AND   DOS.STATUTARCHIVAGE IN ('1', '2')
AND( 
	EXISTS
	(
		SELECT *
		FROM ACTIONNABLE_CASE_LINK ACT, CASE_LINK CAS, ROUTING_TASK ROU
		WHERE DOS.ID = CAS.CASEDOCUMENTID
		AND   CAS.ID = ACT.ID
		AND   ACT.ROUTINGTASKID = ROU.ID
		AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
		AND   ROU.TYPE = 13
		AND   DOS.DELAIPUBLICATION = 3
	)
	 OR
	(
		TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY') 
		AND   TP.PUBLICATIONDELAI = 3
	)
);

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_ARRIVE_SGG  AS
SELECT DISTINCT DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, TP.DATEARRIVEPAPIER
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND DOS.ID = TP.ID;

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_CORBEILLE  AS
SELECT DISTINCT DOS.*, ROU.DISTRIBUTIONMAILBOXID
FROM DOSSIER_SOLON_EPG DOS, ACTIONNABLE_CASE_LINK ACT, CASE_LINK CAS, ROUTING_TASK ROU
WHERE DOS.ID = CAS.CASEDOCUMENTID
AND   DOS.STATUTARCHIVAGE IN ('1', '2')
AND CAS.ID = ACT.ID
AND ACT.ROUTINGTASKID = ROU.ID
AND ACT.CASELIFECYCLESTATE = 'running';

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_PUB  AS
SELECT '0' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION, 
  DOS.MINISTERERESP, TO_CHAR (DOS.DATEPRECISEEPUBLICATION, 'DD/MM/YYYY') AS DATEPRECISEPUB,
  NVL(VMP."label",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, RETOUR_DILA RD, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND RD.MODEPARUTION =  VMP."id"(+)
AND DOS.DELAIPUBLICATION = VPD."id" (+)
AND RD.ID = DOS.ID
AND EXISTS ( 	SELECT * 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
				AND   ROU.TYPE IN (13, 14) )
UNION
SELECT '1' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, TP.PUBLICATIONDELAI DELAIPUBLICATION, DOS.MINISTERERESP,
  TP.PUBLICATIONMODEPUBLICATION MODEPARUTION, TO_CHAR (TP.PUBLICATIONDATEDEMANDE, 'DD/MM/YYYY')  AS DATEPRECISEPUB,
  NVL(VMP."label",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
AND TP.PUBLICATIONMODEPUBLICATION = VMP."id" (+)
AND TP.PUBLICATIONDELAI = VPD."id" (+)
AND DOS.ID = TP.ID;

CREATE OR REPLACE VIEW V_STATS_NOMBRE_ACTE_PAR_TYPE  AS
SELECT DOS.TYPEACTE, DOS.ID, DUB.CREATED DATEDOSSIERCREE
FROM DOSSIER_SOLON_EPG DOS, DUBLINCORE DUB
WHERE DOS.ID = DUB.ID
AND   DOS.STATUTARCHIVAGE IN ('1', '2');


CREATE OR REPLACE VIEW V_STATS_NBR_ACTE_TYPE_PERIODE  AS
SELECT DOS.ID, DOS.MINISTEREATTACHE, DOS.MINISTERERESP, DOS.DIRECTIONRESP, DOS.POSTECREATOR, DUB.CREATED DATEDOSSIERCREE
FROM DOSSIER_SOLON_EPG DOS, DUBLINCORE DUB
WHERE DOS.ID = DUB.ID
AND   DOS.STATUTARCHIVAGE IN ('1', '2');

CREATE OR REPLACE VIEW V_STATS_LISTE_ACTE_TYPE_15  AS
SELECT DOS.ID, DOS.MINISTEREATTACHE, TP.DATERETOUR, ROU.DISTRIBUTIONMAILBOXID
FROM DOSSIER_SOLON_EPG DOS, HIERARCHY H, ROUTING_TASK ROU, TRAITEMENT_PAPIER TP
WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
AND   DOS.STATUTARCHIVAGE IN ('1', '2')
AND   H.ID = ROU.ID
AND TP.ID = DOS.ID
AND   ROU.TYPE = 15;

CREATE OR REPLACE VIEW V_STATS_LISTE_ALL_ACTE  AS
SELECT DOS.ID, DOS.MINISTEREATTACHE, TP.DATERETOUR, ROU.DISTRIBUTIONMAILBOXID, ROU.DATEFINETAPE
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, HIERARCHY H, ROUTING_TASK ROU
WHERE DOS.ID = TP.ID
AND DOS.LASTDOCUMENTROUTE = H.PARENTID
AND H.ID = ROU.ID
AND DOS.STATUTARCHIVAGE IN ('1', '2');

CREATE OR REPLACE VIEW V_STATS_LISTE_ALL_ACTE_DETAIL  AS
SELECT  DOS.ID ID, 
		DOS.MINISTEREATTACHE MINISTEREATTACHE,  
		TP.DATERETOUR DATERETOUR, 
		H.POS POS, 
		ROU.DISTRIBUTIONMAILBOXID DISTRIBUTIONMAILBOXID, 
		ROU.TYPE TYPE, ROU.DATEFINETAPE
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, HIERARCHY H, ROUTING_TASK ROU
WHERE DOS.ID = TP.ID
AND   DOS.LASTDOCUMENTROUTE = H.PARENTID
And   Dos.Statutarchivage In ('1', '2')
AND   H.ID = ROU.ID;

--********
--V_AN
--********
CREATE OR REPLACE VIEW V_AN_LOIS_APPELANT_MESURE  AS
SELECT 
TM_LOI.ID AS LOI_ID, 
TM_LOI.MINISTEREPILOTE AS LOI_MINISTERERESP, 
TM_LOI.DATEPUBLICATION AS LOI_DATEPUBLICATION,
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION, 
TM_LOI.DATEENTREEENVIGUEUR AS LOI_DATEENTREEENVIGUEUR
FROM (TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = '1' )
WHERE EXISTS (
    SELECT TM_MES.ID FROM TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM ON TM_MES.ID = TEXM.ITEM 
    WHERE TEXM.ID = TM_LOI.ID)
AND TM_LOI.APPLICATIONDIRECTE <> 1;

CREATE OR REPLACE VIEW V_AN_LOIS_APPELANT_MESURE_VIG  AS
SELECT 
TM_LOI.ID AS LOI_ID, 
TM_LOI.MINISTEREPILOTE AS LOI_MINISTERERESP, 
TM_LOI.DATEPUBLICATION AS LOI_DATEPUBLICATION,
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION, 
TM_LOI.DATEENTREEENVIGUEUR AS LOI_DATEENTREEENVIGUEUR
FROM (TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = '1' )
WHERE EXISTS (
    SELECT TM_MES.ID FROM TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM ON TM_MES.ID = TEXM.ITEM 
    WHERE TEXM.ID = TM_LOI.ID) 
AND NOT EXISTS (
    SELECT TM_MES.ID FROM TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM ON TM_MES.ID = TEXM.ITEM 
    WHERE TEXM.ID = TM_LOI.ID AND TM_MES.TYPEMESURE = '1')
AND TM_LOI.APPLICATIONDIRECTE <> 1
AND TM_LOI.DATEENTREEENVIGUEUR IS NOT NULL;

 
CREATE OR REPLACE VIEW V_AN_MESURES_APPELANT_DECRET  AS
SELECT 
TM_LOI.ID AS LOI_ID, 
TM_LOI.MINISTEREPILOTE AS LOI_MINISTERERESP, 
TM_LOI.DATEPUBLICATION AS LOI_DATEPUBLICATION,
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION, 
TM_LOI.DATEENTREEENVIGUEUR AS LOI_DATEENTREEENVIGUEUR,
TM_LOI.NATURETEXTE AS LOI_NATURETEXTE, 
TM_LOI.PROCEDUREVOTE AS LOI_PROCEDUREVOTE, 
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE
FROM 
(TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = '1' ), 
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM)
WHERE TM_MES.TYPEMESURE = '1'
AND   TM_LOI.ID = TEXM.ID;

CREATE OR REPLACE VIEW V_AN_MESURES_RECU_APPLICATION  AS
SELECT 
TM_LOI.ID AS LOI_ID, 
TM_LOI.MINISTEREPILOTE AS LOI_MINISTERERESP, 
TM_LOI.DATEPUBLICATION AS LOI_DATEPUBLICATION,
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION, 
TM_LOI.DATEENTREEENVIGUEUR AS LOI_DATEENTREEENVIGUEUR,
TM_LOI.NATURETEXTE AS LOI_NATURETEXTE, 
TM_LOI.PROCEDUREVOTE AS LOI_PROCEDUREVOTE, 
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE,
TM_DEC.ID AS DECRET_ID,
TM_DEC.DATEPUBLICATION AS DECRET_DATEPUBLICATION
FROM 
(TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = '1' ), 
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM),
(TEXTE_MAITRE TM_DEC INNER JOIN TEXM_DECRETIDS TEXD   ON TM_DEC.ID = TEXD.ITEM)
WHERE TM_LOI.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU = '1'
AND   TM_MES.ID = TEXD.ID
AND   TM_DEC.DATEPUBLICATION = (SELECT MAX(MX_TM_DEC.DATEPUBLICATION)
								FROM TEXM_MESUREIDS MX_TEXM, 
								(TEXTE_MAITRE MX_TM_DEC INNER JOIN TEXM_DECRETIDS MX_TEXD   ON MX_TM_DEC.ID = MX_TEXD.ITEM)
								WHERE TM_MES.ID = MX_TEXM.ITEM
								AND   MX_TEXM.ID = MX_TM_DEC.ID
                                );

CREATE OR REPLACE VIEW V_AN_MESURES_ATTENTE_DECRET  AS
SELECT 
TM_LOI.ID AS LOI_ID, 
TM_LOI.MINISTEREPILOTE AS LOI_MINISTERERESP, 
TM_LOI.DATEPUBLICATION AS LOI_DATEPUBLICATION,
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION, 
TM_LOI.DATEENTREEENVIGUEUR AS LOI_DATEENTREEENVIGUEUR,
TM_LOI.NATURETEXTE AS LOI_NATURETEXTE, 
TM_LOI.PROCEDUREVOTE AS LOI_PROCEDUREVOTE, 
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE
FROM 
(TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = '1' ), 
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM)
WHERE TM_LOI.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU <> '1';
  
CREATE OR REPLACE VIEW V_AN_MESURES_DELAIS_DERNIER  AS
SELECT LOI_ID, LOI_DATEPROMULGATION, LOI_NATURETEXTE, MESURE_ID, MESURE_MINISTEREPILOTE,
CASE
  WHEN MES_DATEENTREEENVIGUEUR IS NULL 
  THEN (
    CASE WHEN DEC_DATEPUBLICATION < LOI_DATEPUBLICATION THEN 0
    ELSE (abs(extract(day FROM ((DEC_DATEPUBLICATION - LOI_DATEPUBLICATION) day TO second))) / 30) END
  )
  ELSE (
    CASE WHEN DEC_DATEPUBLICATION < MES_DATEENTREEENVIGUEUR THEN 0
    ELSE (abs(extract(day FROM ((DEC_DATEPUBLICATION - MES_DATEENTREEENVIGUEUR) day TO second))) / 30) END
  )
END DELAIS_EN_MOIS
FROM (
  SELECT 
  TM_LOI.ID AS LOI_ID, 
  TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION,
  TM_LOI.DATEPUBLICATION AS LOI_DATEPUBLICATION,
  TM_LOI.NATURETEXTE AS LOI_NATURETEXTE,
  TM_MES.ID AS MESURE_ID,
  TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE,
  TM_MES.DATEENTREEENVIGUEUR AS MES_DATEENTREEENVIGUEUR,
  (SELECT MAX(MX_TM_DEC.DATEPUBLICATION)
                  FROM TEXM_MESUREIDS MX_TEXM, 
                  (TEXTE_MAITRE MX_TM_DEC INNER JOIN TEXM_DECRETIDS MX_TEXD   ON MX_TM_DEC.ID = MX_TEXD.ITEM)
                  WHERE TM_MES.ID = MX_TEXM.ITEM
                  AND   MX_TEXM.ID = MX_TM_DEC.ID 
                                  )as DEC_DATEPUBLICATION
  FROM 
  (TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = '1' ), 
  (TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM)
  WHERE TM_LOI.ID = TEXM.ID
  AND   TM_MES.TYPEMESURE = '1'
  AND   TM_MES.APPLICATIONRECU = '1'
);
								
CREATE OR REPLACE VIEW V_AN_MESURES_DELAIS_PREMIER  AS
SELECT 
TM_LOI.ID AS LOI_ID, 
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION,
TM_LOI.NATURETEXTE AS LOI_NATURETEXTE,
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE,
CASE
  WHEN TM_MES.DATEENTREEENVIGUEUR IS NULL 
  THEN (
    CASE WHEN TM_DEC.DATEPUBLICATION < TM_LOI.DATEPUBLICATION THEN 0
    ELSE (abs(extract(day FROM ((TM_DEC.DATEPUBLICATION - TM_LOI.DATEPUBLICATION) day TO second))) / 30) END
  )
  ELSE (
    CASE WHEN TM_DEC.DATEPUBLICATION < TM_MES.DATEENTREEENVIGUEUR THEN 0
    ELSE (abs(extract(day FROM ((TM_DEC.DATEPUBLICATION - TM_MES.DATEENTREEENVIGUEUR) day TO second))) / 30) END
  )
END DELAIS_EN_MOIS
FROM 
(TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = '1' ), 
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM),
(TEXTE_MAITRE TM_DEC INNER JOIN TEXM_DECRETIDS TEXD   ON TM_DEC.ID = TEXD.ITEM)
WHERE TM_LOI.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU = '1'
AND   TM_MES.ID = TEXD.ID
AND   TM_DEC.DATEPUBLICATION = (SELECT MIN(MN_TM_DEC.DATEPUBLICATION)
								FROM TEXM_MESUREIDS MN_TEXM, 
								(TEXTE_MAITRE MN_TM_DEC INNER JOIN TEXM_DECRETIDS MN_TEXD   ON MN_TM_DEC.ID = MN_TEXD.ITEM)
								WHERE TM_MES.ID = MN_TEXM.ITEM
								AND   MN_TEXM.ID = MN_TM_DEC.ID
                                );
								
CREATE OR REPLACE VIEW V_AN_MESURES_PUBLIEES  AS
SELECT 
TM_MES.ID AS TM_MESURE_ID,
EXTRACT(DAY FROM TM_DEC.DATEPUBLICATION) AS JOUR_DE_PUBLICATION,
EXTRACT(MONTH FROM TM_DEC.DATEPUBLICATION) AS MOIS_DE_PUBLICATION,
EXTRACT(YEAR FROM TM_DEC.DATEPUBLICATION)  AS ANNEE_DE_PUBLICATION
FROM 
(TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = '1' ), 
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM),
(TEXTE_MAITRE TM_DEC INNER JOIN TEXM_DECRETIDS TEXD   ON TM_DEC.ID = TEXD.ITEM)
WHERE TM_LOI.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU = '1'
AND   TM_MES.ID = TEXD.ID
AND   TM_DEC.DATEPUBLICATION = (SELECT MAX(MX_TM_DEC.DATEPUBLICATION)
								FROM TEXM_MESUREIDS MX_TEXM, 
								(TEXTE_MAITRE MX_TM_DEC INNER JOIN TEXM_DECRETIDS MX_TEXD   ON MX_TM_DEC.ID = MX_TEXD.ITEM)
								WHERE TM_MES.ID = MX_TEXM.ITEM
								AND   MX_TEXM.ID = MX_TM_DEC.ID
                                );
								
CREATE OR REPLACE VIEW V_AN_TRANSPOSITION_DIRECTIVE  AS
SELECT 
TM_DIR.NUMERO , TM_DIR.DATEDIRECTIVE, TM_DIR.TITREACTE AS TITRE, TM_DIR.DATEPROCHAINTABAFFICHAGE, TM_DIR.MINISTEREPILOTE AS TD_MINISTEREPILOTE, 
TM_DIR.TABAFFICHAGEMARCHEINT, TM_DIR.ACHEVEE, TM_DIR.OBSERVATION AS TD_OBSERVATION, TM_DIR.DATEECHEANCE, TM_DIR.CHAMPLIBRE, TM_DIR.DATETRANSPOSITIONEFFECTIVE,
VOC."label" AS NATURE, TM_TT.NUMERONOR, TM_TT.MINISTEREPILOTE AS TT_MINISTERE_PILOTE, TM_TT.ETAPESOLON, TM_TT.NUMEROTEXTEPUBLIE,
TM_TT.TITRETEXTEPUBLIE, TM_TT.DATEPUBLICATION
FROM 
((((
 TEXTE_MAITRE TM_DIR 
 INNER JOIN      ACTIVITE_NORMATIVE AN ON TM_DIR.ID = AN.ID AND AN.TRANSPOSITION = '1' ) 
 LEFT OUTER JOIN TEXM_DOSSIERSNOR TEXN ON TM_DIR.ID = TEXN.ID)
 LEFT OUTER JOIN TEXTE_MAITRE TM_TT    ON TEXN.ITEM = TM_TT.NUMERONOR)
 LEFT OUTER JOIN VOC_ACTE_TYPE VOC     ON TM_TT.NATURETEXTE = VOC."id");
 
CREATE OR REPLACE VIEW V_AN_LOI_HAB_ORDONNANCE  AS
SELECT 
TM_RAC.NUMERO AS RAC_NUMERO,
TM_RAC.DATEPUBLICATION AS RAC_DATEPUBLICATION,
TM_RAC.TITREOFFICIEL AS RAC_TITREACTE,
TM_HAB.NUMEROORDRE AS HAB_NUMEROORDRE,
TM_HAB.ARTICLE AS HAB_ARTICLE,
TM_HAB.OBJETRIM AS HAB_OBJETRIM,
VOC_THAB."label" AS HAB_LBLTYPEHABILITATION,
TM_HAB.TYPEHABILITATION AS HAB_TYPEHABILITATION,
TM_HAB.MINISTEREPILOTE AS HAB_MINISTEREPILOTE,
TM_HAB.DATESAISINECE AS HAB_DATESAISINECE,
TM_HAB.DATEPREVISIONNELLECM AS HAB_DATEPREVISIONNELLECM,
TM_HAB.LEGISLATURE AS HAB_LEGISLATURE,
TM_ORD.NUMERONOR AS ORD_NUMERONOR,
TM_ORD.TITREOFFICIEL AS ORD_TITREACTE,
TM_ORD.NUMERO AS ORD_NUMERO,
TM_ORD.DATEPUBLICATION AS ORD_DATEPUBLICATION,
TM_ORD.DATEPASSAGECM AS ORD_DATEPASSAGECM,
TM_ORD.DATESAISINECE AS ORD_DATESAISINECE,
TM_HAB.CONVENTIONDEPOT AS ORD_TERMEDEPOT, 
TM_HAB.DATETERME AS ORD_DATETERME,
TM_ORD.DATELIMITEDEPOT AS ORD_DATELIMITEDEPOT,
TM_ORD.OBSERVATION  AS ORD_OBSERVATION
FROM 
 TEXTE_MAITRE TM_RAC 
 INNER JOIN      ACTIVITE_NORMATIVE AN      ON TM_RAC.ID  = AN.ID AND AN.ORDONNANCE38C = '1'
 LEFT OUTER JOIN TEXM_HABILITATIONIDS TEXH  ON TM_RAC.ID  = TEXH.ID
 LEFT OUTER JOIN TEXTE_MAITRE TM_HAB        ON TEXH.ITEM  = TM_HAB.ID 
 	LEFT OUTER JOIN VOC_TYPE_HABILITATION VOC_THAB ON TM_HAB.TYPEHABILITATION = VOC_THAB."id"
 LEFT OUTER JOIN TEXM_ORDONNANCEIDS TEXO    ON TM_HAB.ID  = TEXO.ID  
 LEFT OUTER JOIN TEXTE_MAITRE TM_ORD        ON TEXO.ITEM  = TM_ORD.ID  
where TM_HAB.TYPEHABILITATION = '0'
ORDER BY TM_RAC.NUMERO, TM_ORD.DATETERME;

CREATE OR REPLACE VIEW V_AN_ORDONNANCE_38  AS
SELECT 
TM_RAC.NUMERO AS RAC_NUMERO,
TM_RAC.TITREOFFICIEL AS HAB_TITREOFFICIEL,
TM_RAC.HAB_ARTICLE AS RAC_TITREACTE,
TM_ORD.NUMERONOR AS ORD_NUMERONOR,
TM_ORD.MINISTEREPILOTE AS ORD_MINISTEREPILOTE,
TM_ORD.TITREOFFICIEL AS ORD_TITREOFFICIEL,
TM_ORD.NUMERO AS ORD_NUMERO,
TM_ORD.DATEPUBLICATION AS ORD_DATEPUBLICATION,
TM_LRA.DATELIMITEDEPOT AS LRA_DATELIMITEDEPOT,
TM_ORD.CONVENTIONDEPOT AS LRA_CONVENTIONDEPOT,
TM_LRA.NUMERONOR AS LRA_NUMERONOR,
TM_LRA.TITREACTE AS LRA_TITREACTE,
TM_LRA.CHAMBREDEPOT AS LRA_CHAMBREDEPOT,
TM_LRA.DATEDEPOT AS LRA_DATEDEPOT,
TM_LRA.NUMERODEPOT AS LRA_NUMERODEPOT,
TM_LRA.TITREOFFICIEL AS LRA_TITREOFFICIEL,
TM_LRA.DATEPUBLICATION AS LRA_DATEPUBLICATION,
TM_ORD.RATIFIE AS ORD_RATIFIE
FROM 
 (TEXTE_MAITRE TM_ORD 
 INNER JOIN      ACTIVITE_NORMATIVE AN      ON TM_ORD.ID  = AN.ID AND AN.ORDONNANCE = '1' AND  TM_ORD.DISPOSITIONHABILITATION = 1)
 LEFT OUTER JOIN
 ( SELECT TEXO.ITEM, TM_RAC.*, TM_HAB.ARTICLE as HAB_ARTICLE FROM
   TEXM_ORDONNANCEIDS TEXO
   INNER JOIN      TEXTE_MAITRE TM_HAB        ON TEXO.ID    = TM_HAB.ID
   INNER JOIN      TEXM_HABILITATIONIDS TEXH  ON TM_HAB.ID  = TEXH.ITEM
   INNER JOIN      TEXTE_MAITRE TM_RAC        ON TEXH.ID    = TM_RAC.ID ) TM_RAC ON TM_ORD.ID = TM_RAC.ITEM
 LEFT OUTER JOIN   TEXM_LOIRATIFICATIONIDS  TEXL   ON TM_ORD.ID = TEXL.ID
 LEFT OUTER JOIN   TEXTE_MAITRE TM_LRA             ON TEXL.ITEM = TM_LRA.ID 
 ORDER BY TM_LRA.DATELIMITEDEPOT;

CREATE OR REPLACE VIEW V_AN_ORDONNANCE_74  AS
SELECT 
TM_ORD.MINISTEREPILOTE AS ORD_MINISTEREPILOTE,
TM_ORD.NUMERONOR AS ORD_NUMERONOR,
TM_ORD.NUMERO AS ORD_NUMERO,
TM_ORD.TITREOFFICIEL AS ORD_TITREOFFICIEL,
TM_ORD.DATEPUBLICATION AS ORD_DATEPUBLICATION,
TM_LRA.DATELIMITEDEPOT AS LRA_DATELIMITEDEPOT,
TM_LRA.DATEDEPOT AS LRA_DATEDEPOT,
TM_LRA.NUMERONOR AS LRA_NUMERONOR,
TM_LRA.TITREACTE AS LRA_TITREACTE,
TM_LRA.DATEPUBLICATION AS LRA_DATEPUBLICATION
FROM 
 (TEXTE_MAITRE TM_ORD 
 INNER JOIN      ACTIVITE_NORMATIVE AN         ON TM_ORD.ID  = AN.ID AND AN.ORDONNANCE = '1' AND  TM_ORD.DISPOSITIONHABILITATION = 0)
 LEFT OUTER JOIN TEXM_LOIRATIFICATIONIDS  TEXL ON TM_ORD.ID  = TEXL.ID
 LEFT OUTER JOIN TEXTE_MAITRE TM_LRA           ON TEXL.ITEM  = TM_LRA.ID 
 ORDER BY TM_LRA.DATELIMITEDEPOT;

CREATE OR REPLACE VIEW V_AN_HAB_ORD_LOI  AS
SELECT 
TM_RAC.NUMERONOR AS RAC_NUMERONOR,
TM_RAC.TITREACTE AS RAC_TITREACTE,
TM_RAC.DATEPUBLICATION AS RAC_DATEPUBLICATION,
TM_HAB.NUMEROORDRE AS HAB_NUMEROORDRE,
TM_HAB.ARTICLE AS HAB_ARTICLE,
TM_HAB.OBJETRIM AS HAB_OBJETRIM,
VOC_THAB."label" AS HAB_TYPEHABILITATION,
TM_HAB.MINISTEREPILOTE AS HAB_MINISTEREPILOTE,
TM_HAB.DATETERME AS HAB_DATETERME,
TM_HAB.CONVENTIONDEPOT AS HAB_CONVENTIONDEPOT,
TM_HAB.DATESAISINECE AS HAB_DATESAISINECE,
TM_HAB.DATEPREVISIONNELLECM AS HAB_DATEPREVISIONNELLECM,
TM_HAB.OBSERVATION AS HAB_OBSERVATION,
TM_HAB.CODIFICATION AS HAB_CODIFICATION,
TM_HAB.LEGISLATURE AS HAB_LEGISLATURE,
TM_ORD.DISPOSITIONHABILITATION AS ORD_DISPOSITIONHABILITATION,
TM_ORD.NUMERONOR AS ORD_NUMERONOR,
TM_ORD.MINISTEREPILOTE AS ORD_MINISTEREPILOTE,
TM_ORD.DATESAISINECE AS ORD_DATESAISINECE,
TM_ORD.DATEPREVISIONNELLECM AS ORD_DATEPREVISIONNELLECM,
TM_ORD.DATEPUBLICATION AS ORD_DATEPUBLICATION,
TM_ORD.TITREOFFICIEL AS ORD_TITREOFFICIEL,
TM_ORD.CONVENTIONDEPOT AS ORD_CONVENTIONDEPOT,
TM_ORD.DATELIMITEDEPOT AS ORD_DATELIMITEDEPOT,
TM_LRA.NUMERONOR AS LRA_NUMERONOR,
TM_LRA.TITREACTE AS LRA_TITREACTE,
TM_LRA.DATESAISINECE AS LRA_DATESAISINECE,
TM_LRA.DATEEXAMENCE AS LRA_DATEEXAMENCE,
TM_LRA.SECTIONCE AS LRA_SECTIONCE,
TM_LRA.DATEEXAMENCM AS LRA_DATEEXAMENCM,
TM_LRA.CHAMBREDEPOT AS LRA_CHAMBREDEPOT,
TM_LRA.DATEDEPOT AS LRA_DATEDEPOT,
TM_LRA.NUMERODEPOT AS LRA_NUMERODEPOT,
TM_LRA.TITREOFFICIEL AS LRA_TITREOFFICIEL,
TM_LRA.DATEPUBLICATION AS LRA_DATEPUBLICATION,
TM_LRA.NUMEROJOPUBLICATION AS LRA_NUMEROJOPUBLICATION
FROM 
 TEXTE_MAITRE TM_RAC 
 INNER JOIN      ACTIVITE_NORMATIVE AN        ON TM_RAC.ID  = AN.ID AND AN.ORDONNANCE38C = '1'
 LEFT OUTER JOIN TEXM_HABILITATIONIDS TEXH    ON TM_RAC.ID  = TEXH.ID
 LEFT OUTER JOIN TEXTE_MAITRE TM_HAB          ON TEXH.ITEM  = TM_HAB.ID 
	LEFT OUTER JOIN VOC_TYPE_HABILITATION VOC_THAB ON TM_HAB.TYPEHABILITATION = VOC_THAB."id"
 LEFT OUTER JOIN TEXM_ORDONNANCEIDS TEXO      ON TM_HAB.ID  = TEXO.ID  
 LEFT OUTER JOIN TEXTE_MAITRE TM_ORD          ON TEXO.ITEM  = TM_ORD.ID  
 LEFT OUTER JOIN TEXM_LOIRATIFICATIONIDS TEXL ON TM_ORD.ID  = TEXL.ID
 LEFT OUTER JOIN TEXTE_MAITRE TM_LRA          ON TEXL.ITEM  = TM_LRA.ID 
ORDER BY TM_RAC.NUMERO, TM_ORD.DATETERME;

CREATE OR REPLACE VIEW V_AN_TRAITE_ACCORD  AS
SELECT
TM_TRAIT.CATEGORIE AS TRAIT_CATEGORIE,
TM_TRAIT.ORGANISATION AS TRAIT_ORGANISATION,
TM_TRAIT.THEMATIQUE AS TRAIT_THEMATIQUE,
TM_TRAIT.DEGREPRIORITE AS TRAIT_DEGREPRIORITE,
TM_TRAIT.TITREACTE AS TRAIT_TITREACTE,
TM_TRAIT.DATESIGNATURE AS TRAIT_DATESIGNATURE,
TM_TRAIT.DATEENTREEENVIGUEUR AS TRAIT_DATEENTREEENVIGUEUR,
TM_TRAIT.MINISTEREPILOTE AS TRAIT_MINISTEREPILOTE,
TM_TRAIT.DATEPJL AS TRAIT_DATEPJL,
TM_TRAIT.DISPOETUDEIMPACT AS TRAIT_DISPOETUDEIMPACT,
TM_TRAIT.DATEDEPOTRATIFICATION AS TRAIT_DATEDEPOTRATIFICATION,
TM_TRAIT.AUTORISATIONRATIFICATION AS TRAIT_AUTORISATIONRATIFICATION,
TM_LRAT.NUMERONOR AS LRAT_NUMERONOR,
TM_LRAT.ETAPESOLON AS LRAT_ETAPESOLON,
TM_LRAT.DATEPUBLICATION AS LRAT_DATEPUBLICATION,
TM_LRAT.TITREACTE AS LRAT_TITREACTE,
TM_TRAIT.NUMERONOR AS DECRET_NUMERONOR,
TM_TRAIT.ETAPESOLON AS DECRET_ETAPESOLON,
TM_TRAIT.NUMERO AS DECRET_NUMERO,
TM_TRAIT.DATEPUBLICATION AS DECRET_DATEPUBLICATION,
TM_TRAIT.TITREACTE AS DECRET_TITREACTE,
TM_TRAIT.OBSERVATION AS DECRET_OBSERVATION
FROM 
 TEXTE_MAITRE TM_TRAIT 
 INNER JOIN      ACTIVITE_NORMATIVE AN ON TM_TRAIT.ID = AN.ID AND AN.TRAITE = '1'
 LEFT OUTER JOIN TEXTE_MAITRE TM_LRAT  ON TM_TRAIT.NORLOIRATIFICATION = TM_LRAT.NUMERONOR;
 
CREATE OR REPLACE VIEW V_AN_TRAITE_ACCORD  AS
SELECT
TM_TRAIT.ID AS TRAIT_ID,
TM_TRAIT.CATEGORIE AS TRAIT_CATEGORIE,
TM_TRAIT.ORGANISATION AS TRAIT_ORGANISATION,
TM_TRAIT.THEMATIQUE AS TRAIT_THEMATIQUE,
TM_TRAIT.DEGREPRIORITE AS TRAIT_DEGREPRIORITE,
TM_TRAIT.TITREACTE AS TRAIT_TITREACTE,
TM_TRAIT.DATESIGNATURE AS TRAIT_DATESIGNATURE,
TM_TRAIT.DATEENTREEENVIGUEUR AS TRAIT_DATEENTREEENVIGUEUR,
TM_TRAIT.MINISTEREPILOTE AS TRAIT_MINISTEREPILOTE,
TM_TRAIT.DATEPJL AS TRAIT_DATEPJL,
TM_TRAIT.DISPOETUDEIMPACT AS TRAIT_DISPOETUDEIMPACT,
TM_TRAIT.ETUDEIMPACT AS TRAIT_ETUDEIMPACT,
TM_TRAIT.DATEDEPOTRATIFICATION AS TRAIT_DATEDEPOTRATIFICATION,
TM_TRAIT.AUTORISATIONRATIFICATION AS TRAIT_AUTORISATIONRATIFICATION,
TM_LRAT.ID AS LRAT_ID,
TM_LRAT.NUMERONOR AS LRAT_NUMERONOR,
TM_LRAT.ETAPESOLON AS LRAT_ETAPESOLON,
TM_LRAT.DATEPUBLICATION AS LRAT_DATEPUBLICATION,
TM_LRAT.TITREACTE AS LRAT_TITREACTE,
TM_TRAIT.NUMERONOR AS DECRET_NUMERONOR,
TM_TRAIT.ETAPESOLON AS DECRET_ETAPESOLON,
TM_TRAIT.NUMERO AS DECRET_NUMERO,
TM_TRAIT.DATEPUBLICATION AS DECRET_DATEPUBLICATION,
TM_TRAIT.TITREACTE AS DECRET_TITREACTE,
TM_TRAIT.OBSERVATION AS DECRET_OBSERVATION
FROM 
 TEXTE_MAITRE TM_TRAIT 
 INNER JOIN      ACTIVITE_NORMATIVE AN ON TM_TRAIT.ID = AN.ID AND AN.TRAITE = '1'
 LEFT OUTER JOIN TEXTE_MAITRE TM_LRAT  ON TM_TRAIT.NORLOIRATIFICATION = TM_LRAT.NUMERONOR;

CREATE OR REPLACE VIEW V_AN_MESURES_LEGISLATIVE  AS
SELECT
TM_LOI.MOTCLE,
TM_LOI.NUMERO AS NUMEROLOI, 
TM_LOI.TITREOFFICIEL, 
TO_CHAR(TM_LOI.DATEPUBLICATION , 'DD/MM/YYYY') DATEPUBLICATION, 
TM_LOI.LEGISLATUREPUBLICATION,
TM_MES.NUMEROORDRE, 
TM_MES.ARTICLE, 
TM_MES.CODEMODIFIE,
TM_MES.BASELEGALE, 
TM_MES.OBJETRIM, 
TM_MES.MINISTEREPILOTE, 
TM_MES.DIRECTIONRESPONSABLE,
TM_MES.CONSULTATIONSHCE,
TM_MES.CALENDRIERCONSULTATIONSHCE,
TM_MES.DATEPREVISIONNELLESAISINECE,
TO_CHAR(TM_MES.DATEOBJECTIFPUBLICATION, 'DD/MM/YYYY') DATEOBJECTIFPUBLICATION,
NVL(VOC_TM_MES."label", '') AS TYPEMESURE,
TM_MES.OBSERVATION,
TM_DEC.NUMERONOR,                
TM_DEC.TITREOFFICIEL DECRET_TITREOFFICIEL,  
NVL(VOC_TM_DEC."label",' ') AS TYPACTE,
TO_CHAR(TM_DEC.DATESAISINECE, 'DD/MM/YYYY') DATESAISINECE, 
TO_CHAR(TM_DEC.DATESORTIECE, 'DD/MM/YYYY') DATESORTIECE, 
TO_CHAR(TM_DEC.DATEPUBLICATION, 'DD/MM/YYYY') DECRET_DATEPUBLICATION,
TM_MES.APPLICATIONRECU
FROM TEXTE_MAITRE TM_LOI, TEXM_MESUREIDS TME, ACTIVITE_NORMATIVE AN, TEXTE_MAITRE TM_MES 
LEFT JOIN VOC_TYPE_MESURE VOC_TM_MES ON TM_MES.TYPEMESURE = VOC_TM_MES."id"
LEFT JOIN TEXM_DECRETIDS TD ON TD.ID = TM_MES.ID
LEFT JOIN TEXTE_MAITRE TM_DEC ON TM_DEC.ID = TD.ITEM
LEFT JOIN VOC_ACTE_TYPE VOC_TM_DEC ON TM_DEC.TYPEACTE = VOC_TM_DEC."id"
WHERE TM_LOI.ID = AN.ID
AND AN.APPLICATIONLOI = '1'
AND TM_MES.TYPEMESURE IN ('1','4' ,'6')
AND TME.ID = AN.ID
AND TM_MES.ID = TME.ITEM
ORDER BY NUMEROLOI, TO_NUMBER(TM_MES.NUMEROORDRE);

CREATE OR REPLACE VIEW V_AN_MESURES_PREVISIONNELLE  AS
SELECT
TM_LOI.NUMERO AS NUMEROLOI,  
TM_LOI.TITREOFFICIEL, 
TM_MES.NUMEROORDRE, 
TM_MES.ARTICLE, 
TM_MES.BASELEGALE, 
TM_MES.OBJETRIM, 
TM_MES.MINISTEREPILOTE, 
TM_MES.DIRECTIONRESPONSABLE,
TM_MES.CONSULTATIONSHCE,
TM_MES.CALENDRIERCONSULTATIONSHCE,
TO_CHAR(TM_MES.DATEPREVISIONNELLESAISINECE, 'DD/MM/YYYY') DATEPREVISIONNELLESAISINECE,
TO_CHAR(TM_MES.DATEOBJECTIFPUBLICATION, 'DD/MM/YYYY') DATEOBJECTIFPUBLICATION,
TO_CHAR(TM_DEC.DATESAISINECE, 'DD/MM/YYYY') DATESAISINECE, 
TO_CHAR(TM_DEC.DATESORTIECE, 'DD/MM/YYYY') DATESORTIECE, 
TM_MES.OBSERVATION, 
TM_DEC.NUMERONOR,
TM_DEC.TITREOFFICIEL DECRET_TITREOFFICIEL, 
NVL(VOC_TM_DEC."label", '') AS TYPACTE,
TO_CHAR(TM_DEC.DATEPUBLICATION, 'DD/MM/YYYY') DATEPUBLICATION,
TM_MES.APPLICATIONRECU
FROM TEXTE_MAITRE TM_LOI, TEXM_MESUREIDS TME, ACTIVITE_NORMATIVE AN, TEXTE_MAITRE TM_MES
LEFT JOIN TEXM_DECRETIDS TD ON TD.ID = TM_MES.ID
LEFT JOIN TEXTE_MAITRE TM_DEC ON TM_DEC.ID = TD.ITEM
LEFT JOIN VOC_ACTE_TYPE VOC_TM_DEC ON TM_DEC.TYPEACTE = VOC_TM_DEC."id"
WHERE TM_LOI.ID = AN.ID
AND AN.APPLICATIONLOI = '1'
AND TM_MES.TYPEMESURE = '1'
AND TME.ID = AN.ID
AND TM_MES.ID = TME.ITEM
AND TM_MES.DATEOBJECTIFPUBLICATION < SYSDATE
ORDER BY NUMEROLOI, TO_NUMBER(TM_MES.NUMEROORDRE);

CREATE OR REPLACE FORCE VIEW V_FICHE_LOI_NAVETTE
AS
  SELECT F.ID,
    F.INTITULE,
    F.PROCEDUREACCELEREE,
    F.ASSEMBLEEDEPOT,
    F.DATEDEPOT,
    F.NUMERODEPOT,
    N.CODELECTURE,
    N.NIVEAULECTURE,
    N.DATETRANSMISSION,
    N.SORTADOPTION,
    N.DATEADOPTION
  FROM FICHE_LOI F,
    NAVETTE N
  WHERE F.ID = N.IDFICHE;
  
CREATE OR REPLACE VIEW V_COURIER_PRESIDENT_INFO
AS
 SELECT 'AN' AS CODE, NOMAN NOM, 'Palais du Luxembourg' AS ADDRESS, 'Président de l’Assemblée nationale' AS PRESIDENT
 FROM PARAMETRAGE_MGPP
 UNION ALL
 SELECT 'S' AS CODE, NOMSENAT NOM, 'Palais Bourbon' AS ADDRESS, 'Président du Sénat' AS PRESIDENT
 FROM PARAMETRAGE_MGPP;
 
 --create index idx_qrtz_t_next_fire_time on qrtz_triggers(NEXT_FIRE_TIME);
--create index idx_qrtz_t_state on qrtz_triggers(TRIGGER_STATE);
--create index idx_qrtz_t_nf_st on qrtz_triggers(TRIGGER_STATE,NEXT_FIRE_TIME);
--create index idx_qrtz_ft_trig_name on qrtz_fired_triggers(TRIGGER_NAME);
--create index idx_qrtz_ft_trig_group on qrtz_fired_triggers(TRIGGER_GROUP);
--create index idx_qrtz_ft_trig_name on qrtz_fired_triggers(TRIGGER_NAME);
--create index idx_qrtz_ft_trig_n_g on \
--    qrtz_fired_triggers(TRIGGER_NAME,TRIGGER_GROUP);
--create index idx_qrtz_ft_trig_inst_name on qrtz_fired_triggers(INSTANCE_NAME);
--create index idx_qrtz_ft_job_name on qrtz_fired_triggers(JOB_NAME);
--create index idx_qrtz_ft_job_group on qrtz_fired_triggers(JOB_GROUP);
--create index idx_qrtz_t_next_fire_time_misfire on \
--    qrtz_triggers(MISFIRE_INSTR,NEXT_FIRE_TIME);
--create index idx_qrtz_t_nf_st_misfire on \
--    qrtz_triggers(MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE);
--create index idx_qrtz_t_nf_st_misfire_grp on \
--    qrtz_triggers(MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_GROUP,TRIGGER_STATE);

 -- Ajour d'index sur la table Feuille de route --

CREATE INDEX "IDX_FEUILLE_ROUTE_DIR" ON "FEUILLE_ROUTE" ("DIRECTION");
CREATE INDEX "IDX_FEUILLE_ROUTE_DEFAULT" ON "FEUILLE_ROUTE" ("FEUILLEROUTEDEFAUT");

-- Ajour d'index sur la table de l'activite normative --

CREATE INDEX "IDX_TEXM_NUMERO" ON "TEXTE_MAITRE" ("NUMERO");
CREATE INDEX "IDX_TEXM_NOR" ON "TEXTE_MAITRE" ("NUMERONOR");
CREATE INDEX "IDX_TEXM_NUMORDRE" ON "TEXTE_MAITRE" ("NUMEROORDRE");
CREATE INDEX "IDX_TEXM_IDDOS" ON "TEXTE_MAITRE" ("IDDOSSIER");
CREATE INDEX "IDX_TEXM_ARTICLE" ON "TEXTE_MAITRE" ("ARTICLE");
  
CREATE INDEX "IDX_MISC_LF" ON "MISC" ("LIFECYCLESTATE");

spool off;
