-- A passer dans sqlplus ! avant 02_create_index.sql

SPOOL drop_index.sql
SELECT 'DROP INDEX ' || index_name ||';' FROM USER_INDEXES WHERE table_name = 'DOSSIER_SOLON_EPG';
SPOOL OFF;
@drop_index;

SPOOL drop_index.sql
SELECT 'DROP INDEX ' || index_name ||';' FROM USER_INDEXES WHERE table_name = 'HIERARCHY';
SPOOL OFF;
@drop_index;

SPOOL drop_index.sql
SELECT 'DROP INDEX ' || index_name ||';' FROM USER_INDEXES WHERE table_name = 'DUBLINCORE';
SPOOL OFF;
@drop_index;

SPOOL drop_index.sql
SELECT 'DROP INDEX ' || index_name ||';' FROM USER_INDEXES WHERE table_name = 'CASE_LINK';
SPOOL OFF;
@drop_index;

SPOOL drop_index.sql
SELECT 'DROP INDEX ' || index_name ||';' FROM USER_INDEXES WHERE table_name = 'ACTIONNABLE_CASE_LINK';
SPOOL OFF;
@drop_index;

SPOOL drop_index.sql
SELECT 'DROP INDEX ' || index_name ||';' FROM USER_INDEXES WHERE table_name = 'MISC';
SPOOL OFF;
@drop_index;

commit;


-- A passer apres 01_drop_index.sql

-- INDEX ACTIONNABLE_CASE_LINK
CREATE UNIQUE INDEX "IDX_ACT_CL_LIFE_STATUS" ON "ACTIONNABLE_CASE_LINK" ("CASELIFECYCLESTATE", "STATUTARCHIVAGE", "ID");
CREATE UNIQUE INDEX "ACTIONNABLE_CASE_LINK_PK" ON "ACTIONNABLE_CASE_LINK" ("ID");
CREATE UNIQUE INDEX "IDX_ACTIONNABLE_CASE_LINK_1" ON "ACTIONNABLE_CASE_LINK" ("STEPDOCUMENTID", "ID");
CREATE INDEX "IDX_ACTIONNABLE_CASE_LINK_2" ON "ACTIONNABLE_CASE_LINK" ("AUTOMATICVALIDATION");
CREATE INDEX "IDX_ACTIONNABLE_CASE_LINK_3" ON "ACTIONNABLE_CASE_LINK" ("DUEDATE");
CREATE UNIQUE INDEX "IDX_ACTIONNABLE_CASE_LINK_4" ON "ACTIONNABLE_CASE_LINK" ("ID" ,"CASELIFECYCLESTATE");

-- INDEX CASE_LINK
CREATE UNIQUE INDEX "CASE_LINK_PK" ON "CASE_LINK" ("ID");
CREATE UNIQUE INDEX "IDX_CASE_LINK_1" ON "CASE_LINK" ("ID", "DATE");
CREATE UNIQUE INDEX "IDX_CASE_LINK_2" ON "CASE_LINK" ("CASEDOCUMENTID", "ID");

-- INDEX DOSSIER_SOLON_EPG
CREATE UNIQUE INDEX "DOSSIER_ARCH_ID" ON "DOSSIER_SOLON_EPG" ("STATUTARCHIVAGE", "ID");
CREATE UNIQUE INDEX "DOSSIER_STAT_ID" ON "DOSSIER_SOLON_EPG" ("STATUT", "ID");
CREATE UNIQUE INDEX "IDX_DOSSIER_EPG_1" ON "DOSSIER_SOLON_EPG" ("ID", "STATUTARCHIVAGE");
CREATE UNIQUE INDEX "IDX_DOSSIER_EPG_2" ON "DOSSIER_SOLON_EPG" ("ID", "CATEGORIEACTE");
CREATE UNIQUE INDEX "IDX_DOSSIER_EPG_3" ON "DOSSIER_SOLON_EPG" ("ID", "NUMERONOR");
CREATE INDEX "IDX_DOSSIER_EPG_4" ON "DOSSIER_SOLON_EPG" ("STATUT");
CREATE UNIQUE INDEX "IDX_DOSSIER_EPG_5" ON "DOSSIER_SOLON_EPG" ("ID", "TYPEACTE");
CREATE INDEX "IDX_DOSSIER_EPG_6" ON "DOSSIER_SOLON_EPG" ("LASTDOCUMENTROUTE");
CREATE UNIQUE INDEX "DOSSIER_SOLON_EPG_PK" ON "DOSSIER_SOLON_EPG" ("ID");
CREATE UNIQUE INDEX "DOSSIER_SOLON_EPG_NOR" ON "DOSSIER_SOLON_EPG" ("NUMERONOR");
CREATE INDEX "IDX_DOSSIER_EPG_CREATOR" ON "DOSSIER_SOLON_EPG" ("POSTECREATOR");

-- INDEX HIERARCHY
CREATE UNIQUE INDEX "IDX_HIER_1" ON "HIERARCHY" ("PRIMARYTYPE", "ID");
CREATE INDEX "IDX_HIER_2" ON "HIERARCHY" ("PARENTID", "ISPROPERTY");
CREATE UNIQUE INDEX "IDX_HIER_4" ON "HIERARCHY" ("ID", "PRIMARYTYPE");
CREATE UNIQUE INDEX "IDX_HIER_5" ON "HIERARCHY" ("ID", "MIXINTYPES");
CREATE UNIQUE INDEX "IDX_HIER_6" ON "HIERARCHY" ("ID", "ISVERSION");
CREATE UNIQUE INDEX "HIERARCHY_PK" ON "HIERARCHY" ("ID");
CREATE INDEX "HIER_B0ED9092_IDX" ON "HIERARCHY" ("PARENTID", "NAME");
CREATE INDEX "HIERARCHY_PARENTID_IDX" ON "HIERARCHY" ("PARENTID", "ID");
CREATE INDEX "HIERARCHY_ISVERSION_IDX" ON "HIERARCHY" ("ISVERSION");

-- INDEX MISC
CREATE UNIQUE INDEX "MISC_PK" ON "MISC" ("ID");
CREATE UNIQUE INDEX "IDX_MISC_1" ON "MISC" ("ID", "LIFECYCLESTATE");
CREATE UNIQUE INDEX "IDX_MISC_2" ON "MISC" ("LIFECYCLESTATE", "ID");
CREATE  INDEX "IDX_MISC_LF" ON "MISC" ("LIFECYCLESTATE"); 

-- INDEX DUBLINCORE
CREATE UNIQUE INDEX "DUBLINCORE_PK" ON "DUBLINCORE" ("ID"); 
CREATE UNIQUE INDEX "IDX_DUBLINCORE_1" ON "DUBLINCORE" ("ID", "TITLE");
CREATE UNIQUE INDEX "IDX_DUBLINCORE_2" ON "DUBLINCORE" ("ID", "CREATOR");
CREATE UNIQUE INDEX "IDX_DUBLINCORE_CREATED" ON "DUBLINCORE" ("ID", "CREATED");

commit;