-- Attention ! Ce fichier est potentiellement destructif. 
-- Ne pas le passer sur une base de données déjà existante !

spool initialisationBdd.log

--== Début DOSSIER_SOLON_EPG ==--
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN STATUT TO STATUT_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN STATUTARCHIVAGE TO STATUTARCHIVAGE_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN NUMERONOR TO NUMERONOR_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN CATEGORIEACTE TO CATEGORIEACTE_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN IDDOCUMENTPARAPHEUR TO IDDOCUMENTPARAPHEUR_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN TYPEACTE TO TYPEACTE_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN PUBLICATIONINTEGRALEOUEXTRAIT TO INTEGRALEOUEXTRAIT_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN MINISTEREATTACHE TO MINISTEREATTACHE_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN BASELEGALEACTE TO BASELEGALEACTE_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN LASTDOCUMENTROUTE TO LASTDOCUMENTROUTE_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN DIRECTIONRESP TO DIRECTIONRESP_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN MINISTERERESP TO MINISTERERESP_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN IDDOCUMENTFDD TO IDDOCUMENTFDD_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN DIRECTIONATTACHE TO DIRECTIONATTACHE_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN DELAIPUBLICATION TO DELAIPUBLICATION_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN NOMRESPDOSSIER TO NOMRESPDOSSIER_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN PRENOMRESPDOSSIER TO PRENOMRESPDOSSIER_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN QUALITERESPDOSSIER TO QUALITERESPDOSSIER_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN MAILRESPDOSSIER TO MAILRESPDOSSIER_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN TELRESPDOSSIER TO TELRESPDOSSIER_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN IDCREATEURDOSSIER TO IDCREATEURDOSSIER_OLD;
ALTER TABLE DOSSIER_SOLON_EPG RENAME COLUMN CANDIDAT TO CANDIDAT_OLD;

ALTER TABLE DOSSIER_SOLON_EPG
ADD
   (
   STATUT NVARCHAR2(2),
   STATUTARCHIVAGE NVARCHAR2(2),
   NUMERONOR NVARCHAR2(12),
   CATEGORIEACTE NVARCHAR2(50),
   IDDOCUMENTPARAPHEUR VARCHAR2(50),
   TYPEACTE NVARCHAR2(10),
   PUBLICATIONINTEGRALEOUEXTRAIT NVARCHAR2(1),
   MINISTEREATTACHE NVARCHAR2(50),
   BASELEGALEACTE NVARCHAR2(100),
   LASTDOCUMENTROUTE VARCHAR2(50),
   DIRECTIONRESP NVARCHAR2(50),
   MINISTERERESP NVARCHAR2(50),
   IDDOCUMENTFDD VARCHAR2(50),
   DIRECTIONATTACHE NVARCHAR2(50),
   DELAIPUBLICATION NVARCHAR2(2),
   NOMRESPDOSSIER NVARCHAR2(100),
   PRENOMRESPDOSSIER NVARCHAR2(100),
   QUALITERESPDOSSIER NVARCHAR2(250),
   MAILRESPDOSSIER NVARCHAR2(150),
   TELRESPDOSSIER NVARCHAR2(50),
   IDCREATEURDOSSIER NVARCHAR2(100),
   CANDIDAT NVARCHAR2(2)
   );

UPDATE DOSSIER_SOLON_EPG
SET STATUT = STATUT_OLD,
    STATUTARCHIVAGE = STATUTARCHIVAGE_OLD,
    NUMERONOR = NUMERONOR_OLD,
	CATEGORIEACTE = CATEGORIEACTE_OLD,
	IDDOCUMENTPARAPHEUR = IDDOCUMENTPARAPHEUR_OLD,
	TYPEACTE = TYPEACTE_OLD,
	PUBLICATIONINTEGRALEOUEXTRAIT = INTEGRALEOUEXTRAIT_OLD,
	MINISTEREATTACHE = MINISTEREATTACHE_OLD,
	BASELEGALEACTE = BASELEGALEACTE_OLD,
	LASTDOCUMENTROUTE = LASTDOCUMENTROUTE_OLD,
	DIRECTIONRESP = DIRECTIONRESP_OLD,
	MINISTERERESP = MINISTERERESP_OLD,
	IDDOCUMENTFDD = IDDOCUMENTFDD_OLD,
	DIRECTIONATTACHE = DIRECTIONATTACHE_OLD,
	DELAIPUBLICATION = DELAIPUBLICATION_OLD,
	NOMRESPDOSSIER = NOMRESPDOSSIER_OLD,
	PRENOMRESPDOSSIER = PRENOMRESPDOSSIER_OLD,
	QUALITERESPDOSSIER = QUALITERESPDOSSIER_OLD,
	MAILRESPDOSSIER = MAILRESPDOSSIER_OLD,
	TELRESPDOSSIER = TELRESPDOSSIER_OLD,
	IDCREATEURDOSSIER = IDCREATEURDOSSIER_OLD,
	CANDIDAT = CANDIDAT_OLD;
COMMIT;

ALTER TABLE DOSSIER_SOLON_EPG DROP (STATUT_OLD, STATUTARCHIVAGE_OLD, NUMERONOR_OLD, CATEGORIEACTE_OLD, IDDOCUMENTPARAPHEUR_OLD, TYPEACTE_OLD, INTEGRALEOUEXTRAIT_OLD,
									MINISTEREATTACHE_OLD, BASELEGALEACTE_OLD, LASTDOCUMENTROUTE_OLD, DIRECTIONRESP_OLD, MINISTERERESP_OLD,
									IDDOCUMENTFDD_OLD, DIRECTIONATTACHE_OLD, DELAIPUBLICATION_OLD, NOMRESPDOSSIER_OLD,
									PRENOMRESPDOSSIER_OLD, QUALITERESPDOSSIER_OLD, MAILRESPDOSSIER_OLD, TELRESPDOSSIER_OLD, IDCREATEURDOSSIER_OLD,
									CANDIDAT_OLD);

CREATE UNIQUE INDEX IDX_DOSSIER_EPG_1 ON DOSSIER_SOLON_EPG(ID, STATUTARCHIVAGE);
CREATE UNIQUE INDEX IDX_DOSSIER_EPG_2 ON DOSSIER_SOLON_EPG(ID, CATEGORIEACTE);
CREATE UNIQUE INDEX IDX_DOSSIER_EPG_3 ON DOSSIER_SOLON_EPG(ID, NUMERONOR);
CREATE INDEX IDX_DOSSIER_EPG_4 ON DOSSIER_SOLON_EPG(STATUT);
CREATE UNIQUE INDEX IDX_DOSSIER_EPG_5 ON DOSSIER_SOLON_EPG(ID, TYPEACTE);
CREATE UNIQUE INDEX IDX_DOSSIER_EPG_6 ON DOSSIER_SOLON_EPG(LASTDOCUMENTROUTE);



--== Début ALTER_ACTIONNABLE_CASE_LINK ==--
ALTER TABLE ACTIONNABLE_CASE_LINK RENAME COLUMN STEPDOCUMENTID TO STEPDOCUMENTID_OLD;
ALTER TABLE ACTIONNABLE_CASE_LINK RENAME COLUMN ROUTINGTASKID TO ROUTINGTASKID_OLD;
ALTER TABLE ACTIONNABLE_CASE_LINK RENAME COLUMN CASELIFECYCLESTATE TO CASELIFECYCLESTATE_OLD;
ALTER TABLE ACTIONNABLE_CASE_LINK RENAME COLUMN STATUTARCHIVAGE TO STATUTARCHIVAGE_OLD;
ALTER TABLE ACTIONNABLE_CASE_LINK RENAME COLUMN ROUTINGTASKLABEL TO ROUTINGTASKLABEL_OLD;
ALTER TABLE ACTIONNABLE_CASE_LINK RENAME COLUMN ROUTINGTASKTYPE TO ROUTINGTASKTYPE_OLD;
ALTER TABLE ACTIONNABLE_CASE_LINK RENAME COLUMN VALIDATIONOPERATIONCHAINID TO VALIDATIONOPERATIONCHAINID_OLD;
ALTER TABLE ACTIONNABLE_CASE_LINK RENAME COLUMN REFUSALOPERATIONCHAINID TO REFUSALOPERATIONCHAINID_OLD;
ALTER TABLE ACTIONNABLE_CASE_LINK RENAME COLUMN ROUTINGTASKMAILBOXLABEL TO ROUTINGTASKMAILBOXLABEL_OLD;

ALTER TABLE ACTIONNABLE_CASE_LINK
ADD
   (
   STEPDOCUMENTID VARCHAR2(50),
   ROUTINGTASKID VARCHAR2(50),
   CASELIFECYCLESTATE NVARCHAR2(50),
   STATUTARCHIVAGE NVARCHAR2(2),
   ROUTINGTASKLABEL NVARCHAR2(150),
   ROUTINGTASKTYPE NVARCHAR2(4),
   VALIDATIONOPERATIONCHAINID NVARCHAR2(150),
   REFUSALOPERATIONCHAINID NVARCHAR2(150),
   ROUTINGTASKMAILBOXLABEL NVARCHAR2(150)
   );

UPDATE ACTIONNABLE_CASE_LINK
SET STEPDOCUMENTID = STEPDOCUMENTID_OLD,
    ROUTINGTASKID = ROUTINGTASKID_OLD,
	CASELIFECYCLESTATE = CASELIFECYCLESTATE_OLD,
	STATUTARCHIVAGE = STATUTARCHIVAGE_OLD,
	ROUTINGTASKLABEL = ROUTINGTASKLABEL_OLD,
	ROUTINGTASKTYPE = ROUTINGTASKTYPE_OLD,
	VALIDATIONOPERATIONCHAINID = VALIDATIONOPERATIONCHAINID_OLD,
	ROUTINGTASKMAILBOXLABEL = ROUTINGTASKMAILBOXLABEL_OLD;
COMMIT;

ALTER TABLE ACTIONNABLE_CASE_LINK DROP (STEPDOCUMENTID_OLD, ROUTINGTASKID_OLD, CASELIFECYCLESTATE_OLD, STATUTARCHIVAGE_OLD, ROUTINGTASKLABEL_OLD,
										ROUTINGTASKTYPE_OLD, VALIDATIONOPERATIONCHAINID_OLD, REFUSALOPERATIONCHAINID_OLD, ROUTINGTASKMAILBOXLABEL_OLD);

create unique index IDX_ACTIONNABLE_CASE_LINK_1 on ACTIONNABLE_CASE_LINK(STEPDOCUMENTID, ID);
create index IDX_ACTIONNABLE_CASE_LINK_2 ON ACTIONNABLE_CASE_LINK(AUTOMATICVALIDATION);
create index IDX_ACTIONNABLE_CASE_LINK_3 on ACTIONNABLE_CASE_LINK(DUEDATE);
create unique index IDX_ACTIONNABLE_CASE_LINK_4 on ACTIONNABLE_CASE_LINK(ID, CASELIFECYCLESTATE);
create unique index IDX_ACTIONNABLE_CASE_LINK_5 on ACTIONNABLE_CASE_LINK(ID, STATUTARCHIVAGE);
create unique index IDX_ACTIONNABLE_CASE_LINK_6 on ACTIONNABLE_CASE_LINK(ID, ROUTINGTASKTYPE);


spool off;