-- versement des dossiers en attente d'archivage intermediaire vers archivage intermédiaire

UPDATE ACTIONNABLE_CASE_LINK SET STATUTARCHIVAGE = 3,ARCHIVE=1 WHERE CASEDOCUMENTID IN (SELECT ID FROM DOSSIER_SOLON_EPG WHERE STATUTARCHIVAGE = 2);
UPDATE DOSSIER_SOLON_EPG SET DATEVERSEMENTARCHIVAG_E55E9FEF=SYSDATE,STATUTARCHIVAGE = 3,ARCHIVE=1 WHERE STATUTARCHIVAGE = 2 ;
commit;
