-- Création de la table MAJ_MINMINISTERIELLE

CREATE TABLE "MAJ_MINISTERIELLE"
  (
    "ID" VARCHAR2(36 BYTE) NOT NULL ENABLE,
    "MODIFICATION" NVARCHAR2(2000),
    "IDDOSSIER" NVARCHAR2(2000),
    "REFMESURE" NVARCHAR2(2000),
    "COMMENTAIRE" NVARCHAR2(2000),
    "NUMEROARTICLES" NVARCHAR2(2000),
    "NORDOSSIER" NVARCHAR2(2000),
    "REF" NVARCHAR2(2000),
    "TITRE" NVARCHAR2(2000),
    "DATECREATION" TIMESTAMP (6),
    CONSTRAINT "MAJ_MINISTERIELLE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "MAJ__2F99C1A7_FK" FOREIGN KEY ("ID") REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
  );
COMMIT;