CREATE UNIQUE INDEX "ACT_NORM_APLLICATION_LOI" ON "ACTIVITE_NORMATIVE" ("APPLICATIONLOI", "ID"); 
CREATE UNIQUE INDEX "ACT_NORM_TRANSPOSITION" ON "ACTIVITE_NORMATIVE" ("TRANSPOSITION", "ID"); 
CREATE UNIQUE INDEX "ACT_NORM_ORDONNANCE" ON "ACTIVITE_NORMATIVE" ("ORDONNANCE", "ID"); 
CREATE UNIQUE INDEX "ACT_NORM_ORDONNANCE38C" ON "ACTIVITE_NORMATIVE" ("ORDONNANCE38C", "ID");
CREATE UNIQUE INDEX "ACT_NORM_TRAITE" ON "ACTIVITE_NORMATIVE" ("TRAITE", "ID"); 

CREATE UNIQUE INDEX "TM_NUMERONOR" ON "TEXTE_MAITRE" ("NUMERONOR", "ID"); 
CREATE UNIQUE INDEX "TM_TYPEMESURE" ON "TEXTE_MAITRE" ("TYPEMESURE", "ID");
CREATE UNIQUE INDEX "TM_TYPEACTE" ON "TEXTE_MAITRE" ("TYPEACTE", "ID"); 
CREATE UNIQUE INDEX "TM_APPLICATIONRECU" ON "TEXTE_MAITRE" ("APPLICATIONRECU", "TYPEMESURE", "ID"); 
CREATE UNIQUE INDEX "TM_DATEPUBLICATION" ON "TEXTE_MAITRE" ("DATEPUBLICATION", "ID"); 
CREATE UNIQUE INDEX "TM_DATEPROMULGATION" ON "TEXTE_MAITRE" ("DATEPROMULGATION", "ID"); 
CREATE UNIQUE INDEX "TM_DISPOSITIONHABILITATION" ON "TEXTE_MAITRE" ("DISPOSITIONHABILITATION", "ID"); 
CREATE UNIQUE INDEX "TM_NORLOIRATIFICATION" ON "TEXTE_MAITRE" ("NORLOIRATIFICATION", "ID");
CREATE UNIQUE INDEX "TM_DATEOBJECTIFPUBID" ON "TEXTE_MAITRE" ("DATEOBJECTIFPUBLICATION", "ID");

CREATE INDEX "TM_DECRET_ITEMID" ON "TEXM_DECRETIDS" ("ITEM", "ID");
CREATE INDEX "TM_MESURE_ITEMID" ON "TEXM_MESUREIDS" ("ITEM", "ID");
CREATE INDEX "TM_DOSSIER_ITEMID" ON "TEXM_DOSSIERSNOR" ("ITEM", "ID");
CREATE INDEX "TM_HABILITATION_ITEMID" ON "TEXM_HABILITATIONIDS" ("ITEM", "ID");
CREATE INDEX "TM_ORDONNANCE_ITEMID" ON "TEXM_ORDONNANCEIDS" ("ITEM", "ID");
CREATE INDEX "TM_RATIFICATION_ITEMID" ON "TEXM_LOIRATIFICATIONIDS" ("ITEM", "ID");

commit;