ALTER TABLE "NAVETTE" DROP COLUMN "DATEREUNIONAN";

ALTER TABLE "NAVETTE" DROP COLUMN "DATEREUNIONSE";

CREATE TABLE "NAV_DATEREUNIONSE" (
    "ID"  VARCHAR2(36 BYTE) NOT NULL ENABLE,
    "POS" NUMBER(10,0),
    "ITEM" TIMESTAMP (6),
    CONSTRAINT "NAV_DATEREUNIONSE_FK" FOREIGN KEY ("ID") REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
  );
  
CREATE INDEX "NAV_DATEREUNIONSE_ID_IDX" ON "NAV_DATEREUNIONSE" ("ID");
  

CREATE TABLE "NAV_DATEREUNIONAN" (
    "ID"  VARCHAR2(36 BYTE) NOT NULL ENABLE,
    "POS" NUMBER(10,0),
    "ITEM" TIMESTAMP (6),
    CONSTRAINT "NAV_DATEREUNIONAN_FK" FOREIGN KEY ("ID") REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
  );

  CREATE INDEX "NAV_DATEREUNIONAN_ID_IDX" ON "NAV_DATEREUNIONAN" ("ID")
  
ALTER TABLE "FICHE_PRESENTATION_OEP" ADD nomInterlocuteurRef VARCHAR2(2000);

ALTER TABLE "FICHE_PRESENTATION_OEP" ADD fonctionInterlocuteurRef VARCHAR2(2000);

commit;