ALTER TABLE "FICHE_LOI" DROP (AUTEUR);
ALTER TABLE "FICHE_LOI" DROP (NUMEROJO);
ALTER TABLE "FICHE_LOI" DROP (NUMEROLOI);
DROP TABLE "FLOI_COAUTEUR";

ALTER TABLE "FICHE_LOI" ADD ministereResp NVARCHAR2(2000);
ALTER TABLE "FICHE_LOI" ADD dateProjet TIMESTAMP(6);
ALTER TABLE "FICHE_LOI" ADD dateSectionCe TIMESTAMP(6);
ALTER TABLE "FICHE_LOI" ADD numeroISA NVARCHAR2(2000);
ALTER TABLE "FICHE_LOI" ADD diffusion NVARCHAR2(2000);
ALTER TABLE "FICHE_LOI" ADD diffusionGenerale NVARCHAR2(2000);
ALTER TABLE "FICHE_LOI" ADD titreOfficiel NVARCHAR2(2000);

CREATE TABLE "FLOI_NOMCOMPLETCHARGESMISSIONS"
(
    "ID"  VARCHAR2(36 BYTE),
    "POS" NUMBER(10,0),
    "ITEM" NVARCHAR2(2000),
    CONSTRAINT "FLOI_CM_ID_HIERARCHY_FK" FOREIGN KEY ("ID")
    	REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
);

DROP TABLE "NAV_DATEREUNIONAN";
DROP TABLE "NAV_DATEREUNIONSE";
ALTER TABLE "NAVETTE" ADD resultatCMP NVARCHAR2(2000);
ALTER TABLE "NAVETTE" ADD sortAdoptionAN NVARCHAR2(2000);
ALTER TABLE "NAVETTE" ADD sortAdoptionSE NVARCHAR2(2000);
ALTER TABLE "NAVETTE" ADD dateAdoptionAN TIMESTAMP(6);
ALTER TABLE "NAVETTE" ADD dateAdoptionSE TIMESTAMP(6);
ALTER TABLE "NAVETTE" DROP (RESULTATAN);
ALTER TABLE "NAVETTE" DROP (RESULTATSE);
 
CREATE TABLE "NAV_DATECMP"
(
	"ID" VARCHAR2(36) NOT NULL ENABLE,
	"POS" NUMBER(10,0),
	"ITEM" TIMESTAMP (6),
 	CONSTRAINT "NAV_DATECMP_ID_HIERARCHY_FK" FOREIGN KEY ("ID")
  		REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
);

commit;