CREATE OR REPLACE VIEW V_AN_MESURES_DELAIS_DERNIER  AS
SELECT LOI_ID, LOI_DATEPROMULGATION, LOI_NATURETEXTE, MESURE_ID, MESURE_MINISTEREPILOTE,
CASE
  WHEN MES_DATEENTREEENVIGUEUR IS NULL 
  THEN (
    CASE WHEN DEC_DATEPUBLICATION < LOI_DATEPUBLICATION THEN 0
    ELSE (abs(extract(day FROM ((DEC_DATEPUBLICATION - LOI_DATEPUBLICATION) day TO second))) / 30) END
  )
  ELSE (
    CASE WHEN DEC_DATEPUBLICATION < MES_DATEENTREEENVIGUEUR THEN 0
    ELSE (abs(extract(day FROM ((DEC_DATEPUBLICATION - MES_DATEENTREEENVIGUEUR) day TO second))) / 30) END
  )
END DELAIS_EN_MOIS, DEC_DATEPUBLICATION
FROM (
  SELECT 
  TM_LOI.ID AS LOI_ID, 
  TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION,
  TM_LOI.DATEPUBLICATION AS LOI_DATEPUBLICATION,
  TM_LOI.NATURETEXTE AS LOI_NATURETEXTE,
  TM_MES.ID AS MESURE_ID,
  TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE,
  TM_MES.DATEENTREEENVIGUEUR AS MES_DATEENTREEENVIGUEUR,
  (SELECT MAX(MX_TM_DEC.DATEPUBLICATION)
                  FROM TEXM_MESUREIDS MX_TEXM, 
                  (TEXTE_MAITRE MX_TM_DEC INNER JOIN TEXM_DECRETIDS MX_TEXD   ON MX_TM_DEC.ID = MX_TEXD.ITEM)
                  WHERE TM_MES.ID = MX_TEXM.ITEM
                  AND   MX_TEXM.ID = MX_TM_DEC.ID 
                                  )as DEC_DATEPUBLICATION
  FROM 
  (TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = '1' ), 
  (TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM)
  WHERE TM_LOI.ID = TEXM.ID
  AND   TM_MES.TYPEMESURE = '1'
  AND   TM_MES.APPLICATIONRECU = '1'
);