CREATE UNIQUE INDEX "IDX_ACTCLINK_CREATED_INV" ON "ACTIONNABLE_CASE_LINK" ("CREATED" , "ID");
CREATE UNIQUE INDEX "IDX_DOSSIER_EPG_CREATED_INV" ON "DOSSIER_SOLON_EPG" ("CREATED" , "ID");
CREATE UNIQUE INDEX "IDX_DOSSIER_EPG_NOR_INV" ON "DOSSIER_SOLON_EPG" ("NUMERONOR" , "ID");
CREATE UNIQUE INDEX "IDX_DOSSIER_EPG_TYPE_ACTE_INV" ON "DOSSIER_SOLON_EPG" ("TYPEACTE" , "ID");

DROP INDEX DOSSIER_STAT_ID;
CREATE UNIQUE INDEX "DOSSIER_STAT_ID" ON "DOSSIER_SOLON_EPG" ("STATUT" , "ID");

CREATE UNIQUE INDEX "IDX_DOSSIER_EPG_DIR_ATT" ON "DOSSIER_SOLON_EPG" ( "ID", "DIRECTIONATTACHE");
CREATE UNIQUE INDEX "IDX_DOSSIER_EPG_MIN_ATT" ON "DOSSIER_SOLON_EPG" ( "ID", "MINISTEREATTACHE");

DROP INDEX "NXP_LOGS_ID_DATE";
drop index "NXP_LOGS_DATE";
CREATE UNIQUE INDEX "IDX_LOGS_CATEGORY" ON "NXP_LOGS" ( "LOG_EVENT_DATE", "LOG_EVENT_CATEGORY", "LOG_ID");


commit;
