-- Ajout des listes DOS_APPLICATIONLOIREFS et DOS_TRANSPOSITIONORDOREFS

CREATE TABLE "DOS_APPLICATIONLOIREFS"
  (
    "ID"  VARCHAR2(36 BYTE) NOT NULL ENABLE,
    "POS" NUMBER(10,0),
    "ITEM" NVARCHAR2(100),
    CONSTRAINT "DOS_AR__45E541BD_FK" FOREIGN KEY ("ID") REFERENCES "HIERARCHY" ("ID") ON
  DELETE CASCADE ENABLE
  );
  
  /
  
  CREATE TABLE "DOS_TRANSPOSITIONORDOREFS"
  (
    "ID"  VARCHAR2(36 BYTE) NOT NULL ENABLE,
    "POS" NUMBER(10,0),
    "ITEM" NVARCHAR2(100),
    CONSTRAINT "DOS_TR__45E541BD_FK" FOREIGN KEY ("ID") REFERENCES "HIERARCHY" ("ID") ON
  DELETE CASCADE ENABLE
  );

COMMIT;