ALTER TABLE FICHE_PRESENTATION_OEP ADD ministereRattachement2 VARCHAR2(4000 CHAR);
ALTER TABLE FICHE_PRESENTATION_OEP ADD ministereRattachement3 VARCHAR2(4000 CHAR);
ALTER TABLE FICHE_PRESENTATION_OEP ADD texteDuree VARCHAR2(4000 CHAR);
ALTER TABLE FICHE_PRESENTATION_OEP ADD texteOrganisme VARCHAR2(4000 CHAR);
ALTER TABLE FICHE_PRESENTATION_OEP ADD observation VARCHAR2(4000 CHAR);


commit;