//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace solonng_launcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("solonng_launcher.Resources.ApplicationMessages", typeof(ApplicationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr(e) de vouloir quitter SOLON-Edit ?.
        /// </summary>
        internal static string ConfirmApplicationClose {
            get {
                return ResourceManager.GetString("ConfirmApplicationClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il existe un ou plusieurs fichiers enregistrés et non déposés dans l’application EPG. 
        ///Etes-vous sûr(e) de vouloir quitter SOLON-Edit ?.
        /// </summary>
        internal static string ConfirmApplicationCloseWithPendingFiles {
            get {
                return ResourceManager.GetString("ConfirmApplicationCloseWithPendingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’application EPG n’est pas joignable ! Veuillez réessayer plus tard..
        /// </summary>
        internal static string DownloadErrorEpg2ngInaccessible {
            get {
                return ResourceManager.GetString("DownloadErrorEpg2ngInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier &quot;{0}&quot; n’existe pas..
        /// </summary>
        internal static string DownloadErrorFileNotFound {
            get {
                return ResourceManager.GetString("DownloadErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne disposez pas des droits d’édition du fichier {0}..
        /// </summary>
        internal static string DownloadErrorNotAuthorized {
            get {
                return ResourceManager.GetString("DownloadErrorNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez vous reconnecter a EPG2NG..
        /// </summary>
        internal static string DownloadErrorReconnectToEpg2ng {
            get {
                return ResourceManager.GetString("DownloadErrorReconnectToEpg2ng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’application EPG n’est pas joignable ! Veuillez réessayer plus tard..
        /// </summary>
        internal static string DownloadErrorUknownError {
            get {
                return ResourceManager.GetString("DownloadErrorUknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délai de lancement dépassé pour ouvrir le fichier {0}, merci de vérifier la configuration de votre poste de travail..
        /// </summary>
        internal static string ErrorOpeningFile {
            get {
                return ResourceManager.GetString("ErrorOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier &quot;{0}&quot; est en cours d&apos;édition. 
        ///
        ///Fermer l&apos;éditeur puis réessayer..
        /// </summary>
        internal static string FileBeingEditedCondirmation {
            get {
                return ResourceManager.GetString("FileBeingEditedCondirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier &quot;{0}&quot; est en cours d&apos;édition..
        /// </summary>
        internal static string FileBeingEditedNotification {
            get {
                return ResourceManager.GetString("FileBeingEditedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Après confirmation, le fichier {0} sera supprimé de SOLON-Edit et de votre poste local. 
        ///Les modifications apportées ne seront pas sauvegardées dans l’application EPG..
        /// </summary>
        internal static string FileDeleteConfirm {
            get {
                return ResourceManager.GetString("FileDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Le document {0} existe déjà. Voulez-vous conserver la version locale, télécharger une nouvelle version ou abandonner la demande d’édition ?.
        /// </summary>
        internal static string FileExistsConfirmation {
            get {
                return ResourceManager.GetString("FileExistsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier {0} n&apos;est pas pris en charge..
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;application ne supporte pas ce format d&apos;URL..
        /// </summary>
        internal static string MalFormedUrlError {
            get {
                return ResourceManager.GetString("MalFormedUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous allez être redirigé vers la page de connexion..
        /// </summary>
        internal static string RedirectToLoginPageNotification {
            get {
                return ResourceManager.GetString("RedirectToLoginPageNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La version de SOLON-Edit installée sur votre poste n’a pas pu être vérifiée..
        /// </summary>
        internal static string SolonEditVersionNotChecked {
            get {
                return ResourceManager.GetString("SolonEditVersionNotChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La version de SOLON-Edit que vous utilisez n’est pas la dernière version disponible.
        ///Veuillez contacter votre support informatique ministériel pour procéder à la mise à jour de SOLON-Edit, téléchargeable via l’espace utilisateur de l’application SOLON.
        /// </summary>
        internal static string SolonEditVersionWarning {
            get {
                return ResourceManager.GetString("SolonEditVersionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La validation du certificat SSL/TLS à echoué.
        /// </summary>
        internal static string SslTlsCertificateValidationFailed {
            get {
                return ResourceManager.GetString("SslTlsCertificateValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative de télechargement..
        /// </summary>
        internal static string StatutDownload {
            get {
                return ResourceManager.GetString("StatutDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En cours d&apos;édition..
        /// </summary>
        internal static string StatutEditing {
            get {
                return ResourceManager.GetString("StatutEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verrou retiré sur le dossier..
        /// </summary>
        internal static string StatutLocked {
            get {
                return ResourceManager.GetString("StatutLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative d&apos;ouverture du document..
        /// </summary>
        internal static string StatutNew {
            get {
                return ResourceManager.GetString("StatutNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document introuvable.
        /// </summary>
        internal static string StatutNotFound {
            get {
                return ResourceManager.GetString("StatutNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative d&apos;ouverture du document..
        /// </summary>
        internal static string StatutPreEdit {
            get {
                return ResourceManager.GetString("StatutPreEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente de dépôt..
        /// </summary>
        internal static string StatutSaved {
            get {
                return ResourceManager.GetString("StatutSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’application EPG n’est pas joignable ! Veuillez réessayer plus tard..
        /// </summary>
        internal static string UploadErrorEpg2ngInaccessible {
            get {
                return ResourceManager.GetString("UploadErrorEpg2ngInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier &quot;{0}&quot; n’existe pas..
        /// </summary>
        internal static string UploadErrorFileNotFound {
            get {
                return ResourceManager.GetString("UploadErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne disposez pas des droits d’édition du fichier {0}..
        /// </summary>
        internal static string UploadErrorNotAuthorized {
            get {
                return ResourceManager.GetString("UploadErrorNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez vous reconnecter a EPG2NG..
        /// </summary>
        internal static string UploadErrorReconnectToEpg2ng {
            get {
                return ResourceManager.GetString("UploadErrorReconnectToEpg2ng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’application EPG n’est pas joignable ! Veuillez réessayer plus tard..
        /// </summary>
        internal static string UploadErrorUknownError {
            get {
                return ResourceManager.GetString("UploadErrorUknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier {0} a bien été enregistré..
        /// </summary>
        internal static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }
    }
}
