//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace solonng_launcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("solonng_launcher.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt de l&apos;application suite au abandon de l&apos;utilisateur de l&apos;ouverture du fichier {0}, ID: {1}.
        /// </summary>
        internal static string AbortOpeningFileAndClosingApplicationInformation {
            get {
                return ResourceManager.GetString("AbortOpeningFileAndClosingApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AbortOpeningFileAndClosingApplicationOnErrorInformation {
            get {
                return ResourceManager.GetString("AbortOpeningFileAndClosingApplicationOnErrorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon de l&apos;utilisateur de l&apos;ouverture du fichier {0}, ID: {1}.
        /// </summary>
        internal static string AbortOpeningFileInformation {
            get {
                return ResourceManager.GetString("AbortOpeningFileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt de l&apos;application par l&apos;utilisateur.
        /// </summary>
        internal static string ApplicationClosedInfo {
            get {
                return ResourceManager.GetString("ApplicationClosedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt de l&apos;application vu qu&apos;une autre instance existe déjà..
        /// </summary>
        internal static string ApplicationClosedOtherInstanceExistsInfo {
            get {
                return ResourceManager.GetString("ApplicationClosedOtherInstanceExistsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrage de l&apos;application.
        /// </summary>
        internal static string ApplicationStarted {
            get {
                return ResourceManager.GetString("ApplicationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt de l&apos;application suite à une erreur..
        /// </summary>
        internal static string ApplicationStoppedDueToErrorInformation {
            get {
                return ResourceManager.GetString("ApplicationStoppedDueToErrorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL d&apos;authentification, Ajout des nouveaux headers au fichier des headers puis arrêt de l&apos;application..
        /// </summary>
        internal static string AuthUrlRefreshHeadersAndExit {
            get {
                return ResourceManager.GetString("AuthUrlRefreshHeadersAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du téléchargement du fichier {0}, ID: {1}, Code erreur HTTP: {2}. Message: {3}.
        /// </summary>
        internal static string DownloadErrorInfo {
            get {
                return ResourceManager.GetString("DownloadErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas le droit de faire l’action sur la données (métier)sur le  fichier {0}, ID: {1}.
        /// </summary>
        internal static string DownloadResponse_Forbidden {
            get {
                return ResourceManager.GetString("DownloadResponse.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le serveur distant est inaccessible..
        /// </summary>
        internal static string DownloadResponse_GatewayTimeout {
            get {
                return ResourceManager.GetString("DownloadResponse.GatewayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du téléchargement du fichier {0}, ID: {1}. L’application EPG n’est pas joignable..
        /// </summary>
        internal static string DownloadResponse_InternalServerError {
            get {
                return ResourceManager.GetString("DownloadResponse.InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier {0}, ID: {1} est introuvable..
        /// </summary>
        internal static string DownloadResponse_NotFound {
            get {
                return ResourceManager.GetString("DownloadResponse.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur en essayant de télécharger le fichier {0}, ID: {1}.
        /// </summary>
        internal static string DownloadResponse_UknownError {
            get {
                return ResourceManager.GetString("DownloadResponse.UknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du téléchargement du fichier {0}, ID: {1}.   Code erreur HTTP: {2}..
        /// </summary>
        internal static string DownloadResponse_Unauthorized {
            get {
                return ResourceManager.GetString("DownloadResponse.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délai de lancement dépassé pour ouvrir le fichier {0}, ID: {1}, merci de vérifier la configuration de votre poste de travail..
        /// </summary>
        internal static string ErrorOpeningFile {
            get {
                return ResourceManager.GetString("ErrorOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative de récupération de la version en ligne du fichier {0}, ID: {1} pour faire une comparaison avec la version locale.
        /// </summary>
        internal static string FetchingDistantFileInfo {
            get {
                return ResourceManager.GetString("FetchingDistantFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier {0}, ID: {1} en cours d&apos;édition.
        /// </summary>
        internal static string FileBeingEditedInfo {
            get {
                return ResourceManager.GetString("FileBeingEditedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Début du télechargement du fichier {0}, ID: {1}.
        /// </summary>
        internal static string FileDownloadStartedInfo {
            get {
                return ResourceManager.GetString("FileDownloadStartedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléchargé avec succès.
        /// </summary>
        internal static string FileDownloadSuccessInfo {
            get {
                return ResourceManager.GetString("FileDownloadSuccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier {0}, ID: {1} n&apos;est pas pris en charge..
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;url entrée est non valide.
        /// </summary>
        internal static string MalFormedUrlError {
            get {
                return ResourceManager.GetString("MalFormedUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur des paramètres dans URL, les paramètres suivants sont non fournis: {0} ou {1}.
        /// </summary>
        internal static string MissingParamsUrlError {
            get {
                return ResourceManager.GetString("MissingParamsUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur args == 0.
        /// </summary>
        internal static string NoArgsError {
            get {
                return ResourceManager.GetString("NoArgsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la notification à EPG que le fichier  {0}, ID: {1} est en cours d’édition. Code erreur Http {2}..
        /// </summary>
        internal static string NotifyFileBeingEditedLocallyError {
            get {
                return ResourceManager.GetString("NotifyFileBeingEditedLocallyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPG a été notifié que le fichier  {0}, ID: {1}  est en cours d’édition avec succès.
        /// </summary>
        internal static string NotifyFileBeingEditedLocallySuccess {
            get {
                return ResourceManager.GetString("NotifyFileBeingEditedLocallySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la notification à EPG que le fichier  {0}, ID: {1} n’est pas en cours d’édition. Code erreur Http {2}..
        /// </summary>
        internal static string NotifyFileNotBeingEditedError {
            get {
                return ResourceManager.GetString("NotifyFileNotBeingEditedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPG a été notifié que le fichier  {0}, ID: {1}  n’est pas en cours d’édition avec succès.
        /// </summary>
        internal static string NotifyFileNotBeingEditedSuccess {
            get {
                return ResourceManager.GetString("NotifyFileNotBeingEditedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouverture du fichier {0}, ID: {1} à éditer.
        /// </summary>
        internal static string OpeningFileToEditInfo {
            get {
                return ResourceManager.GetString("OpeningFileToEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la supression du fichier {0}, ID: {1}.
        /// </summary>
        internal static string RemovingFileError {
            get {
                return ResourceManager.GetString("RemovingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier {0}, ID: {1} est identique à celui sur le serveur. Supression du fichier..
        /// </summary>
        internal static string RemovingIdenticalFile {
            get {
                return ResourceManager.GetString("RemovingIdenticalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La validation du certificat SSL/TLS à echoué.
        /// </summary>
        internal static string SslTlsCertificateValidationFailed {
            get {
                return ResourceManager.GetString("SslTlsCertificateValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier est non identique à celui sur le serveur. Tentative de sauvegarde du fichier {0}, ID: {1}.
        /// </summary>
        internal static string StartUploadInfo {
            get {
                return ResourceManager.GetString("StartUploadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt de l&apos;application suite a la fin du traitement des différents fichiers.
        /// </summary>
        internal static string StopingAppNofileLeftInfo {
            get {
                return ResourceManager.GetString("StopingAppNofileLeftInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error lors de la resauvegarde du fichier {0}, ID: {1}. .
        /// </summary>
        internal static string UploadErrorInfo {
            get {
                return ResourceManager.GetString("UploadErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative de resauvegarde du fichier {0}, ID: {1}.
        /// </summary>
        internal static string UploadInfo {
            get {
                return ResourceManager.GetString("UploadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas le droit de faire l’action sur la données (métier) sur le  fichier {0}, ID: {1}.
        /// </summary>
        internal static string UploadResponse_Forbidden {
            get {
                return ResourceManager.GetString("UploadResponse.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’application EPG n’est pas joignable..
        /// </summary>
        internal static string UploadResponse_GatewayTimeout {
            get {
                return ResourceManager.GetString("UploadResponse.GatewayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;upload du fichier {0}, ID: {1}. Code erreur Http {2}..
        /// </summary>
        internal static string UploadResponse_InternalServerError {
            get {
                return ResourceManager.GetString("UploadResponse.InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier {0}, ID: {1} est introuvable.
        /// </summary>
        internal static string UploadResponse_NotFound {
            get {
                return ResourceManager.GetString("UploadResponse.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;upload du fichier {0}, ID: {1}..
        /// </summary>
        internal static string UploadResponse_UknownError {
            get {
                return ResourceManager.GetString("UploadResponse.UknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;upload du fichier {0}, ID: {1}. L’application EPG n’est pas joignable.
        /// </summary>
        internal static string UploadResponse_Unauthorized {
            get {
                return ResourceManager.GetString("UploadResponse.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le dépôt du fichier {0}, ID: {1} est effectué avec succès..
        /// </summary>
        internal static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }
    }
}
