package fr.dila.solonepg.api.constant;

import fr.dila.st.api.constant.STSchemaConstant;

public class TexteMaitreConstants {

	public static final String	TEXTE_MAITRE_SCHEMA					= "texte_maitre";
	public static final String	TEXTE_MAITRE_PREFIX					= "texm";

	// lock du document
	public static final String	DOC_LOCK_DATE						= "docLockDate";
	public static final String	DOC_LOCK_USER						= "docLockUser";

	public static final String	NUMERO_DEPOT_LOCKED					= "numeroDepotLocked";
	public static final String	DATE_DEPOT_LOCKED					= "dateDepotLocked";
	public static final String	CHAMBRE_DEPOT_LOCKED				= "chambreDepotLocked";
	public static final String	DATE_EXAMEN_CE_LOCKED				= "dateExamenCELocked";
	public static final String	TYPE_ACTE_LOCKED					= "typeActeLocked";
	public static final String	SECTION_CE_LOCKED					= "sectionCELocked";
	public static final String	RAPPORTEUR_CE_LOCKED				= "rapporteurCELocked";
	public static final String	NUMERO_PAGE_LOCKED					= "numeroPageLocked";
	public static final String	NUMERO_JO_PUBLICATION_LOCKED		= "numeroJOPublicationLocked";
	public static final String	DATE_SORTIE_CE_LOCKED				= "dateSortieCELocked";
	public static final String	DATE_SECTION_CE_LOCKED				= "dateSectionCELocked";
	public static final String	DATE_PASSAGE_CM_LOCKED				= "datePassageCMLocked";
	public static final String	DATE_SAISINE_CE_LOCKED				= "dateSaisineCELocked";
	public static final String	OBJET_LOCKED						= "objetLocked";
	public static final String	NUMERO_LOCKED						= "numeroLocked";
	public static final String	COMMISSION_SENAT_LOCKED				= "commissionSenatLocked";
	public static final String	COMMISSION_ASS_NATIONALE_LOCKED		= "commissionAssNationaleLocked";
	public static final String	PROCEDURE_VOTE_LOCKED				= "procedureVoteLocked";
	public static final String	NATURE_TEXTE_LOCKED					= "natureTexteLocked";
	public static final String	LEGISLATURE_PUBLICATION_LOCKED		= "legislaturePublicationLocked";
	public static final String	TITRE_OFFICIEL_LOCKED				= "titreOfficielLocked";
	public static final String	DATE_PROMULGATION_LOCKED			= "datePromulgationLocked";
	public static final String	DATE_PUBLICATION_LOCKED				= "datePublicationLocked";
	public static final String	APPLICATION_DIRECTE_LOCKED			= "applicationDirecteLocked";
	public static final String	CHAMP_LIBRE_LOCKED					= "champLibreLocked";
	public static final String	DATE_ENTREE_EN_VIGUEUR_LOCKED		= "dateEntreeEnVigueurLocked";
	public static final String	NUMERO_INTERNE_LOCKED				= "numeroInterneLocked";
	public static final String	MINISTERE_PILOTE_LOCKED				= "ministerePiloteLocked";
	public static final String	TITRE_ACTE_LOCKED					= "titreActeLocked";
	public static final String	LOI_RATIFICATION_IDS				= "loiRatificationIds";
	public static final String	MESURES_APPLICATIVES_IDS			= "mesuresApplicativesIds";
	public static final String	DOSSIERS_NOR						= "dossiersNor";
	public static final String	TRANSPOSITION_IDS					= "transpositionIds";
	public static final String	DECRET_IDS							= "decretIds";
	public static final String	HAS_VALIDATION						= "hasvalidation";
	public static final String	MESURE_IDS							= "mesureIds";
	public static final String	HABILITATION_IDS					= "habilitationIds";
	public static final String	ORDONNANCE_IDS						= "ordonnanceIds";
	public static final String	ID_DOSSIER							= "idDossier";
	public static final String	COMMISSION_SENAT					= "commissionSenat";
	public static final String	COMMISSION_ASS_NATIONALE			= "commissionAssNationale";
	public static final String	PROCEDURE_VOTE						= "procedureVote";
	public static final String	NATURE_TEXTE						= "natureTexte";
	public static final String	DATE_SIGNATURE						= "dateSignature";
	public static final String	NUMEROS_TEXTES						= "numerosTextes";
	public static final String	REFERENCE_AVIS_CE					= "referenceAvisCE";
	public static final String	ACHEVEE								= "achevee";
	public static final String	DATE_PROCHAIN_TAB_AFFICHAGE			= "dateProchainTabAffichage";
	public static final String	TAB_AFFICHAGE_MARCHE_INT			= "tabAffichageMarcheInt";
	public static final String	DATE_ECHEANCE						= "dateEcheance";
	public static final String	DATE_DIRECTIVE						= "dateDirective";
	public static final String	NUMERO_TEXTE_PUBLIE					= "numeroTextePublie";
	public static final String	ETAPE_SOLON							= "etapeSolon";
	public static final String	INTITULE							= "intitule";
	public static final String	NUMERO_DEPOT						= "numeroDepot";
	public static final String	DATE_DEPOT							= "dateDepot";
	public static final String	CHAMBRE_DEPOT						= "chambreDepot";
	public static final String	DATE_EXAMEN_CM						= "dateExamenCM";
	public static final String	DATE_EXAMEN_CE						= "dateExamenCE";
	public static final String	DATE_LIMITE_PUBLICATION				= "dateLimitePublication";
	public static final String	DATE_LIMITE_DEPOT					= "dateLimiteDepot";
	public static final String	TERME_DEPOT							= "termeDepot";
	public static final String	DATE_SAISINE_CE						= "dateSaisineCE";
	public static final String	NUMERO_NOR							= "numeroNor";
	public static final String	DATE_CIRCULATION_COMPTE_RENDU		= "dateCirculationCompteRendu";
	public static final String	DATE_REUNION_PROGRAMMATION			= "dateReunionProgrammation";
	public static final String	MESURE_APPLICATION					= "mesureApplication";
	public static final String	RESPONSABLE_AMENDEMENT				= "responsableAmendement";
	public static final String	AMENDEMENT							= "amendement";
	public static final String	NUMERO_QUESTION						= "numeroQuestion";
	public static final String	APPLICATION_RECU					= "applicationRecu";
	public static final String	DIFFERE								= "differe";
	public static final String	DATE_PASSAGE_CM						= "datePassageCM";
	public static final String	POLE_CHARGE_MISSION					= "poleChargeMission";
	public static final String	APPLICATION_LOI						= "applicationLoi";
	public static final String	FROM_AMENDEMENT						= "fromAmendement";
	public static final String	DATE_OBJECTIF_PUBLICATION			= "dateObjectifPublication";
	public static final String	CALENDRIER_CONSULTATIONS_HCE		= "calendrierConsultationsHCE";
	public static final String	CONSULTATIONS_HCE					= "consultationsHCE";
	public static final String	DATE_DISPONIBILITE_AVANT_PROJET		= "dateDisponibiliteAvantProjet";
	public static final String	DIRECTION_RESPONSABLE				= "directionResponsable";
	public static final String	TYPE_MESURE							= "typeMesure";
	public static final String	BASE_LEGALE							= "baseLegale";
	public static final String	CODE_MODIFIE						= "codeModifie";
	public static final String	REFERENCE_DISPOSITION_RATIFICATION	= "referenceDispositionRatification";
	public static final String	DELAI_PUBLICATION					= "delaiPublication";
	public static final String	NUMERO_PAGE							= "numeroPage";
	public static final String	NUMERO_JO_PUBLICATION				= "numeroJOPublication";
	public static final String	RECEPTION_AVIS_CE					= "receptionAvisCE";
	public static final String	RAPPORTEUR_CE						= "rapporteurCE";
	public static final String	DATE_SORTIE_CE						= "dateSortieCE";
	public static final String	DATE_SECTION_CE						= "dateSectionCE";
	public static final String	SECTION_CE							= "sectionCE";
	public static final String	TYPE_ACTE							= "typeActe";
	public static final String	CODIFICATION						= "codification";
	public static final String	LEGISLATURE							= "legislature";
	public static final String	DATE_PREVISIONNELLE_CM				= "datePrevisionnelleCM";
	public static final String	DATE_PREVISIONNELLE_SAISINE_CE		= "datePrevisionnelleSaisineCE";
	public static final String	CONVENTION_DEPOT					= "conventionDepot";
	public static final String	DATE_TERME							= "dateTerme";
	public static final String	CONVENTION							= "convention";
	public static final String	TYPE_HABILITATION					= "typeHabilitation";
	public static final String	OBJET_RIM							= "objetRIM";
	public static final String	ARTICLE								= "article";
	public static final String	NUMERO_ORDRE						= "numeroOrdre";
	public static final String	RENVOI_DECRET						= "renvoiDecret";
	public static final String	NUMERO								= "numero";
	public static final String	DISPOSITION_HABILITATION			= "dispositionHabilitation";
	public static final String	OBJET								= "objet";
	public static final String	LEGISLATURE_PUBLICATION				= "legislaturePublication";
	public static final String	TITRE_OFFICIEL						= "titreOfficiel";
	public static final String	DATE_PROMULGATION					= "datePromulgation";
	public static final String	DATE_PUBLICATION					= "datePublication";
	public static final String	APPLICATION_DIRECTE					= "applicationDirecte";
	public static final String	CHAMP_LIBRE							= "champLibre";
	public static final String	OBSERVATION							= "observation";
	public static final String	DATE_ENTREE_EN_VIGUEUR				= "dateEntreeEnVigueur";
	public static final String	MOT_CLE								= "motCle";
	public static final String	NUMERO_INTERNE						= "numeroInterne";
	public static final String	MINISTERE_PILOTE					= "ministerePilote";
	public static final String	TITRE_ACTE							= "titreActe";
	public static final String	LIEN_JORF_LEGIFRANCE				= "lienJORFLegifrance";
	public static final String	RATIFIE								= "ratifie";
	public static final String	DATE_DEPOT_RATIFICATION				= "dateDepotRatification";
	public static final String	NOR_LOI_RATIFICATION				= "norLoiRatification";
	public static final String	DISPO_ETUDE_IMPACT					= "dispoEtudeImpact";
	public static final String	ETUDE_IMPACT						= "etudeImpact";
	public static final String	DATE_PJL							= "datePJL";
	public static final String	DEGRE_PRIORITE						= "degrePriorite";
	public static final String	NOR_DECRET							= "norDecret";
	public static final String	PUBLICATION							= "publication";
	public static final String	AUTORISATION_RATIFICATION			= "autorisationRatification";
	public static final String	THEMATIQUE							= "thematique";
	public static final String	ORGANISATION						= "organisation";
	public static final String	CATEGORIE							= "categorie";
	public static final String	DATE_CREATION						= "dateCreation";
	public static final String	DATE_TRANSPOSITION_EFFECTIVE		= "dateTranspositionEffective";
	public static final String	DIRECTIVE_ETAT						= "directiveEtat";
	public static final String	DATE_MISE_APPLICATION				= "dateMiseApplication";
	public static final String	IDS_INVALIDATED						= "idsInvalidated";
	public static final String	COMMUNICATION_MINISTERIELLE			= "communicationMinisterielle";
	public static final String DATE_MODIFICATION = "dateModification";
	public static final String DATE_INJECTION = "dateInjection";

	public static final String	ID									= STSchemaConstant.ECM_UUID_PROPERTY;

	private TexteMaitreConstants() {
		// private empty constructor
	}

}
