
Insert into INSTITUTION (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,FUNCTION_READ) values ('ASSEMBLEE_NATIONALE',null,null,null,'Assemblée nationale',0,null,null);

Insert into INSTITUTION (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,FUNCTION_READ) values ('DILA',null,null,null,'DILA',0,null,null);

Insert into INSTITUTION (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,FUNCTION_READ) values ('GOUVERNEMENT',null,null,null,'Gouvernement',0,null,null);

Insert into INSTITUTION (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,FUNCTION_READ) values ('SENAT',null,null,null,'Sénat',0,null,null);

Insert into UNITE_STRUCTURELLE (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,ID_PARENT_ENTITE,ID_PARENT_UNITE,ID_PARENT_INSTITUTION,TYPE,FUNCTION_READ,NOR_DIRECTION) values ('mineconomie',null,to_timestamp('24/08/07 02:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'Ministère de l''économie',0,null,null,null,'GOUVERNEMENT','UST',null,null);

Insert into UNITE_STRUCTURELLE (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,ID_PARENT_ENTITE,ID_PARENT_UNITE,ID_PARENT_INSTITUTION,TYPE,FUNCTION_READ,NOR_DIRECTION) values ('premierministre',null,to_timestamp('24/08/07 02:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'Premier ministre',0,null,null,null,'GOUVERNEMENT','UST',null,null);



Insert into POSTE (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,ID_PARENT_ENTITE,ID_PARENT_UNITE,ID_PARENT_INSTITUTION,CHARGE_MISSION_SGG,POSTE_BDC,SUPERVISEUR_SGG,CONSEILLER_PM,POSTE_WS,WS_URL,WS_LOGIN,WS_MDP,WS_CLE,MEMBRES,FUNCTION_READ) values ('bdc-economie',null,to_timestamp('15/06/11 02:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'BDC économie',0,null,null,'mineconomie',null,0,0,null,0,0,null,null,null,'99991231000000Z','bdc;contributeur',null);

Insert into POSTE (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,ID_PARENT_ENTITE,ID_PARENT_UNITE,ID_PARENT_INSTITUTION,CHARGE_MISSION_SGG,POSTE_BDC,SUPERVISEUR_SGG,CONSEILLER_PM,POSTE_WS,WS_URL,WS_LOGIN,WS_MDP,WS_CLE,MEMBRES,FUNCTION_READ) values ('sgg',null,to_timestamp('15/06/11 02:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'SGG',0,null,null,'premierministre',null,0,0,null,0,0,null,null,null,'99991231000000Z','adminsgg',null);

Insert into POSTE (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,ID_PARENT_ENTITE,ID_PARENT_UNITE,ID_PARENT_INSTITUTION,CHARGE_MISSION_SGG,POSTE_BDC,SUPERVISEUR_SGG,CONSEILLER_PM,POSTE_WS,WS_URL,WS_LOGIN,WS_MDP,WS_CLE,MEMBRES,FUNCTION_READ) values ('technique-an',null,to_timestamp('15/06/11 02:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'Poste technique AN',0,null,null,null,'ASSEMBLEE_NATIONALE',0,0,null,0,0,null,null,null,'99991231000000Z','adminan;an;ws-an',null);

Insert into POSTE (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,ID_PARENT_ENTITE,ID_PARENT_UNITE,ID_PARENT_INSTITUTION,CHARGE_MISSION_SGG,POSTE_BDC,SUPERVISEUR_SGG,CONSEILLER_PM,POSTE_WS,WS_URL,WS_LOGIN,WS_MDP,WS_CLE,MEMBRES,FUNCTION_READ) values ('technique-dila',null,to_timestamp('15/06/11 02:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'Poste technique DILA',0,null,null,null,'DILA',0,0,null,0,0,null,null,null,'99991231000000Z','admindila;dila;ws-dila',null);

Insert into POSTE (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,ID_PARENT_ENTITE,ID_PARENT_UNITE,ID_PARENT_INSTITUTION,CHARGE_MISSION_SGG,POSTE_BDC,SUPERVISEUR_SGG,CONSEILLER_PM,POSTE_WS,WS_URL,WS_LOGIN,WS_MDP,WS_CLE,MEMBRES,FUNCTION_READ) values ('technique-gouvernement',null,to_timestamp('15/06/11 02:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'Poste technique gouvernement',0,null,null,null,'GOUVERNEMENT',0,0,null,0,0,null,null,null,'99991231000000Z','admingouvernement;usertest2;ws-gouvernement',null);

Insert into POSTE (ID_ORGANIGRAMME,DATE_FIN,DATE_DEBUT,DATE_VERROU,LABEL,DELETED,UTILISATEUR_VERROU,ID_PARENT_ENTITE,ID_PARENT_UNITE,ID_PARENT_INSTITUTION,CHARGE_MISSION_SGG,POSTE_BDC,SUPERVISEUR_SGG,CONSEILLER_PM,POSTE_WS,WS_URL,WS_LOGIN,WS_MDP,WS_CLE,MEMBRES,FUNCTION_READ) values ('technique-senat',null,to_timestamp('15/06/11 02:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,'Poste technique sénat',0,null,null,null,'SENAT',0,0,null,0,0,null,null,null,'99991231000000Z','adminsenat;senat;ws-senat',null);

commit;



