CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_PUB  AS
SELECT '0' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION, 
  DOS.MINISTERERESP, TO_CHAR (DOS.DATEPRECISEEPUBLICATION, 'DD/MM/YYYY') AS DATEPRECISEPUB,
  NVL(MP."MODE",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, RETOUR_DILA RD, VOC_PUBLICATION_DELAI VPD, MODE_PARUTION MP
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND RD.MODEPARUTION =  MP.id(+)
AND DOS.DELAIPUBLICATION = VPD."id" (+)
AND RD.ID = DOS.ID
AND EXISTS ( 	SELECT 1 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
        		AND   ROU.DATEFINETAPE IS NULL
				AND   ROU.TYPE IN (13) )
AND (SELECT vp.vppos
        FROM DOS_VECTEURPUBLICATION VEC, vecteur_publication vp
        WHERE VEC.ID = DOS.ID
        AND VEC.ITEM = vp.id) = 1 -- 1 = Journal officiel
UNION
SELECT '1' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, TP.PUBLICATIONDELAI DELAIPUBLICATION, DOS.MINISTERERESP,
  TP.PUBLICATIONMODEPUBLICATION MODEPARUTION, TO_CHAR (TP.PUBLICATIONDATEDEMANDE, 'DD/MM/YYYY')  AS DATEPRECISEPUB,
  NVL(MP."MODE",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, MODE_PARUTION MP, VOC_PUBLICATION_DELAI VPD, VECTEUR_PUBLICATION VEC --RETOUR_DILA RD, 
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
AND TP.PUBLICATIONMODEPUBLICATION = MP."ID" (+)
AND TP.PUBLICATIONDELAI = VPD."id" (+)
AND TP.PUBLICATIONNOMPUBLICATION = VEC.ID
and VEC.vppos = 1 -- 1 = Journal Officiel
AND DOS.ID = TP.ID;

