-- Redimension du champ de dénormalisation related_document sur FILE_SOLON_EPG

ALTER TABLE FILE_SOLON_EPG RENAME COLUMN RELATEDDOCUMENT TO RELATEDDOCUMENT_OLD;
ALTER TABLE FILE_SOLON_EPG ADD (RELATEDDOCUMENT VARCHAR2(36 BYTE));
UPDATE FILE_SOLON_EPG SET RELATEDDOCUMENT = RELATEDDOCUMENT_OLD;

COMMIT;

ALTER TABLE FILE_SOLON_EPG DROP (RELATEDDOCUMENT_OLD);
COMMIT;

-- Redimension du champ de dénormalisation casedocumentid sur CASE_LINK

ALTER TABLE CASE_LINK RENAME COLUMN CASEDOCUMENTID TO CASEDOCUMENTID_OLD;
ALTER TABLE CASE_LINK ADD (CASEDOCUMENTID VARCHAR2(36 BYTE));
UPDATE CASE_LINK SET CASEDOCUMENTID = CASEDOCUMENTID_OLD;

COMMIT;

ALTER TABLE CASE_LINK DROP (CASEDOCUMENTID_OLD);
COMMIT;


-- Redimension du champ de dénormalisation documentrouteid sur ROUTING_TASK

ALTER TABLE ROUTING_TASK RENAME COLUMN DOCUMENTROUTEID TO DOCUMENTROUTEID_OLD;
ALTER TABLE ROUTING_TASK ADD (DOCUMENTROUTEID VARCHAR2(36 BYTE));
UPDATE ROUTING_TASK SET DOCUMENTROUTEID = DOCUMENTROUTEID_OLD;

COMMIT;

ALTER TABLE ROUTING_TASK DROP (DOCUMENTROUTEID_OLD);
COMMIT;





