ALTER TABLE FICHE_PRESENTATION_OEP ADD IDCOMMUN VARCHAR2(100 CHAR);
ALTER TABLE FICHE_PRESENTATION_OEP ADD COMMENTAIRE VARCHAR2(4000 CHAR);
ALTER TABLE FICHE_PRESENTATION_OEP ADD NBDEPUTES NUMBER(19,0);
ALTER TABLE FICHE_PRESENTATION_OEP ADD NBSENATEURS NUMBER(19,0);
ALTER TABLE FICHE_PRESENTATION_DECRET ADD ACTIF NUMBER(1,0) DEFAULT 0;
ALTER TABLE NAVETTE ADD URL NVARCHAR2(2000);
ALTER TABLE NAVETTE ADD IDFICHE VARCHAR2(36);


CREATE TABLE REPRESENTANT_AVI
  (
    ID VARCHAR2(36) NOT NULL ,
    IDFPAN VARCHAR2(36) ,
    DATEDEBUT TIMESTAMP(6) ,
    DATEFIN TIMESTAMP(6) ,
    DATEAUDITIONAN TIMESTAMP(6) ,
    DATEAUDITIONSE TIMESTAMP(6) ,
    NOMINE NVARCHAR2(200) ,
    CONSTRAINT REPRESENTANT_AVI_PK PRIMARY KEY ( ID ) ENABLE,
    CONSTRAINT REPR_AVI_FK FOREIGN KEY (ID) REFERENCES HIERARCHY (ID) ON DELETE CASCADE ENABLE
  );
  
DROP TABLE FICHE_PRESENTATION_AN;

CREATE TABLE FICHE_PRESENTATION_AVI
  (
    "ID" VARCHAR2(36) NOT NULL ENABLE,
    "IDORGANISMEEPP" NVARCHAR2(200),
    "NOMORGANISME" NVARCHAR2(2000),
    "DATE" TIMESTAMP (6),
    "IDDOSSIER" VARCHAR2(36),
    "BASELEGALE" NVARCHAR2(2000),
    CONSTRAINT "FICHE_PRESENTATION_AVI_PK" PRIMARY KEY ("ID") ENABLE,
    CONSTRAINT "FICH_AVI_FK" FOREIGN KEY ("ID") REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
  );
  
CREATE TABLE PARAMETRAGE_MGPP
  (
    "ID" VARCHAR2(36 BYTE) NOT NULL ENABLE,
    "URLEPP" NVARCHAR2(2000),
    "LOGINEPP" NVARCHAR2(200),
    "PASSEPP"  NVARCHAR2(200),
    CONSTRAINT "PARAMETRAGE_MGPP_PK" PRIMARY KEY ("ID") ENABLE,
    CONSTRAINT "PARAMETRAGE_MGPP_FK" FOREIGN KEY ("ID") REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
  );
  
  