ALTER TABLE DOSSIER_SOLON_EPG ADD "BASELEGALENATURETEXTE" NVARCHAR2(2000);
ALTER TABLE DOSSIER_SOLON_EPG ADD "BASELEGALENUMEROTEXTE" NVARCHAR2(2000);
ALTER TABLE DOSSIER_SOLON_EPG ADD "BASELEGALEDATE" TIMESTAMP (6); 

commit;