CREATE OR REPLACE VIEW V_AN_MESURES_RECU_APPLICATION  AS
SELECT
TM_LOI.ID AS LOI_ID,
TM_LOI.MINISTEREPILOTE AS LOI_MINISTERERESP,
TM_LOI.DATEPUBLICATION AS LOI_DATEPUBLICATION,
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION,
TM_LOI.DATEENTREEENVIGUEUR AS LOI_DATEENTREEENVIGUEUR,
TM_LOI.NATURETEXTE AS LOI_NATURETEXTE,
TM_LOI.PROCEDUREVOTE AS LOI_PROCEDUREVOTE,
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE,
TM_DEC.ID AS DECRET_ID,
TM_DEC.DATEPUBLICATION AS DECRET_DATEPUBLICATION,
TM_MES.DATEMISEAPPLICATION AS MES_DATEMISEAPPLICATION,
TM_MES.DATEENTREEENVIGUEUR as MES_DATEENTREEENVIGUEUR,
TM_MES.DIFFERE as MES_DIFFERE
FROM
(TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = '1' ),
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM),
(TEXTE_MAITRE TM_DEC INNER JOIN TEXM_DECRETIDS TEXD   ON TM_DEC.ID = TEXD.ITEM)
WHERE TM_LOI.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU = '1'
AND   TM_MES.ID = TEXD.ID
AND   TM_DEC.DATEPUBLICATION = (SELECT MAX(MX_TM_DEC.DATEPUBLICATION)
        FROM TEXM_MESUREIDS MX_TEXM,
        (TEXTE_MAITRE MX_TM_DEC INNER JOIN TEXM_DECRETIDS MX_TEXD   ON MX_TM_DEC.ID = MX_TEXD.ITEM)
        WHERE TM_MES.ID = MX_TEXD.ID
        AND   MX_TEXM.ID = MX_TM_DEC.ID
                                );
commit;