--------------------------------------------------------
--  DDL for View V_AN_MESURES_LEGISLATIVE
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_AN_MESURES_LEGISLATIVE" ("MOTCLE", "NUMEROLOI", "TITREOFFICIEL", "NATURETEXTE", "PROCEDUREVOTE", "DATEPUBLICATION", "LEGISLATUREPUBLICATION", "NUMEROORDRE", "ARTICLE", "CODEMODIFIE", "BASELEGALE", "OBJETRIM", "MINISTEREPILOTE", "DIRECTIONRESPONSABLE", "CONSULTATIONSHCE", "CALENDRIERCONSULTATIONSHCE", "DATEPREVISIONNELLESAISINECE", "DATEENTREEENVIGUEUR", "DATEOBJECTIFPUBLICATION", "TYPEMESUREID", "TYPEMESURE", "OBSERVATION", "NUMERONOR", "DECRET_TITREOFFICIEL", "TYPACTE", "DATESAISINECE", "DATESORTIECE", "DECRET_DATEPUBLICATION", "DATEMISEAPPLICATION", "MES_DATEENTREEENVIGUEUR", "APPLICATIONRECU", "LOI_DATEPROMULGATION", "MES_DIFFERE") AS 
  SELECT
TM_LOI.MOTCLE,
TM_LOI.NUMERO AS NUMEROLOI,
TM_LOI.TITREOFFICIEL,
TM_LOI.NATURETEXTE AS NATURETEXTE,
TM_LOI.PROCEDUREVOTE AS PROCEDUREVOTE,
TM_LOI.DATEPUBLICATION,
TM_LOI.LEGISLATUREPUBLICATION,
TM_MES.NUMEROORDRE,
TM_MES.ARTICLE,
TM_MES.CODEMODIFIE,
TM_MES.BASELEGALE,
TM_MES.OBJETRIM,
TM_MES.MINISTEREPILOTE,
TM_MES.DIRECTIONRESPONSABLE,
TM_MES.CONSULTATIONSHCE,
TM_MES.CALENDRIERCONSULTATIONSHCE,
TM_MES.DATEPREVISIONNELLESAISINECE,
TM_MES.DATEENTREEENVIGUEUR,
TM_MES.DATEOBJECTIFPUBLICATION DATEOBJECTIFPUBLICATION,
TM_MES.TYPEMESURE           AS TYPEMESUREID,
NVL(VOC_TM_MES."label", '') AS TYPEMESURE,
TM_MES.OBSERVATION,
TM_DEC.NUMERONOR,
TM_DEC.TITREOFFICIEL DECRET_TITREOFFICIEL,
NVL(VOC_TM_DEC."label",' ') AS TYPACTE,
TM_DEC.DATESAISINECE,
TM_DEC.DATESORTIECE,
TM_DEC.DATEPUBLICATION,
TM_MES.DATEMISEAPPLICATION,
TM_MES.DATEENTREEENVIGUEUR as MES_DATEENTREEENVIGUEUR,
TM_MES.APPLICATIONRECU,
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION,
TM_MES.DIFFERE as MES_DIFFERE
FROM TEXTE_MAITRE TM_LOI, TEXM_MESUREIDS TME, ACTIVITE_NORMATIVE AN, TEXTE_MAITRE TM_MES
LEFT JOIN VOC_TYPE_MESURE VOC_TM_MES ON TM_MES.TYPEMESURE = VOC_TM_MES."id"
LEFT JOIN TEXM_DECRETIDS TD ON TD.ID = TM_MES.ID
LEFT JOIN TEXTE_MAITRE TM_DEC ON TM_DEC.ID = TD.ITEM
LEFT JOIN VOC_ACTE_TYPE VOC_TM_DEC ON TM_DEC.TYPEACTE = VOC_TM_DEC."id"
WHERE TM_LOI.ID = AN.ID
AND AN.APPLICATIONLOI = '1'
AND TM_MES.TYPEMESURE IN ('1','4' ,'6')
AND TME.ID = AN.ID
AND TM_MES.ID = TME.ITEM;

--------------------------------------------------------
--  DDL for View V_AN_MESURES_PREVISIONNELLE
--------------------------------------------------------

  CREATE OR REPLACE VIEW "V_AN_MESURES_PREVISIONNELLE" ("NUMEROLOI", "TITREOFFICIEL", "NUMEROORDRE", "ARTICLE", "BASELEGALE", "OBJETRIM", "MINISTEREPILOTE", "DIRECTIONRESPONSABLE", "CONSULTATIONSHCE", "CALENDRIERCONSULTATIONSHCE", "DATEPREVISIONNELLESAISINECE", "DATEOBJECTIFPUBLICATION", "DATESAISINECE", "DATESORTIECE", "OBSERVATION", "NUMERONOR", "DECRET_TITREOFFICIEL", "TYPACTE", "DATEPUBLICATION", "DATEMISEAPPLICATION", "DATEPUBLICATIONLOI", "APPLICATIONRECU") AS 
  SELECT
TM_LOI.NUMERO AS NUMEROLOI,
TM_LOI.TITREOFFICIEL,
TM_MES.NUMEROORDRE,
TM_MES.ARTICLE,
TM_MES.BASELEGALE,
TM_MES.OBJETRIM,
TM_MES.MINISTEREPILOTE,
TM_MES.DIRECTIONRESPONSABLE,
TM_MES.CONSULTATIONSHCE,
TM_MES.CALENDRIERCONSULTATIONSHCE,
TM_MES.DATEPREVISIONNELLESAISINECE,
TM_MES.DATEOBJECTIFPUBLICATION,
TM_DEC.DATESAISINECE,
TM_DEC.DATESORTIECE,
TM_MES.OBSERVATION,
TM_DEC.NUMERONOR,
TM_DEC.TITREOFFICIEL DECRET_TITREOFFICIEL,
NVL(VOC_TM_DEC."label", '') AS TYPACTE,
TM_DEC.DATEPUBLICATION,
TM_MES.DATEMISEAPPLICATION,
TM_LOI.DATEPUBLICATION DATEPUBLICATIONLOI,
TM_MES.APPLICATIONRECU
FROM TEXTE_MAITRE TM_LOI, TEXM_MESUREIDS TME, ACTIVITE_NORMATIVE AN, TEXTE_MAITRE TM_MES
LEFT JOIN TEXM_DECRETIDS TD ON TD.ID = TM_MES.ID
LEFT JOIN TEXTE_MAITRE TM_DEC ON TM_DEC.ID = TD.ITEM
LEFT JOIN VOC_ACTE_TYPE VOC_TM_DEC ON TM_DEC.TYPEACTE = VOC_TM_DEC."id"
WHERE TM_LOI.ID = AN.ID
AND AN.APPLICATIONLOI = '1'
AND TM_MES.TYPEMESURE = '1'
AND TME.ID = AN.ID
AND TM_MES.ID = TME.ITEM
AND TM_MES.DATEOBJECTIFPUBLICATION < SYSDATE;


--------------------------------------------------------
--  DDL for View V_AN_HAB_ORD_LOI
--------------------------------------------------------

CREATE OR REPLACE VIEW "V_AN_HAB_ORD_LOI" ("HAB_DATEPUBLICATION","RAC_NUMERONOR", "RAC_TITREACTE", "RAC_DATEPUBLICATION", "HAB_NUMEROORDRE", "HAB_ARTICLE", "HAB_OBJETRIM", "HAB_TYPEHABILITATION", "HAB_MINISTEREPILOTE", "HAB_DATETERME", "HAB_CONVENTIONDEPOT", "HAB_DATESAISINECE", "HAB_DATEPREVISIONNELLECM", "HAB_OBSERVATION", "HAB_CODIFICATION", "HAB_LEGISLATURE", "ORD_DISPOSITIONHABILITATION", "ORD_NUMERONOR", "ORD_MINISTEREPILOTE", "ORD_DATESAISINECE", "ORD_DATEPREVISIONNELLECM", "ORD_DATEPUBLICATION", "ORD_TITREOFFICIEL", "ORD_CONVENTIONDEPOT", "ORD_DATELIMITEDEPOT", "LRA_NUMERONOR", "LRA_TITREACTE", "LRA_DATESAISINECE", "LRA_DATEEXAMENCE", "LRA_SECTIONCE", "LRA_DATEEXAMENCM", "LRA_CHAMBREDEPOT", "LRA_DATEDEPOT", "LRA_NUMERODEPOT", "LRA_TITREOFFICIEL", "LRA_DATEPUBLICATION", "LRA_NUMEROJOPUBLICATION") AS 
  SELECT
TM_HAB.DATEPUBLICATION AS HAB_DATEPUBLICATION,
TM_RAC.NUMERONOR AS RAC_NUMERONOR,
TM_RAC.TITREACTE AS RAC_TITREACTE,
TM_RAC.DATEPUBLICATION AS RAC_DATEPUBLICATION,
TM_HAB.NUMEROORDRE AS HAB_NUMEROORDRE,
TM_HAB.ARTICLE AS HAB_ARTICLE,
TM_HAB.OBJETRIM AS HAB_OBJETRIM,
VOC_THAB."label" AS HAB_TYPEHABILITATION,
TM_HAB.MINISTEREPILOTE AS HAB_MINISTEREPILOTE,
TM_HAB.DATETERME AS HAB_DATETERME,
TM_HAB.CONVENTIONDEPOT AS HAB_CONVENTIONDEPOT,
TM_HAB.DATESAISINECE AS HAB_DATESAISINECE,
TM_HAB.DATEPREVISIONNELLECM AS HAB_DATEPREVISIONNELLECM,
TM_HAB.OBSERVATION AS HAB_OBSERVATION,
TM_HAB.CODIFICATION AS HAB_CODIFICATION,
TM_HAB.LEGISLATURE AS HAB_LEGISLATURE,
TM_ORD.DISPOSITIONHABILITATION AS ORD_DISPOSITIONHABILITATION,
TM_ORD.NUMERONOR AS ORD_NUMERONOR,
TM_ORD.MINISTEREPILOTE AS ORD_MINISTEREPILOTE,
TM_ORD.DATESAISINECE AS ORD_DATESAISINECE,
TM_ORD.DATEPREVISIONNELLECM AS ORD_DATEPREVISIONNELLECM,
TM_ORD.DATEPUBLICATION AS ORD_DATEPUBLICATION,
TM_ORD.TITREOFFICIEL AS ORD_TITREOFFICIEL,
TM_ORD.CONVENTIONDEPOT AS ORD_CONVENTIONDEPOT,
TM_ORD.DATELIMITEDEPOT AS ORD_DATELIMITEDEPOT,
TM_LRA.NUMERONOR AS LRA_NUMERONOR,
TM_LRA.TITREACTE AS LRA_TITREACTE,
TM_LRA.DATESAISINECE AS LRA_DATESAISINECE,
TM_LRA.DATEEXAMENCE AS LRA_DATEEXAMENCE,
TM_LRA.SECTIONCE AS LRA_SECTIONCE,
TM_LRA.DATEEXAMENCM AS LRA_DATEEXAMENCM,
TM_LRA.CHAMBREDEPOT AS LRA_CHAMBREDEPOT,
TM_LRA.DATEDEPOT AS LRA_DATEDEPOT,
TM_LRA.NUMERODEPOT AS LRA_NUMERODEPOT,
TM_LRA.TITREOFFICIEL AS LRA_TITREOFFICIEL,
TM_LRA.DATEPUBLICATION AS LRA_DATEPUBLICATION,
TM_LRA.NUMEROJOPUBLICATION AS LRA_NUMEROJOPUBLICATION
FROM
 TEXTE_MAITRE TM_RAC
 INNER JOIN      ACTIVITE_NORMATIVE AN        ON TM_RAC.ID  = AN.ID AND AN.ORDONNANCE38C = '1'
 LEFT OUTER JOIN TEXM_HABILITATIONIDS TEXH    ON TM_RAC.ID  = TEXH.ID
 LEFT OUTER JOIN TEXTE_MAITRE TM_HAB          ON TEXH.ITEM  = TM_HAB.ID
	LEFT OUTER JOIN VOC_TYPE_HABILITATION VOC_THAB ON TM_HAB.TYPEHABILITATION = VOC_THAB."id"
 LEFT OUTER JOIN TEXM_ORDONNANCEIDS TEXO      ON TM_HAB.ID  = TEXO.ID
 LEFT OUTER JOIN TEXTE_MAITRE TM_ORD          ON TEXO.ITEM  = TM_ORD.ID
 LEFT OUTER JOIN TEXM_LOIRATIFICATIONIDS TEXL ON TM_ORD.ID  = TEXL.ID
 LEFT OUTER JOIN TEXTE_MAITRE TM_LRA          ON TEXL.ITEM  = TM_LRA.ID
ORDER BY TM_RAC.NUMERO, TM_ORD.DATETERME;

