CREATE TABLE "TEXM_DECRETIDSNOTVALIDATED" 
   (	"ID" VARCHAR2(36 BYTE), 
	"POS" NUMBER(10,0), 
	"ITEM" NVARCHAR2(2000),
	CONSTRAINT "TEXM_TEXM_ID_HIERARCHY_FK" FOREIGN KEY ("ID")
    	REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
   );
