
  CREATE OR REPLACE VIEW "V_BORDEREAU_AUTRE_LISTE" ("MINISTERERESP", "NUMERONOR", "TITREACTE", "PUBLICATIONEPREUVEENRETOUR", "PUBLICATIONDELAI", "PUBLICATIONDATEDEMANDE", "TYPELISTE", "NUMEROLISTE", "ID", "DOCID", "DATEGENERATIONLISTE", "TYPESIGNATURE", "PUBTPLABEL", "MODPARULABEL", "PUBDELAILABEL", "VECTEURPUBLICATION") AS 
  SELECT DOS.MINISTERERESP, DOS.NUMERONOR,
       DOS.TITREACTE,
       TP.PUBLICATIONEPREUVEENRETOUR,
       TP.PUBLICATIONDELAI,
       TP.PUBLICATIONDATEDEMANDE,
       LISTE.TYPELISTE, LISTE.NUMEROLISTE,
       LISTE.ID,
       TP.ID as DOCID,
       LISTE.DATEGENERATIONLISTE,
       LISTE.TYPESIGNATURE,
       NVL(VOCPUBTP."VPINTITULE",' ') AS PUBTPLABEL,
       NVL(VOCMODEPARU."MODE",'') AS MODPARULABEL,
       NVL(VOCPUBDEL."label",' ') AS PUBDELAILABEL,
       NVL(VOCVEC."VPINTITULE",'') AS VECTEURPUBLICATION
  FROM DOSSIER_SOLON_EPG DOS,
       TRAITEMENT_PAPIER TP,
       LIS_IDSDOSSIER LISDOS,
       LISTE_TRAITEMENT_PAPI_144E75F6 LISTE,
       VECTEUR_PUBLICATION VOCPUBTP,
       MODE_PARUTION VOCMODEPARU,
       VOC_PUBLICATION_DELAI VOCPUBDEL,
       VECTEUR_PUBLICATION VOCVEC
 WHERE DOS.ID = TP.ID
   AND DOS.ID = LISDOS.ITEM
   AND LISDOS.ID = LISTE.ID
   AND (LISTE.TYPELISTE = '2' OR LISTE.TYPELISTE = '3')
   AND TP.PUBLICATIONNOMPUBLICATION = VOCPUBTP."ID"(+)
   AND TP.PUBLICATIONMODEPUBLICATION = VOCMODEPARU."ID"(+)
   AND TP.PUBLICATIONDELAI = VOCPUBDEL."id"(+)
   AND TP.PUBLICATIONNOMPUBLICATION = VOCVEC."ID"(+);

