CREATE TABLE "PARAMETRAGE_ADAMANT" 
   (	"ID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"NUMEROSOLON" NUMBER(19,0), 
	"ORIGINAGENCYBLOCIDENTIFIER" VARCHAR2(2000), 
	"SUBMISAGENCYBLOCIDENTIFIER" VARCHAR2(2000), 
	"ARCHIVALPROFILE" VARCHAR2(2000), 
	"ORIGINATINGAGENCYIDENTIFIER"VARCHAR2(2000), 
	"SUBMISSIONAGENCYIDENTIFIER" VARCHAR2(2000), 
	"DELAIELIGIBILITE" NUMBER(19,0), 
	"NBDOSSIEREXTRACTION" NUMBER(19,0)
   );
   
CREATE UNIQUE INDEX "PARAMETRAGE_ADAMANT_PK" ON "PARAMETRAGE_ADAMANT" ("ID") ;

ALTER TABLE "PARAMETRAGE_ADAMANT" ADD CONSTRAINT "PARAMETRAGE_ADAMANT_PK" PRIMARY KEY ("ID") ENABLE;

ALTER TABLE "PARAMETRAGE_ADAMANT" ADD CONSTRAINT "PAR_ADMANT_FK" FOREIGN KEY ("ID")
	  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE;