-- FEV560 - Ajout de la table des postes de retour au DAN

CREATE TABLE "TBREF_RETOURDAN" (
"ID" VARCHAR2(36 BYTE),
"POS" NUMBER(10,0),
"ITEM" NVARCHAR2(2000)
);

ALTER TABLE "TBREF_RETOURDAN" MODIFY ("ID" NOT NULL ENABLE);