ALTER TABLE DOSSIER_EXTRACTION_BORDEREAU
ADD STATUT_ARCHIVAGE_AFTER VARCHAR2(2);

UPDATE DOSSIER_EXTRACTION_BORDEREAU SET STATUT_ARCHIVAGE_AFTER='6' WHERE MESSAGE IS NULL;
UPDATE DOSSIER_EXTRACTION_BORDEREAU SET STATUT_ARCHIVAGE_AFTER='90' WHERE MESSAGE IS NOT NULL;

COMMIT;