-- index pour le suivi
CREATE INDEX "IDX_MISC_LF" ON "MISC" ("LIFECYCLESTATE");

-- index pour les logs
DROP INDEX IDX_NXP_LOGS_2;
CREATE INDEX "NXP_LOGS_UUID_DATE" ON "NXP_LOGS" ("LOG_DOC_UUID", "LOG_EVENT_DATE");

-- index en trop
drop index HIERARCHY_PRIMARYTYPE_IDX;

drop index HIERARCHY_PRIMARYTYPE_IDX;
drop index IDX_CASE_LINK_2;
drop index IDX_ACTIONNABLE_CASE_LINK_4;
drop index IDX_ACTIONNABLE_CASE_LINK_5;
drop index IDX_ACTIONNABLE_CASE_LINK_6;
DROP INDEX IDX_NXP_LOGS_1;
DROP INDEX IDX_DUBLINCORE_CREATED;
DROP INDEX IDX_ACT_CL_LIFE_STATUS;
drop index DOSSIER_ARCHIVAGE;

CREATE UNIQUE INDEX "IDX_DUBLINCORE_CREATED" ON "DUBLINCORE"("ID","CREATED");
CREATE UNIQUE INDEX "IDX_ACT_CL_LIFE_STATUS" ON "ACTIONNABLE_CASE_LINK"("CASELIFECYCLESTATE","STATUTARCHIVAGE","ID");
CREATE UNIQUE INDEX "IDX_ACTIONNABLE_CASE_LINK_6" ON "ACTIONNABLE_CASE_LINK" ("ROUTINGTASKTYPE", "ID");
CREATE UNIQUE INDEX DOSSIER_ARCH_ID ON DOSSIER_SOLON_EPG("STATUTARCHIVAGE", "ID");
CREATE UNIQUE INDEX DOSSIER_STAT_ID ON DOSSIER_SOLON_EPG("STATUT", "ID");

