/*Correction pour le rapport du nombre d'acte dans statitique*/

CREATE OR REPLACE VIEW V_STATS_NBR_ACTE_TYPE_PERIODE  AS
SELECT DOS.ID, DOS.MINISTEREATTACHE, DOS.MINISTERERESP, DOS.DIRECTIONRESP, DOS.MAILRESPDOSSIER, DUB.CREATED DATEDOSSIERCREE
FROM DOSSIER_SOLON_EPG DOS, DUBLINCORE DUB
WHERE DOS.ID = DUB.ID
AND   DOS.STATUTARCHIVAGE IN ('1', '2');


/*Ajouter dossier traitement papier, delai de publication et mode parution*/
CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_PUB  AS
SELECT '0' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION,
  NVL(VMP."label",' ') AS DELAIPUBLICATIONLABEL,
  NVL(VPD."label",' ') AS MODEPARUTIONLABEL
FROM DOSSIER_SOLON_EPG DOS, RETOUR_DILA RD, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND VMP."id" = RD.MODEPARUTION
AND VPD."id" = DOS.DELAIPUBLICATION
AND EXISTS ( 	SELECT * 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
				AND   ROU.TYPE IN (13, 14) )
UNION
SELECT '1' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, TP.PUBLICATIONDELAI DELAIPUBLICATION, TP.PUBLICATIONMODEPUBLICATION MODEPARUTION,
  NVL(VMP."label",' ') AS DELAIPUBLICATIONLABEL,
  NVL(VPD."label",' ') AS MODEPARUTIONLABEL
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
AND VMP."id" = TP.PUBLICATIONMODEPUBLICATION
AND VPD."id" = TP.PUBLICATIONDELAI
AND DOS.ID = TP.ID;


/*Correction pour la statistique du taux d'execution des lois */
CREATE OR REPLACE VIEW V_AN_MESURES_APPELANT_DECRET  AS
SELECT 
TM_LOI.ID AS LOI_ID, 
TM_LOI.MINISTEREPILOTE AS LOI_MINISTERERESP, 
TM_LOI.DATEPUBLICATION AS LOI_DATEPUBLICATION,
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION, 
TM_LOI.DATEENTREEENVIGUEUR AS LOI_DATEENTREEENVIGUEUR,
TM_LOI.NATURETEXTE AS LOI_NATURETEXTE, 
TM_LOI.PROCEDUREVOTE AS LOI_PROCEDUREVOTE, 
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE
FROM 
(TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = 1 ), 
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM)
WHERE TM_MES.TYPEMESURE = '1'
AND   TM_LOI.ID = TEXM.ID;

CREATE OR REPLACE VIEW V_AN_MESURES_ATTENTE_DECRET  AS
SELECT 
TM_LOI.ID AS LOI_ID, 
TM_LOI.MINISTEREPILOTE AS LOI_MINISTERERESP, 
TM_LOI.DATEPUBLICATION AS LOI_DATEPUBLICATION,
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION, 
TM_LOI.DATEENTREEENVIGUEUR AS LOI_DATEENTREEENVIGUEUR,
TM_LOI.NATURETEXTE AS LOI_NATURETEXTE, 
TM_LOI.PROCEDUREVOTE AS LOI_PROCEDUREVOTE, 
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE
FROM 
(TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = 1 ), 
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM)
WHERE TM_LOI.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU <> '1';