ALTER TABLE "FULLTEXT" DROP
	(
		"FULLTEXT_NOR",
        "SIMPLETEXT_NOR",
        "BINARYTEXT_NOR"
	);	   
   
ALTER TABLE "FULLTEXT" ADD
	(
		"FULLTEXT_TITREACTE" CLOB,
        "SIMPLETEXT_TITREACTE" NCLOB,
        "BINARYTEXT_TITREACTE" NCLOB
	);



   
CREATE OR REPLACE TRIGGER "NX_TRIG_FT_UPDATE"
  BEFORE INSERT OR UPDATE ON "FULLTEXT"
  FOR EACH ROW
BEGIN
    :NEW."FULLTEXT" := :NEW."SIMPLETEXT" || :NEW."BINARYTEXT";    
	:NEW."FULLTEXT_TITREACTE" := :NEW."SIMPLETEXT_TITREACTE" || :NEW."BINARYTEXT_TITREACTE";
END;
/


UPDATE FULLTEXT F SET F.FULLTEXT_TITREACTE = (SELECT d.TITREACTE FROM DOSSIER_SOLON_EPG d WHERE F.iD=d.ID);

COMMIT;

