CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_SIG_PM_PR  AS
SELECT DISTINCT DOS.*
FROM DOSSIER_SOLON_EPG DOS
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND EXISTS ( 	SELECT * 
				FROM HIERARCHY H, DONNEESSIGNATAIRE SIG
				WHERE DOS.ID = H.PARENTID
				AND   H.NAME IN ('tp:signaturePm', 'tp:signaturePr')
				AND   H.ID = SIG.ID
				AND   SIG.DATEENVOISIGNATURE IS NOT NULL
				AND   SIG.DATERETOURSIGNATURE IS NULL);

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_COM  AS
SELECT DOS.*
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND TP.TEXTESOUMISAVALIDATION = 1
AND DOS.ID = TP.ID
AND   EXISTS ( 	SELECT * 
				FROM HIERARCHY H, DESTINATAIRECOMMUNICATION DES
				WHERE DOS.ID = H.PARENTID
				AND   H.ID = DES.ID 
				AND   DES.DATERETOURCOMMUNICATION IS NULL 
				AND   DES.DATEENVOICOMMUNICATION IS NOT NULL );

CREATE OR REPLACE VIEW V_AN_MESURES_DELAIS_DERNIER  AS
SELECT 
TM_LOI.ID AS LOI_ID, 
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION,
TM_LOI.NATURETEXTE AS LOI_NATURETEXTE,
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE,
CASE
  WHEN TM_MES.DATEENTREEENVIGUEUR IS NULL 
  THEN (
    CASE WHEN TM_DEC.DATEPUBLICATION < TM_LOI.DATEPUBLICATION THEN 0
    ELSE TRUNC(abs(extract(day FROM ((TM_DEC.DATEPUBLICATION - TM_LOI.DATEPUBLICATION) day TO second))) / 30) END
  )
  ELSE (
    CASE WHEN TM_DEC.DATEPUBLICATION < TM_MES.DATEENTREEENVIGUEUR THEN 0
    ELSE TRUNC(abs(extract(day FROM ((TM_DEC.DATEPUBLICATION - TM_MES.DATEENTREEENVIGUEUR) day TO second))) / 30) END
  )
END DELAIS_EN_MOIS
FROM 
(TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = 1 ), 
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM),
(TEXTE_MAITRE TM_DEC INNER JOIN TEXM_DECRETIDS TEXD   ON TM_DEC.ID = TEXD.ITEM)
WHERE TM_LOI.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU = '1'
AND   TM_MES.ID = TEXD.ID
AND   TM_DEC.DATEPUBLICATION = (SELECT MAX(MX_TM_DEC.DATEPUBLICATION)
								FROM TEXM_MESUREIDS MX_TEXM, 
								(TEXTE_MAITRE MX_TM_DEC INNER JOIN TEXM_DECRETIDS MX_TEXD   ON MX_TM_DEC.ID = MX_TEXD.ITEM)
								WHERE TM_MES.ID = MX_TEXM.ITEM
								AND   MX_TEXM.ID = MX_TM_DEC.ID
                                );
								
CREATE OR REPLACE VIEW V_AN_MESURES_DELAIS_PREMIER  AS
SELECT 
TM_LOI.ID AS LOI_ID, 
TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION,
TM_LOI.NATURETEXTE AS LOI_NATURETEXTE,
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE,
CASE
  WHEN TM_MES.DATEENTREEENVIGUEUR IS NULL 
  THEN (
    CASE WHEN TM_DEC.DATEPUBLICATION < TM_LOI.DATEPUBLICATION THEN 0
    ELSE TRUNC(abs(extract(day FROM ((TM_DEC.DATEPUBLICATION - TM_LOI.DATEPUBLICATION) day TO second))) / 30) END
  )
  ELSE (
    CASE WHEN TM_DEC.DATEPUBLICATION < TM_MES.DATEENTREEENVIGUEUR THEN 0
    ELSE TRUNC(abs(extract(day FROM ((TM_DEC.DATEPUBLICATION - TM_MES.DATEENTREEENVIGUEUR) day TO second))) / 30) END
  )
END DELAIS_EN_MOIS
FROM 
(TEXTE_MAITRE TM_LOI INNER JOIN ACTIVITE_NORMATIVE AN ON TM_LOI.ID = AN.ID AND AN.APPLICATIONLOI = 1 ), 
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM),
(TEXTE_MAITRE TM_DEC INNER JOIN TEXM_DECRETIDS TEXD   ON TM_DEC.ID = TEXD.ITEM)
WHERE TM_LOI.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU = '1'
AND   TM_MES.ID = TEXD.ID
AND   TM_DEC.DATEPUBLICATION = (SELECT MIN(MN_TM_DEC.DATEPUBLICATION)
								FROM TEXM_MESUREIDS MN_TEXM, 
								(TEXTE_MAITRE MN_TM_DEC INNER JOIN TEXM_DECRETIDS MN_TEXD   ON MN_TM_DEC.ID = MN_TEXD.ITEM)
								WHERE TM_MES.ID = MN_TEXM.ITEM
								AND   MN_TEXM.ID = MN_TM_DEC.ID
                                );

CREATE OR REPLACE VIEW V_STATS_NOMBRE_ACTE_PAR_TYPE  AS
SELECT DOS.TYPEACTE, DOS.ID, DUB.CREATED DATEDOSSIERCREE
FROM DOSSIER_SOLON_EPG DOS, DUBLINCORE DUB
WHERE DOS.ID = DUB.ID
AND   DOS.STATUTARCHIVAGE IN ('1', '2');
