ALTER TABLE NAVETTE DROP COLUMN DATEREUNION;
ALTER TABLE NAVETTE ADD DATEREUNIONAN TIMESTAMP(6);
ALTER TABLE NAVETTE ADD DATEREUNIONSE TIMESTAMP(6);
ALTER TABLE NAVETTE ADD RESULTATSE NVARCHAR2(2000);
ALTER TABLE NAVETTE ADD RESULTATAN NVARCHAR2(2000);

commit;