
CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_COM  AS
SELECT DOS.*
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP
WHERE DOS.ARCHIVE = 0
AND TP.TEXTESOUMISAVALIDATION = 1
AND   EXISTS ( 	SELECT * 
				FROM HIERARCHY H, DESTINATAIRECOMMUNICATION DES
				WHERE DOS.ID = H.PARENTID
				AND   H.ID = DES.ID 
				AND   DES.DATERETOURCOMMUNICATION IS NULL 
				AND   DES.DATEENVOICOMMUNICATION IS NOT NULL );

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_SIG_PM_PR  AS
SELECT DISTINCT DOS.*
FROM DOSSIER_SOLON_EPG DOS
WHERE DOS.ARCHIVE = 0
AND EXISTS ( 	SELECT * 
				FROM HIERARCHY H, DONNEESSIGNATAIRE SIG
				WHERE DOS.ID = H.PARENTID
				AND   H.NAME IN ('dos:signaturePm', 'dos:signaturePr')
				AND   H.ID = SIG.ID
				AND   SIG.DATEENVOISIGNATURE IS NOT NULL
				AND   SIG.DATERETOURSIGNATURE IS NULL);

CREATE OR REPLACE VIEW V_STATS_LISTE_EPREUVE_RELEC  AS
SELECT DISTINCT DOS.*
FROM DOSSIER_SOLON_EPG DOS, 
     TRAITEMENT_PAPIER TP
WHERE DOS.ID = TP.ID
AND   DOS.ARCHIVE = 0
AND EXISTS (
				SELECT * 
				FROM INFOEPREUVE EPR, HIERARCHY H
				WHERE DOS.ID = H.PARENTID
				AND   H.ID = EPR.ID
				AND   EPR.EPREUVEENVOIRELECTURELE IS NOT NULL
				AND   TP.RETOURDUBONATITRERLE IS NULL );

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_AMPLIATION  AS
SELECT  DOS.ID, 
		DOS.NUMERONOR, 
		DOS.TITREACTE, 
		LISTAGG (AMP.ITEM, ', ') WITHIN GROUP (ORDER BY AMP.ITEM) ITEM
FROM (DOSSIER_SOLON_EPG DOS INNER JOIN TP_AMPLIATIONDESTINATAIREMAILS AMP ON DOS.ID = AMP.ID AND DOS.ARCHIVE = 0)
GROUP BY DOS.ID, DOS.NUMERONOR, DOS.TITREACTE;

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_RIG  AS
SELECT DISTINCT DOS.*
FROM DOSSIER_SOLON_EPG DOS,
     TRAITEMENT_PAPIER TP
WHERE DOS.ID = TP.ID
AND   DOS.ARCHIVE = 0
AND( 
	EXISTS
	(
		SELECT *
		FROM ACTIONNABLE_CASE_LINK ACT, CASE_LINK CAS, ROUTING_TASK ROU
		WHERE DOS.ID = CAS.CASEDOCUMENTID
		AND   CAS.ID = ACT.ID
		AND   ACT.ROUTINGTASKID = ROU.ID
		AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
		AND   ROU.TYPE = 13
		AND   ACT.CASELIFECYCLESTATE = 'RUNNING'
		AND   ACT.DELETED = 0
		AND   DOS.DELAIPUBLICATION = 3
	)
	 OR
	(
		TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY') 
		AND   TP.PUBLICATIONDELAI = 3
	)
);

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_ARRIVE_SGG  AS
SELECT DISTINCT DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, TP.DATEARRIVEPAPIER
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP
WHERE DOS.ARCHIVE = 0
AND DOS.ID = TP.ID;

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_CORBEILLE  AS
SELECT DISTINCT DOS.*, ROU.DISTRIBUTIONMAILBOXID
FROM DOSSIER_SOLON_EPG DOS, ACTIONNABLE_CASE_LINK ACT, CASE_LINK CAS, ROUTING_TASK ROU
WHERE DOS.ID = CAS.CASEDOCUMENTID
AND DOS.ARCHIVE = 0
AND CAS.ID = ACT.ID
AND ACT.ROUTINGTASKID = ROU.ID
AND ACT.DELETED = 0
AND ACT.CASELIFECYCLESTATE = 'running';

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_PUB  AS
SELECT DOS.*
FROM DOSSIER_SOLON_EPG DOS
WHERE DOS.ARCHIVE = 0
AND EXISTS ( 	SELECT * 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
				AND   ROU.TYPE IN (13, 14) );

CREATE OR REPLACE VIEW V_STATS_NOMBRE_ACTE_PAR_TYPE  AS
SELECT DOS.TYPEACTE, DOS.ID, DUB.CREATED DATEDOSSIERCREE
FROM DOSSIER_SOLON_EPG DOS, DUBLINCORE DUB
WHERE DOS.ID = DUB.ID
AND   DOS.ARCHIVE = 0;

CREATE OR REPLACE VIEW V_STATS_NBR_ACTE_TYPE_PERIODE  AS
SELECT DOS.ID, DOS.MINISTEREATTACHE, DOS.MINISTERERESP, DOS.DIRECTIONRESP, DOS.MAILRESPDOSSIER, DUB.CREATED DATEDOSSIERCREE
FROM DOSSIER_SOLON_EPG DOS, DUBLINCORE DUB
WHERE DOS.ID = DUB.ID
AND   DOS.ARCHIVE = 0;

CREATE OR REPLACE VIEW V_STATS_LISTE_ACTE_TYPE_15  AS
SELECT DOS.ID, DOS.MINISTEREATTACHE, TP.DATERETOUR, ROU.DISTRIBUTIONMAILBOXID
FROM DOSSIER_SOLON_EPG DOS, HIERARCHY H, ROUTING_TASK ROU, TRAITEMENT_PAPIER TP
WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
AND   DOS.ARCHIVE = 0
AND   H.ID = ROU.ID
AND TP.ID = DOS.ID
AND   ROU.TYPE = 15;

CREATE OR REPLACE VIEW V_STATS_LISTE_ALL_ACTE  AS
SELECT DOS.ID, DOS.MINISTEREATTACHE, TP.DATERETOUR
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP
WHERE DOS.ID = TP.ID
AND DOS.ARCHIVE = 0;

CREATE OR REPLACE VIEW V_STATS_LISTE_ALL_ACTE_DETAIL  AS
SELECT  DOS.ID ID, 
		DOS.MINISTEREATTACHE MINISTEREATTACHE,  
		TP.DATERETOUR DATERETOUR, 
		H.POS POS, 
		ROU.DISTRIBUTIONMAILBOXID DISTRIBUTIONMAILBOXID, 
		ROU.TYPE TYPE
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, HIERARCHY H, ROUTING_TASK ROU
WHERE DOS.ID = TP.ID
AND   DOS.LASTDOCUMENTROUTE = H.PARENTID
AND   DOS.ARCHIVE = 0
AND   H.ID = ROU.ID;