CREATE OR REPLACE VIEW V_AN_MESURES_PREVISIONNELLE  AS
SELECT
TM_LOI.NUMERO AS NUMEROLOI,  
TM_LOI.TITREOFFICIEL, 
TM_MES.NUMEROORDRE, 
TM_MES.ARTICLE, 
TM_MES.BASELEGALE, 
TM_MES.OBJETRIM, 
TM_MES.MINISTEREPILOTE, 
TM_MES.DIRECTIONRESPONSABLE,
TM_MES.CONSULTATIONSHCE,
TM_MES.CALENDRIERCONSULTATIONSHCE,
TM_MES.DATEPREVISIONNELLESAISINECE,
TM_MES.DATEOBJECTIFPUBLICATION,
TO_CHAR(TM_DEC.DATESAISINECE, 'DD/MM/YYYY') DATESAISINECE, 
TO_CHAR(TM_DEC.DATESORTIECE, 'DD/MM/YYYY') DATESORTIECE, 
TM_MES.OBSERVATION, 
TM_DEC.NUMERONOR,
TM_DEC.TITREOFFICIEL DECRET_TITREOFFICIEL, 
NVL(VOC_TM_DEC."label", '') AS TYPACTE,
TO_CHAR(TM_DEC.DATEPUBLICATION, 'DD/MM/YYYY') DATEPUBLICATION,
TM_MES.APPLICATIONRECU
FROM TEXTE_MAITRE TM_LOI, TEXM_MESUREIDS TME, ACTIVITE_NORMATIVE AN, TEXTE_MAITRE TM_MES
LEFT JOIN TEXM_DECRETIDS TD ON TD.ID = TM_MES.ID
LEFT JOIN TEXTE_MAITRE TM_DEC ON TM_DEC.ID = TD.ITEM
LEFT JOIN VOC_ACTE_TYPE VOC_TM_DEC ON TM_DEC.TYPEACTE = VOC_TM_DEC."id"
WHERE TM_LOI.ID = AN.ID
AND AN.APPLICATIONLOI = '1'
AND TM_MES.TYPEMESURE = '1'
AND TME.ID = AN.ID
AND TM_MES.ID = TME.ITEM
AND TM_MES.DATEOBJECTIFPUBLICATION < SYSDATE
ORDER BY NUMEROLOI, TO_NUMBER(TM_MES.NUMEROORDRE);
commit;