CREATE OR REPLACE VIEW V_ECHEANCIER_PROMULGATION
AS
  SELECT F.IDDOSSIER, F.DATESAISIECC, F.DATEDECISION, F.DATERECEPTION,
    DOS.EPREUVEDEMANDELE, DOS.EPREUVEPOURLE, DOS.EPREUVEENVOIRELECTURELE,
    DOS.RETOURDUBONATITRERLE, DOS.DATEENVOISIGNATURE, DOS.DATERETOURSIGNATURE,
    F.DEPARTELYSEE, F.RETOURELYSEE, F.DATELIMITEPROMULGATION, F.DATEJO
  FROM FICHE_LOI F LEFT JOIN
  (
    SELECT D.NUMERONOR, T.RETOURDUBONATITRERLE, E.EPREUVEDEMANDELE, E.EPREUVEPOURLE, E.EPREUVEENVOIRELECTURELE, S.DATEENVOISIGNATURE, S.DATERETOURSIGNATURE
    FROM DOSSIER_SOLON_EPG D, TRAITEMENT_PAPIER T, HIERARCHY HE, HIERARCHY HS, INFOEPREUVE E, DONNEESSIGNATAIRE S
    WHERE D.ID = T.ID
    AND D.ID = HE.PARENTID
    AND E.ID = HE.ID
    AND HE.NAME = 'tp:epreuve'
    AND D.ID = HS.PARENTID
    AND S.ID = HS.ID
    AND HS.NAME = 'tp:signaturePm'
  )DOS ON F.IDDOSSIER = DOS.NUMERONOR
  WHERE F.ECHEANCIERPROMULGATION = 1;
  
commit;