CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_PUB  AS
SELECT '0' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION, 
  DOS.MINISTERERESP, TO_CHAR (DOS.DATEPRECISEEPUBLICATION, 'DD/MM/YYYY') AS DATEPRECISEPUB,
  NVL(VMP."label",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, RETOUR_DILA RD, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND RD.MODEPARUTION =  VMP."id"(+)
AND DOS.DELAIPUBLICATION = VPD."id" (+)
AND RD.ID = DOS.ID
AND EXISTS ( 	SELECT * 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
        		AND   ROU.DATEFINETAPE IS NULL
				AND   ROU.TYPE IN (13) )
AND EXISTS ( SELECT * 
        FROM DOS_VECTEURPUBLICATION VEC, VOC_VECTEUR_PUBLICATION_TP VOC
        WHERE VEC.ID = DOS.ID
        AND VEC.ITEM = VOC."label"
        AND VOC."id" = '1' )
UNION
SELECT '1' AS IS_TP, DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, TP.PUBLICATIONDELAI DELAIPUBLICATION, DOS.MINISTERERESP,
  TP.PUBLICATIONMODEPUBLICATION MODEPARUTION, TO_CHAR (TP.PUBLICATIONDATEDEMANDE, 'DD/MM/YYYY')  AS DATEPRECISEPUB,
  NVL(VMP."label",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL
FROM DOSSIER_SOLON_EPG DOS, TRAITEMENT_PAPIER TP, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
AND TP.PUBLICATIONMODEPUBLICATION = VMP."id" (+)
AND TP.PUBLICATIONDELAI = VPD."id" (+)
AND TP.PUBLICATIONNOMPUBLICATION = '1'
AND DOS.ID = TP.ID;

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_RIG  AS
SELECT DISTINCT DOS.*
FROM DOSSIER_SOLON_EPG DOS,
     TRAITEMENT_PAPIER TP
WHERE DOS.ID = TP.ID
AND   DOS.STATUTARCHIVAGE IN ('1', '2')
AND(
( 
	EXISTS
	(
		SELECT *
		FROM ACTIONNABLE_CASE_LINK ACT, CASE_LINK CAS, ROUTING_TASK ROU
		WHERE DOS.ID = CAS.CASEDOCUMENTID
		AND   CAS.ID = ACT.ID
		AND   ACT.ROUTINGTASKID = ROU.ID
		AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY')
    AND   ROU.DATEFINETAPE IS NULL
		AND   ROU.TYPE = 13
		AND   DOS.DELAIPUBLICATION = 3
	)
  AND EXISTS 
  ( 
    SELECT * 
    FROM DOS_VECTEURPUBLICATION VEC, VOC_VECTEUR_PUBLICATION_TP VOC
    WHERE VEC.ID = DOS.ID
    AND VEC.ITEM = VOC."label"
    AND VOC."id" = '1'
  )
)
OR (
  TO_CHAR (TP.PUBLICATIONDATEENVOIJO, 'MM/DD/YYYY') = TO_CHAR(SYSTIMESTAMP,'MM/DD/YYYY') 
  AND   TP.PUBLICATIONDELAI = 3
  AND TP.PUBLICATIONNOMPUBLICATION = '1'
))
;

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_EPR  AS
SELECT DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION, 
  TO_CHAR (DOS.POURFOURNITUREEPREUVE, 'DD/MM/YYYY') AS POURFOURNITUREEPREUVE,
  DOS.MINISTERERESP, TO_CHAR (DOS.DATEPRECISEEPUBLICATION, 'DD/MM/YYYY') AS DATEPRECISEPUB,
  NVL(VMP."label",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL,
  VEC.ITEM AS VECTEURPUBLICATION
FROM DOSSIER_SOLON_EPG DOS, DOS_VECTEURPUBLICATION VEC, 
  RETOUR_DILA RD, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND RD.MODEPARUTION =  VMP."id"(+)
AND DOS.DELAIPUBLICATION = VPD."id" (+)
AND DOS.ID = VEC.ID(+)
AND RD.ID = DOS.ID
AND EXISTS ( 	SELECT * 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
        AND   ROU.DATEFINETAPE IS NULL
				AND   ROU.TYPE IN (12) );

CREATE OR REPLACE VIEW V_STATS_LISTE_TEXTE_DILA_JO_BO  AS
SELECT DOS.ID, DOS.NUMERONOR, DOS.TITREACTE, DOS.DELAIPUBLICATION, RD.MODEPARUTION, 
  TO_CHAR (DOS.POURFOURNITUREEPREUVE, 'DD/MM/YYYY') AS POURFOURNITUREEPREUVE,
  DOS.MINISTERERESP, TO_CHAR (DOS.DATEPRECISEEPUBLICATION, 'DD/MM/YYYY') AS DATEPRECISEPUB,
  NVL(VMP."label",' ') AS MODEPARUTIONLABEL,
  NVL(VPD."label",' ') AS DELAIPUBLICATIONLABEL,
  VEC.ITEM AS VECTEURPUBLICATION
FROM DOSSIER_SOLON_EPG DOS, DOS_VECTEURPUBLICATION VEC, 
  RETOUR_DILA RD, VOC_MODE_PARUTION VMP, VOC_PUBLICATION_DELAI VPD
WHERE DOS.STATUTARCHIVAGE IN ('1', '2')
AND RD.MODEPARUTION =  VMP."id"(+)
AND DOS.DELAIPUBLICATION = VPD."id" (+)
AND DOS.ID = VEC.ID(+)
AND RD.ID = DOS.ID
AND EXISTS ( 	SELECT * 
				FROM HIERARCHY H, ROUTING_TASK ROU
				WHERE DOS.LASTDOCUMENTROUTE = H.PARENTID
				AND   H.ID = ROU.ID
				AND   TO_CHAR (ROU.DATEDEBUTETAPE, 'DD/MM/YYYY') = TO_CHAR(SYSTIMESTAMP,'DD/MM/YYYY')
        		AND   ROU.DATEFINETAPE IS NULL
				AND   ROU.TYPE IN (13, 14) );

delete from VOC_VECTEUR_PUBLICATION_TP;
insert into VOC_VECTEUR_PUBLICATION_TP ("id","obsolete","ordering","label") values ('1',0,10000000,'Journal Officiel');
insert into VOC_VECTEUR_PUBLICATION_TP ("id","obsolete","ordering","label") values ('2',0,10000000,'BODMR');
insert into VOC_VECTEUR_PUBLICATION_TP ("id","obsolete","ordering","label") values ('3',0,10000000,'Documents administratifs');
insert into VOC_VECTEUR_PUBLICATION_TP ("id","obsolete","ordering","label") values ('4',0,10000000,'JO + Documents administratifs');
commit;
