CREATE TABLE FICHE_PRESENTATION_DPG
  (
    "ID" VARCHAR2(36) NOT NULL ,
	"OBJET" NVARCHAR2(2000),	
	"DATEPRESENTATION" TIMESTAMP(6),
	"DATELETTREPM" TIMESTAMP(6),
	"DATEVOTE" TIMESTAMP (6),
	"SENSAVIS" NVARCHAR2(2000),
	"SUFFRAGEEXPRIME" NUMBER(19,0),
	"VOTEPOUR" NUMBER(19,0),
	"VOTECONTRE" NUMBER(19,0),
	"ABSTENTION" NUMBER(19,0),
	"IDDOSSIER" NVARCHAR2(2000),
    CONSTRAINT REPRESENTANT_DPG_PK PRIMARY KEY ( ID ) ENABLE,
    CONSTRAINT REPR_DPG_FK FOREIGN KEY (ID) REFERENCES HIERARCHY (ID) ON DELETE CASCADE ENABLE
  );
