CREATE TABLE REPRESENTANT_AUD
  (
    ID VARCHAR2(36) NOT NULL ,
    IDFPAUD VARCHAR2(36) ,
    DATEDEBUT TIMESTAMP(6) ,
    DATEFIN TIMESTAMP(6) ,
    DATEAUDITIONAN TIMESTAMP(6) ,
    DATEAUDITIONSE TIMESTAMP(6) ,
    PERSONNE NVARCHAR2(200) ,
	FONCTION NVARCHAR2(200) ,
    CONSTRAINT REPRESENTANT_AUD_PK PRIMARY KEY ( ID ) ENABLE,
    CONSTRAINT REPR_AUD_FK FOREIGN KEY (ID) REFERENCES HIERARCHY (ID) ON DELETE CASCADE ENABLE
  );
