CREATE TABLE FICHE_PRESENTATION_AUD
  (
    "ID" VARCHAR2(36) NOT NULL ENABLE,
    "IDORGANISMEEPP" NVARCHAR2(200),
    "NOMORGANISME" NVARCHAR2(2000),
    "DATE" TIMESTAMP (6),
	"DATEFIN" TIMESTAMP (6),
    "IDDOSSIER" VARCHAR2(36),
    "BASELEGALE" NVARCHAR2(2000),
    CONSTRAINT "FICHE_PRESENTATION_AUD_PK" PRIMARY KEY ("ID") ENABLE,
    CONSTRAINT "FICH_AUD_FK" FOREIGN KEY ("ID") REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
  );
  