CREATE TABLE FICHE_PRESENTATION_DOC
  (
    "ID" VARCHAR2(36) NOT NULL ,
	"OBJET" NVARCHAR2(2000),	
	"DATELETTREPM" TIMESTAMP(6),
	"IDDOSSIER" NVARCHAR2(2000),
	"BASELEGALE" NVARCHAR2(2000),
    CONSTRAINT REPRESENTANT_DOC_PK PRIMARY KEY ( ID ) ENABLE,
    CONSTRAINT REPR_DOC_FK FOREIGN KEY (ID) REFERENCES HIERARCHY (ID) ON DELETE CASCADE ENABLE
  );
