CREATE TABLE FICHE_PRESENTATION_JSS
  (
    "ID" VARCHAR2(36) NOT NULL ,
	"OBJET" NVARCHAR2(2000),	
	"DATELETTREPM" TIMESTAMP(6),
	"IDDOSSIER" NVARCHAR2(2000),
    CONSTRAINT REPRESENTANT_JSS_PK PRIMARY KEY ( ID ) ENABLE,
    CONSTRAINT REPR_JSS_FK FOREIGN KEY (ID) REFERENCES HIERARCHY (ID) ON DELETE CASCADE ENABLE
  );
