CREATE OR REPLACE VIEW V_COURIER_PRESIDENT_INFO
AS
SELECT 'AN' AS CODE, NOMAN NOM, 'Palais Bourbon' AS ADDRESS, 'Président de l’Assemblée nationale' AS PRESIDENT
 FROM PARAMETRAGE_MGPP
 UNION ALL
 SELECT 'S' AS CODE, NOMSENAT NOM, 'Palais du Luxembourg' AS ADDRESS, 'Président du Sénat' AS PRESIDENT
 FROM PARAMETRAGE_MGPP
COMMIT ;
