-- vue pour mesure application date previsionnelle dépassée
CREATE OR REPLACE VIEW "V_AN_MES_PREV_APP_ORDO" ("NUMEROORDO", "TITREOFFICIEL", "NUMEROORDRE", "ARTICLE", "BASELEGALE", "OBJETRIM", "MINISTEREPILOTE", "DIRECTIONRESPONSABLE", "CONSULTATIONSHCE", "CALENDRIERCONSULTATIONSHCE", "DATEPREVISIONNELLESAISINECE", "DATEOBJECTIFPUBLICATION", "DATESAISINECE", "DATESORTIECE", "OBSERVATION", "NUMERONOR", "DECRET_TITREOFFICIEL", "TYPACTE", "DATEPUBLICATION", "DATEMISEAPPLICATION", "DATEPUBLICATIONORDO", "APPLICATIONRECU", "LEGISLATUREPUBLICATION")
                       AS
  SELECT TM_ORDO.NUMERO AS NUMEROORDO,
    TM_ORDO.TITREOFFICIEL,
    TM_MES.NUMEROORDRE,
    TM_MES.ARTICLE,
    TM_MES.BASELEGALE,
    TM_MES.OBJETRIM,
    TM_MES.MINISTEREPILOTE,
    TM_MES.DIRECTIONRESPONSABLE,
    TM_MES.CONSULTATIONSHCE,
    TM_MES.CALENDRIERCONSULTATIONSHCE,
    TM_MES.DATEPREVISIONNELLESAISINECE,
    TM_MES.DATEOBJECTIFPUBLICATION,
    TM_DEC.DATESAISINECE,
    TM_DEC.DATESORTIECE,
    TM_MES.OBSERVATION,
    TM_DEC.NUMERONOR,
    TM_DEC.TITREOFFICIEL DECRET_TITREOFFICIEL,
    NVL(VOC_TM_DEC."label", '') AS TYPACTE,
    TM_DEC.DATEPUBLICATION,
    TM_MES.DATEMISEAPPLICATION,
    TM_ORDO.DATEPUBLICATION AS DATEPUBLICATIONORDO,
    TM_MES.APPLICATIONRECU,
    TM_ORDO.LEGISLATUREPUBLICATION AS LEGISLATUREPUBLICATION
  FROM TEXTE_MAITRE TM_ORDO,
    TEXM_MESUREIDS TME,
    ACTIVITE_NORMATIVE AN,
    TEXTE_MAITRE TM_MES
  LEFT JOIN TEXM_DECRETIDS TD
  ON TD.ID = TM_MES.ID
  LEFT JOIN TEXTE_MAITRE TM_DEC
  ON TM_DEC.ID = TD.ITEM
  LEFT JOIN VOC_ACTE_TYPE VOC_TM_DEC
  ON TM_DEC.TYPEACTE                 = VOC_TM_DEC."id"
  WHERE TM_ORDO.ID                   = AN.ID
  AND AN.APPLICATIONORDONNANCE       = '1'
  AND TM_MES.TYPEMESURE              = '1'
  AND TME.ID                         = AN.ID
  AND TM_MES.ID                      = TME.ITEM
  AND TM_MES.DATEOBJECTIFPUBLICATION < SYSDATE
  AND (TM_ORDO.DISPOSITIONHABILITATION IS NULL OR TM_ORDO.DISPOSITIONHABILITATION = 1);


--------------------------------------------------------
--  DDL for View V_AN_MES_LEGIS_APP_ORDO
--------------------------------------------------------
CREATE OR REPLACE VIEW "V_AN_MES_LEGIS_APP_ORDO" ("MOTCLE", "NUMEROORDO", "TITREOFFICIEL", "NATURETEXTE", "PROCEDUREVOTE", "DATEPUBLICATION", "LEGISLATUREPUBLICATION", "NUMEROORDRE", "ARTICLE", "CODEMODIFIE", "BASELEGALE", "OBJETRIM", "MINISTEREPILOTE", "DIRECTIONRESPONSABLE", "CONSULTATIONSHCE", "CALENDRIERCONSULTATIONSHCE", "DATEPREVISIONNELLESAISINECE", "DATEENTREEENVIGUEUR", "DATEOBJECTIFPUBLICATION", "TYPEMESUREID", "TYPEMESURE", "OBSERVATION", "NUMERONOR", "DECRET_TITREOFFICIEL", "TYPACTE", "DATESAISINECE", "DATESORTIECE", "DECRET_DATEPUBLICATION", "DATEMISEAPPLICATION", "MES_DATEENTREEENVIGUEUR", "APPLICATIONRECU", "ORDO_DATEPROMULGATION", "MES_DIFFERE") AS 
  SELECT
TM_ORDO.MOTCLE,
TM_ORDO.NUMERO AS NUMEROORDO,
TM_ORDO.TITREOFFICIEL,
TM_ORDO.NATURETEXTE AS NATURETEXTE,
TM_ORDO.PROCEDUREVOTE AS PROCEDUREVOTE,
TM_ORDO.DATEPUBLICATION,
TM_ORDO.LEGISLATUREPUBLICATION,
TM_MES.NUMEROORDRE,
TM_MES.ARTICLE,
TM_MES.CODEMODIFIE,
TM_MES.BASELEGALE,
TM_MES.OBJETRIM,
TM_MES.MINISTEREPILOTE,
TM_MES.DIRECTIONRESPONSABLE,
TM_MES.CONSULTATIONSHCE,
TM_MES.CALENDRIERCONSULTATIONSHCE,
TM_MES.DATEPREVISIONNELLESAISINECE,
TM_MES.DATEENTREEENVIGUEUR,
TM_MES.DATEOBJECTIFPUBLICATION DATEOBJECTIFPUBLICATION,
TM_MES.TYPEMESURE           AS TYPEMESUREID,
NVL(VOC_TM_MES."label", '') AS TYPEMESURE,
TM_MES.OBSERVATION,
TM_DEC.NUMERONOR,
TM_DEC.TITREOFFICIEL DECRET_TITREOFFICIEL,
NVL(VOC_TM_DEC."label",' ') AS TYPACTE,
TM_DEC.DATESAISINECE,
TM_DEC.DATESORTIECE,
TM_DEC.DATEPUBLICATION,
TM_MES.DATEMISEAPPLICATION,
TM_MES.DATEENTREEENVIGUEUR as MES_DATEENTREEENVIGUEUR,
TM_MES.APPLICATIONRECU,
TM_ORDO.DATEPROMULGATION AS ORDO_DATEPROMULGATION,
TM_MES.DIFFERE as MES_DIFFERE
FROM TEXTE_MAITRE TM_ORDO, TEXM_MESUREIDS TME, ACTIVITE_NORMATIVE AN, TEXTE_MAITRE TM_MES
LEFT JOIN VOC_TYPE_MESURE VOC_TM_MES ON TM_MES.TYPEMESURE = VOC_TM_MES."id"
LEFT JOIN TEXM_DECRETIDS TD ON TD.ID = TM_MES.ID
LEFT JOIN TEXTE_MAITRE TM_DEC ON TM_DEC.ID = TD.ITEM
LEFT JOIN VOC_ACTE_TYPE VOC_TM_DEC ON TM_DEC.TYPEACTE = VOC_TM_DEC."id"
WHERE TM_ORDO.ID = AN.ID
AND AN.APPLICATIONORDONNANCE = '1'
AND TM_MES.TYPEMESURE IN ('1','4' ,'6')
AND TME.ID = AN.ID
AND TM_MES.ID = TME.ITEM
AND (TM_ORDO.DISPOSITIONHABILITATION IS NULL OR TM_ORDO.DISPOSITIONHABILITATION = 1);


--vue mesures ayant reçu application pour les ordonnances
CREATE OR REPLACE VIEW "V_AN_MESURES_RECU_APP_ORDO" ("ORDO_ID", "ORDO_MINISTERERESP", "ORDO_DATEPUBLICATION", "ORDO_DATEPROMULGATION", "ORDO_DATEENTREEENVIGUEUR", "MESURE_ID", "MESURE_MINISTEREPILOTE", "DECRET_ID", "DECRET_DATEPUBLICATION", "MES_DATEMISEAPPLICATION", "MES_DATEENTREEENVIGUEUR", "MES_DIFFERE") AS 
  SELECT
TM_ORDO.ID AS ORDO_ID,
TM_ORDO.MINISTEREPILOTE AS ORDO_MINISTERERESP,
TM_ORDO.DATEPUBLICATION AS ORDO_DATEPUBLICATION,
TM_ORDO.DATEPROMULGATION AS ORDO_DATEPROMULGATION,
TM_ORDO.DATEENTREEENVIGUEUR AS ORDO_DATEENTREEENVIGUEUR,
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE,
TM_DEC.ID AS DECRET_ID,
TM_DEC.DATEPUBLICATION AS DECRET_DATEPUBLICATION,
TM_MES.DATEMISEAPPLICATION AS MES_DATEMISEAPPLICATION,
TM_MES.DATEENTREEENVIGUEUR as MES_DATEENTREEENVIGUEUR,
TM_MES.DIFFERE as MES_DIFFERE
FROM
(TEXTE_MAITRE TM_ORDO INNER JOIN ACTIVITE_NORMATIVE AN ON TM_ORDO.ID = AN.ID AND AN.APPLICATIONORDONNANCE = '1' ),
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM),
(TEXTE_MAITRE TM_DEC INNER JOIN TEXM_DECRETIDS TEXD   ON TM_DEC.ID = TEXD.ITEM)
WHERE TM_ORDO.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU = '1'
AND   TM_MES.ID = TEXD.ID
AND (TM_ORDO.DISPOSITIONHABILITATION IS NULL OR TM_ORDO.DISPOSITIONHABILITATION = 1)
AND   TM_DEC.DATEPUBLICATION = (SELECT MAX(MX_TM_DEC.DATEPUBLICATION)
        FROM TEXM_MESUREIDS MX_TEXM,
        (TEXTE_MAITRE MX_TM_DEC INNER JOIN TEXM_DECRETIDS MX_TEXD   ON MX_TM_DEC.ID = MX_TEXD.ITEM)
        WHERE TM_MES.ID = MX_TEXD.ID
        AND   MX_TEXM.ID = MX_TM_DEC.ID);


--vue mesure appelant décret pour les ordonnances
CREATE OR REPLACE VIEW "V_AN_MESURES_APPEL_DECRET_ORDO" ("ORDO_ID", "ORDO_MINISTERERESP", "ORDO_DATEPUBLICATION", "ORDO_DATEPROMULGATION", "ORDO_DATEENTREEENVIGUEUR", "MESURE_ID", "MESURE_MINISTEREPILOTE") AS 
  SELECT
TM_ORDO.ID AS LOI_ID,
TM_ORDO.MINISTEREPILOTE AS ORDO_MINISTERERESP,
TM_ORDO.DATEPUBLICATION AS ORDO_DATEPUBLICATION,
TM_ORDO.DATEPROMULGATION AS ORDO_DATEPROMULGATION,
TM_ORDO.DATEENTREEENVIGUEUR AS ORDO_DATEENTREEENVIGUEUR,
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE
FROM
(TEXTE_MAITRE TM_ORDO INNER JOIN ACTIVITE_NORMATIVE AN ON TM_ORDO.ID = AN.ID AND AN.APPLICATIONORDONNANCE = '1' ),
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM)
WHERE TM_MES.TYPEMESURE = '1'
AND   TM_ORDO.ID = TEXM.ID
AND (TM_ORDO.DISPOSITIONHABILITATION IS NULL OR TM_ORDO.DISPOSITIONHABILITATION = 1);


-- vue mesures en attente de décret pour les ordonnances
CREATE OR REPLACE  VIEW "V_AN_MES_ATTENTE_DECRET_ORDO" ("ORDO_ID", "ORDO_MINISTERERESP", "ORDO_DATEPUBLICATION", "ORDO_DATEPROMULGATION", "ORDO_DATEENTREEENVIGUEUR", "ORDO_NATURETEXTE", "ORDO_PROCEDUREVOTE", "MESURE_ID", "MESURE_MINISTEREPILOTE") AS 
  SELECT
TM_ORDO.ID AS ORDO_ID,
TM_ORDO.MINISTEREPILOTE AS ORDO_MINISTERERESP,
TM_ORDO.DATEPUBLICATION AS ORDO_DATEPUBLICATION,
TM_ORDO.DATEPROMULGATION AS ORDO_DATEPROMULGATION,
TM_ORDO.DATEENTREEENVIGUEUR AS ORDO_DATEENTREEENVIGUEUR,
TM_ORDO.NATURETEXTE AS ORDO_NATURETEXTE,
TM_ORDO.PROCEDUREVOTE AS ORDO_PROCEDUREVOTE,
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE
FROM
(TEXTE_MAITRE TM_ORDO INNER JOIN ACTIVITE_NORMATIVE AN ON TM_ORDO.ID = AN.ID AND AN.APPLICATIONORDONNANCE = '1' ),
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM)
WHERE TM_ORDO.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU <> '1'
AND (TM_ORDO.DISPOSITIONHABILITATION IS NULL OR TM_ORDO.DISPOSITIONHABILITATION = 1);


--Vue mesures délais dernier pour les ordonnances
CREATE OR REPLACE  VIEW "V_AN_MES_DELAIS_DERNIER_ORDO" ("ORDO_ID", "ORDO_DATEPUBLICATION",  "MESURE_ID", "MESURE_MINISTEREPILOTE", "DELAIS_EN_MOIS", "DEC_DATEPUBLICATION") AS 
  SELECT ORDO_ID, ORDO_DATEPUBLICATION, MESURE_ID, MESURE_MINISTEREPILOTE,
CASE
  WHEN MES_DATEENTREEENVIGUEUR IS NULL 
  THEN (
    CASE WHEN DEC_DATEPUBLICATION < ORDO_DATEPUBLICATION THEN 0
    ELSE (abs(extract(day FROM ((DEC_DATEPUBLICATION - ORDO_DATEPUBLICATION) day TO second))) / 30) END
  )
  ELSE (
    CASE WHEN DEC_DATEPUBLICATION < MES_DATEENTREEENVIGUEUR THEN 0
    ELSE (abs(extract(day FROM ((DEC_DATEPUBLICATION - MES_DATEENTREEENVIGUEUR) day TO second))) / 30) END
  )
END DELAIS_EN_MOIS, DEC_DATEPUBLICATION
FROM (
  SELECT 
  TM_ORDO.ID AS ORDO_ID, 
  TM_ORDO.DATEPUBLICATION AS ORDO_DATEPUBLICATION,
  TM_MES.ID AS MESURE_ID,
  TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE,
  TM_MES.DATEENTREEENVIGUEUR AS MES_DATEENTREEENVIGUEUR,
  (SELECT MAX(MX_TM_DEC.DATEPUBLICATION)
                  FROM TEXM_MESUREIDS MX_TEXM, 
                  (TEXTE_MAITRE MX_TM_DEC INNER JOIN TEXM_DECRETIDS MX_TEXD   ON MX_TM_DEC.ID = MX_TEXD.ITEM)
                  WHERE TM_MES.ID = MX_TEXM.ITEM
                  AND   MX_TEXM.ID = MX_TM_DEC.ID 
                                  )as DEC_DATEPUBLICATION
  FROM 
  (TEXTE_MAITRE TM_ORDO INNER JOIN ACTIVITE_NORMATIVE AN ON TM_ORDO.ID = AN.ID AND AN.APPLICATIONORDONNANCE = '1'  ), 
  (TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM)
  WHERE TM_ORDO.ID = TEXM.ID
  AND   TM_MES.TYPEMESURE = '1'
  AND   TM_MES.APPLICATIONRECU = '1'
  AND (TM_ORDO.DISPOSITIONHABILITATION IS NULL OR TM_ORDO.DISPOSITIONHABILITATION = 1));


--Vue mesures délais premier pour les ordonnances
  CREATE OR REPLACE  VIEW "V_AN_MES_DELAIS_PREMIER_ORDO" ("ORDO_ID", "ORDO_DATEPUBLICATION", "MESURE_ID", "MESURE_MINISTEREPILOTE", "DELAIS_EN_MOIS", "DEC_DATEPUBLICATION") AS 
  SELECT
TM_ORDO.ID AS ORDO_ID,
TM_ORDO.DATEPUBLICATION AS ORDO_DATEPUBLICATION,
TM_MES.ID AS MESURE_ID,
TM_MES.MINISTEREPILOTE AS MESURE_MINISTEREPILOTE,
CASE
  WHEN TM_MES.DATEENTREEENVIGUEUR IS NULL
  THEN (
    CASE WHEN TM_DEC.DATEPUBLICATION < TM_ORDO.DATEPUBLICATION THEN 0
    ELSE (abs(extract(day FROM ((TM_DEC.DATEPUBLICATION - TM_ORDO.DATEPUBLICATION) day TO second))) / 30) END
  )
  ELSE (
    CASE WHEN TM_DEC.DATEPUBLICATION < TM_MES.DATEENTREEENVIGUEUR THEN 0
    ELSE (abs(extract(day FROM ((TM_DEC.DATEPUBLICATION - TM_MES.DATEENTREEENVIGUEUR) day TO second))) / 30) END
  )
END DELAIS_EN_MOIS, TM_DEC.DATEPUBLICATION AS DEC_DATEPUBLICATION
FROM
(TEXTE_MAITRE TM_ORDO INNER JOIN ACTIVITE_NORMATIVE AN ON TM_ORDO.ID = AN.ID AND AN.APPLICATIONORDONNANCE = '1'  ),
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM),
(TEXTE_MAITRE TM_DEC INNER JOIN TEXM_DECRETIDS TEXD   ON TM_DEC.ID = TEXD.ITEM)
WHERE TM_ORDO.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU = '1'
AND   TM_MES.ID = TEXD.ID
AND (TM_ORDO.DISPOSITIONHABILITATION IS NULL OR TM_ORDO.DISPOSITIONHABILITATION = 1)
AND   TM_DEC.DATEPUBLICATION = (SELECT MIN(MN_TM_DEC.DATEPUBLICATION)
								FROM TEXM_MESUREIDS MN_TEXM,
								(TEXTE_MAITRE MN_TM_DEC INNER JOIN TEXM_DECRETIDS MN_TEXD   ON MN_TM_DEC.ID = MN_TEXD.ITEM)
								WHERE TM_MES.ID = MN_TEXM.ITEM
								AND   MN_TEXM.ID = MN_TM_DEC.ID);


--Vue mesures publiées pour l'application des ordonnances
CREATE OR REPLACE VIEW "V_AN_MES_PUBLIEES_APP_ORDO" ("TM_MESURE_ID", "JOUR_DE_PUBLICATION", "MOIS_DE_PUBLICATION", "ANNEE_DE_PUBLICATION") AS 
  SELECT
TM_MES.ID AS TM_MESURE_ID,
EXTRACT(DAY FROM TM_DEC.DATEPUBLICATION) AS JOUR_DE_PUBLICATION,
EXTRACT(MONTH FROM TM_DEC.DATEPUBLICATION) AS MOIS_DE_PUBLICATION,
EXTRACT(YEAR FROM TM_DEC.DATEPUBLICATION)  AS ANNEE_DE_PUBLICATION
FROM
(TEXTE_MAITRE TM_ORDO INNER JOIN ACTIVITE_NORMATIVE AN ON TM_ORDO.ID = AN.ID AND AN.APPLICATIONORDONNANCE = '1' ),
(TEXTE_MAITRE TM_MES INNER JOIN TEXM_MESUREIDS TEXM   ON TM_MES.ID = TEXM.ITEM),
(TEXTE_MAITRE TM_DEC INNER JOIN TEXM_DECRETIDS TEXD   ON TM_DEC.ID = TEXD.ITEM)
WHERE TM_ORDO.ID = TEXM.ID
AND   TM_MES.TYPEMESURE = '1'
AND   TM_MES.APPLICATIONRECU = '1'
AND   TM_MES.ID = TEXD.ID
AND (TM_ORDO.DISPOSITIONHABILITATION IS NULL OR TM_ORDO.DISPOSITIONHABILITATION = 1)
AND   TM_DEC.DATEPUBLICATION = (SELECT MAX(MX_TM_DEC.DATEPUBLICATION)
								FROM TEXM_MESUREIDS MX_TEXM,
								(TEXTE_MAITRE MX_TM_DEC INNER JOIN TEXM_DECRETIDS MX_TEXD   ON MX_TM_DEC.ID = MX_TEXD.ITEM)
								WHERE TM_MES.ID = MX_TEXM.ITEM
								AND   MX_TEXM.ID = MX_TM_DEC.ID);


--Vue ordonnance appelant mesures pour l'application des ordonnances                  
CREATE OR REPLACE VIEW "V_AN_ORDOS_APPELANT_MESURE" ("ORDO_ID", "ORDO_MINISTERERESP", "ORDO_DATEPUBLICATION", "ORDO_DATEPROMULGATION", "ORDO_DATEENTREEENVIGUEUR")
                               AS
  SELECT TM_ORDO.ID             AS ORDO_ID,
    TM_ORDO.MINISTEREPILOTE     AS ORDO_MINISTERERESP,
    TM_ORDO.DATEPUBLICATION     AS ORDO_DATEPUBLICATION,
    TM_ORDO.DATEPROMULGATION    AS ORDO_DATEPROMULGATION,
    TM_ORDO.DATEENTREEENVIGUEUR AS ORDO_DATEENTREEENVIGUEUR
  FROM (TEXTE_MAITRE TM_ORDO
  INNER JOIN ACTIVITE_NORMATIVE AN
  ON TM_ORDO.ID          = AN.ID
  AND AN.APPLICATIONORDONNANCE = '1' )
  WHERE EXISTS
    (SELECT TM_MES.ID
    FROM TEXTE_MAITRE TM_MES
    INNER JOIN TEXM_MESUREIDS TEXM
    ON TM_MES.ID  = TEXM.ITEM
    WHERE TEXM.ID = TM_ORDO.ID
    )
  AND TM_ORDO.APPLICATIONDIRECTE <> 1
  AND (TM_ORDO.DISPOSITIONHABILITATION IS NULL OR TM_ORDO.DISPOSITIONHABILITATION = 1);


--Vue ordonnance appelant mesures vig pour l'application des ordonnances
CREATE OR REPLACE VIEW "V_AN_ORDOS_APPELANT_MESURE_VIG" ("ORDO_ID", "ORDO_MINISTERERESP", "ORDO_DATEPUBLICATION", "ORDO_DATEPROMULGATION", "ORDO_DATEENTREEENVIGUEUR")
                               AS
  SELECT TM_ORDO.ID             AS ORDO_ID,
    TM_ORDO.MINISTEREPILOTE     AS ORDO_MINISTERERESP,
    TM_ORDO.DATEPUBLICATION     AS ORDO_DATEPUBLICATION,
    TM_ORDO.DATEPROMULGATION    AS ORDO_DATEPROMULGATION,
    TM_ORDO.DATEENTREEENVIGUEUR AS ORDO_DATEENTREEENVIGUEUR
  FROM (TEXTE_MAITRE TM_ORDO
  INNER JOIN ACTIVITE_NORMATIVE AN
  ON TM_ORDO.ID          = AN.ID
  AND AN.APPLICATIONORDONNANCE = '1' )
  WHERE EXISTS
    (SELECT TM_MES.ID
    FROM TEXTE_MAITRE TM_MES
    INNER JOIN TEXM_MESUREIDS TEXM
    ON TM_MES.ID  = TEXM.ITEM
    WHERE TEXM.ID = TM_ORDO.ID
    )
  AND NOT EXISTS
    (SELECT TM_MES.ID
    FROM TEXTE_MAITRE TM_MES
    INNER JOIN TEXM_MESUREIDS TEXM
    ON TM_MES.ID          = TEXM.ITEM
    WHERE TEXM.ID         = TM_ORDO.ID
    AND TM_MES.TYPEMESURE = '1'
    )
  AND TM_ORDO.APPLICATIONDIRECTE  <> 1
  AND TM_ORDO.DATEENTREEENVIGUEUR IS NOT NULL
  AND (TM_ORDO.DISPOSITIONHABILITATION IS NULL OR TM_ORDO.DISPOSITIONHABILITATION = 1);
  
  
-- Vue loi corrigée pour la récupération du premier décret
CREATE OR REPLACE VIEW "V_AN_MESURES_DELAIS_PREMIER" ("LOI_ID", "LOI_DATEPROMULGATION", "LOI_NATURETEXTE", "MESURE_ID", "MESURE_MINISTEREPILOTE", "DELAIS_EN_MOIS", "DEC_DATEPUBLICATION")
                            AS
  SELECT TM_LOI.ID          AS LOI_ID,
    TM_LOI.DATEPROMULGATION AS LOI_DATEPROMULGATION,
    TM_LOI.NATURETEXTE      AS LOI_NATURETEXTE,
    TM_MES.ID               AS MESURE_ID,
    TM_MES.MINISTEREPILOTE  AS MESURE_MINISTEREPILOTE,
    CASE
      WHEN TM_MES.DATEENTREEENVIGUEUR IS NULL
      THEN (
        CASE
          WHEN TM_DEC.DATEPUBLICATION < TM_LOI.DATEPUBLICATION
          THEN 0
          ELSE (ABS(extract(DAY FROM ((TM_DEC.DATEPUBLICATION - TM_LOI.DATEPUBLICATION) DAY TO second))) / 30)
        END )
      ELSE (
        CASE
          WHEN TM_DEC.DATEPUBLICATION < TM_MES.DATEENTREEENVIGUEUR
          THEN 0
          ELSE (ABS(extract(DAY FROM ((TM_DEC.DATEPUBLICATION - TM_MES.DATEENTREEENVIGUEUR) DAY TO second))) / 30)
        END )
    END DELAIS_EN_MOIS, TM_DEC.DATEPUBLICATION AS DEC_DATEPUBLICATION
  FROM (TEXTE_MAITRE TM_LOI
  INNER JOIN ACTIVITE_NORMATIVE AN
  ON TM_LOI.ID          = AN.ID
  AND AN.APPLICATIONLOI = '1' ),
    (TEXTE_MAITRE TM_MES
  INNER JOIN TEXM_MESUREIDS TEXM
  ON TM_MES.ID = TEXM.ITEM),
    (TEXTE_MAITRE TM_DEC
  INNER JOIN TEXM_DECRETIDS TEXD
  ON TM_DEC.ID               = TEXD.ITEM)
  WHERE TM_LOI.ID            = TEXM.ID
  AND TM_MES.TYPEMESURE      = '1'
  AND TM_MES.APPLICATIONRECU = '1'
  AND TM_MES.ID              = TEXD.ID
  AND TM_DEC.DATEPUBLICATION =
    (SELECT MIN(MN_TM_DEC.DATEPUBLICATION)
    FROM TEXM_MESUREIDS MN_TEXM,
      (TEXTE_MAITRE MN_TM_DEC
    INNER JOIN TEXM_DECRETIDS MN_TEXD
    ON MN_TM_DEC.ID = MN_TEXD.ITEM)
    WHERE TM_MES.ID = MN_TEXM.ITEM
    AND MN_TEXM.ID  = MN_TM_DEC.ID
    );
