--Requête qui supprime les décrets qui sont liés à des ordonnances pour la partie ratification des ordonnances
DELETE FROM TEXM_DECRETIDS WHERE TEXM_DECRETIDS.ITEM IN (
select  TEXM_DECRETIDS.ITEM 
from TEXTE_MAITRE TM_ORD 
INNER JOIN    TEXM_DECRETIDS
ON TM_ORD.ID = TEXM_DECRETIDS.ID
INNER JOIN ACTIVITE_NORMATIVE AN      
ON TM_ORD.ID  = AN.ID 
INNER JOIN TEXTE_MAITRE TM_DEC ON TM_DEC.ID = TEXM_DECRETIDS.ITEM
WHERE  AN.ORDONNANCE = '1');
