-- généré le 10 juillet 2018 à partir du liquibase showSQL (cf 70-ddl-dev-epg-indexation.xml)

CREATE TABLE DOSSIERINDEXATIONQUERY (
   DOSSIERID VARCHAR2(36) NOT NULL,
   EVENTDATE TIMESTAMP,
   INDEXATIONDATE TIMESTAMP,
   INDEXATIONMASSIVEDATE TIMESTAMP,
   DELETED NUMBER(1),
   CONSTRAINT PK_DOSSIERINDEXATIONQUERY PRIMARY KEY (DOSSIERID)
);

CREATE INDEX IDX_DIQ_INDEXATIONDATE ON DOSSIERINDEXATIONQUERY(INDEXATIONDATE);
CREATE INDEX IDX_DIQ_INDEXATIONMASSIVEDATE ON DOSSIERINDEXATIONQUERY(INDEXATIONMASSIVEDATE);

CREATE TABLE DOSSIERINDEXATIONSTATUS (
   DOSSIERID VARCHAR2(36) NOT NULL,
   LASTERRORDATE TIMESTAMP,
   LASTINDEXATIONDATE TIMESTAMP,
   MESSAGE VARCHAR2(3500),
   STATUS VARCHAR2(25),
   CONSTRAINT PK_DOSSIERINDEXATIONSTATUS PRIMARY KEY (DOSSIERID)
);

CREATE INDEX IDX_DIS_LASTINDEXATIONDATE ON DOSSIERINDEXATIONSTATUS(LASTINDEXATIONDATE);
CREATE INDEX IDX_DIS_STATUS ON DOSSIERINDEXATIONSTATUS(STATUS);

ALTER TABLE DOSSIERINDEXATIONSTATUS ADD CONSTRAINT FK_DIS_DIQ FOREIGN KEY (DOSSIERID) REFERENCES DOSSIERINDEXATIONQUERY (DOSSIERID);