CREATE UNIQUE INDEX "INFO_UTIL_CONNECT_ISLOGOUT" ON "INFO_UTILISATEUR_CONNECTION" ("ISLOGOUT", "ID");

CREATE UNIQUE INDEX "INFO_UTIL_CONNECT_USERNAME" ON "INFO_UTILISATEUR_CONNECTION" ("USERNAME", "ID");

commit;